### ISSUE TITLE
Can't get to run or build on macOS

### ISSUE THREAD

**Issue by jbellanca** [comictagger/comictagger#121]
Can someone provide instructions to get ComicTagger 1.1.30-rc1 to run on MacOS 10.14? I've got everything installed right that I can think of - Python, beautifulsoup4, configparser, pyqt5... and just can't get it to work from the source. Setup.py just gives errors. And the file on the release page isn't a .app or .py or any other file that I can think of to get working. I'd really, really, really appreciate help getting it working. Hoping that the updates fix the problems with the ComicVine API returning thousands of results, but just can't get it to work. Thanks.

**Comment by davide-romanini** [comment]
Did you try to run the file at https://github.com/davide-romanini/comictagger/releases/download/untagged-0565c2a87a706c64e033/comictagger-1.1.30-rc1? I don't have anymore access to a Mac so I just built it on travis but never tried it out. 
Just give it a try.

**Comment by kedickso** [comment]
If you chmod +x the file that is downloaded, you can run it from terminal on the Mac, but it has multiple show-stopping issues: Crashes on any drag & drop event, search results have not been corrected to adopt the new search API from comicVine resulting in thousands of pages of results being returned for simple searches, which then result in temporary API blocking from ComicVine due to the traffic.

**Comment by Sparks01** [comment]
Kedickso,

Do we know if there's a working version right now on either platform? I've abandoned the Mac app because no version will run properly on it, but the error you describe above (ComicVine API) is also found in the Win version. So right now this all seems unusable. 

Cheers

**Comment by kedickso** [comment]
The newest 1.1.31 RC on windows seems to work fine and corrects the issues with searches returning too many results. I’m still unable to get a working build for Mac, so for now I’m just using the Windows version in a VM I built just to run the application.

**Comment by Sparks01** [comment]
Thanks! I didn't see that there had been a new RC since 1.1.30. That seems to be working. My Mac is older so I can't get a working version of it on there either. In the meantime, I've got that on a Win 10 machine that can see a shared Mac folder so I can run the app in Windows but still access the files. 

Thanks for the heads up.

**Comment by jbellanca** [comment]
Any more luck with 1.1.31 RC on the Mac? Got 1.1.30-rc1 to run from its release but as you all know, it still returns too many results from CV. I may have to resort to the Windows version, too, I guess. Appreciate everyones hard work on this.

**Comment by kedickso** [comment]
@jbellanca I've been able to get 1.1.31 RC to build successfully, and can verify that it fixes search results. However, drag & drop is still apparently broken as it causes the app to crash any you drag a file into the application window.

**Comment by jbellanca** [comment]
Yeah I verified that 1.1.131 RC works with pulling results on the Windows side, but I haven't been able to build it on the Mac, and there's no release build on GitHub here either, and saw that 1.1.30 RC breaks drag and drop (which is fine, that's minor). Do you have a build of 1.1.31 RC on the Mac that I could download?

**Comment by kedickso** [comment]
@jbellanca https://www.dropbox.com/s/ritwi4cwrpm9o7a/ComicTagger-1.1.31RC.zip?dl=0

**Comment by erikbennett** [comment]
@kedickso I tried running your compiled version, but it's constantly telling me my unrar isn't properly configured. I know it isn't, as I upgraded to your version from a working on because of this "too many search results" issue with ComicVine.

**Comment by eduo** [comment]
Hi

Were build instructions provided in the end elsewhere? There's a simple error that requires changing the TLS version but I can't manage to build the app in MacOS. I must be missing something.

Existing instructions in the Wiki are from 4 years ago and don't work on MacOS.

The two lines that need changing to get comictagger working back are on [this commit](https://github.com/davide-romanini/comictagger/pull/135/files).

**Comment by lordwelch** [comment]
The current alpha release does not have this issue.
