### ISSUE TITLE
Allowing for pathnames in Rename Template

### ISSUE THREAD

**Issue by ScuttleSE** [comictagger/comictagger#123]
Would it be possible to allow pathnames in the rename template?

This way it would be very easy and fast to move a comic to its proper folder

`/ComicArchive/%publisher/%series%/%series% Vol.%year% #%issue%` for example

**Comment by Brodieman** [comment]
Second

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.1](https://github.com/comictagger/comictagger/releases/tag/1.4.1)
