### ISSUE TITLE
CLI mode background execution

### ISSUE THREAD

**Issue by sbrownlow** [comictagger/comictagger#127]
I noticed that with 1.1.31-rc1 for Windows that the CLI is returning to the command prompt immediately and executing in the background. This is bad for a batch/CLI interface as I cannot be sure the operation completed before moving on to the next step. All console output including version and help is also missing due to no stdout available.

**Comment by davide-romanini** [comment]
The problem seem related to running it in Powershell.
It seems to work correctly using [Git Bash](https://gitforwindows.org/) on windows. 
Maybe you can use it in the meanwhile.

**Comment by davide-romanini** [comment]
The problem seems related to running it on PowerShell.
It works using [GitBash](https://gitforwindows.org/). Maybe you can use it until we find a solution.

**Comment by davide-romanini** [comment]
Should be easy to fix just adding the console flag to the pyinstaller spec file.
