### ISSUE TITLE
App contains version 0.0.0 instead of 1.2.1

### ISSUE THREAD

**Issue by suschizu** [comictagger/comictagger#146]
Hello! I think you forgot to update the version number :)
<img width="314" alt="Screenshot 2019-09-28 at 23 05 51" src="https://user-images.githubusercontent.com/16004333/65822498-6d8ba580-e245-11e9-9686-25434f67e8d1.png">

**Comment by davide-romanini** [comment]
Fixed in 1.2.2.

**Comment by core-code** [comment]
i can confirm this is fixed. thank you
