### ISSUE TITLE
Consider pip-only release for the linux platform

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#150]
At this moment, we don't have a specific release for the linux platform.
I tried the resulting Pyinstaller generated from Travis but was totally bugged and unusable.

We should decide if we want:
 * fix any pyinstaller issue and provide a stable linux release
 * drop the pyinstaller exe for linux and provide it only via pip

**Comment by beville** [comment]
My opinion is that there is no need to build a binary Linux version. The pip source release should be sufficient.

Also, I had a go at trying to add desktop integration (icon and launch shortcut) to the pip release for the different platforms, but punted on it.  I think I had some of it working, but can't remember why I bailed.  Pretty sure that the Linux version worked on Ubuntu, anyways.

The remnants of my attempt are in the "desktop-integration" folder and the commented-out section of setup.py, where it looks like I had set up some post install actions.

If this is only implemented for the Linux systems, that might be enough.
