### ISSUE TITLE
ctversion.py missing

### ISSUE THREAD

**Issue by kpi88** [comictagger/comictagger#165]
Apologies in advance if I'm missing something. As of release 1.2.1, comictagger source is no longer including comictaggerlib/ctversion.py. Without this the software will not run. I was able to pull a copy from 1.2.0 to get the program running.

**Comment by davide-romanini** [comment]
The ctversion is now written automatically as part of the setup phase.
If you are working from the cloned repository (or source distribution) you should always do a `pip install .` or `python setup.py develop` before running comictagger.
Feel free to join [our gitter channel](https://gitter.im/comictagger/community) if you are in trouble 😃

**Comment by kpi88** [comment]
Thank you for the guidance. You may want to add 'pip install .' to your
'from source' installation instructions.

**Comment by davide-romanini** [comment]
You're right, the README is misleading in this regard.
I'll fix that as soon as I can. Thanks!

**Comment by zapisnicar** [comment]
ctversion.py is missing again, probably because of .gitignore line 2

**Comment by lordwelch** [comment]
You need to run `python setup.py --version`
Or run `pip install .`
