### ISSUE TITLE
No image from Comic Vine

### ISSUE THREAD

**Issue by Nosirus** [comictagger/comictagger#167]
comictagger finds the comics, but I have no image to compare with "Search Online".

**Comment by Tommm777** [comment]
True. Unable to use manual-visual matching.  But, Interestingly if the comic has alternate covers available tagger seems to display these.  An Indexing problem? A change in the way ComicVine returned the info?  Must be something like that.  Tested versions 1.22 up and all show same behavior. Automated matching seems to be working great...

**Comment by bookmunkie** [comment]
I'm getting the same in ComicTagger v1.3.0-alpha.o

![image](https://user-images.githubusercontent.com/14288539/75813866-c3b5c500-5d5e-11ea-96ff-15277ab00b8d.png)
![image](https://user-images.githubusercontent.com/14288539/75814051-18594000-5d5f-11ea-8cb3-432c6d07f8d9.png)

The one place they do show up is during auto-tagging:
![image](https://user-images.githubusercontent.com/14288539/76569301-29a1fb00-6489-11ea-8017-a337acdd6374.png)

**Comment by bookmunkie** [comment]
I'm guessing this must be due to a change in the ComicVine API. Versions 1.2.1 and 1.2.0 do the same thing. It's making things a little tough.

**Comment by ReallDeadpool** [comment]
I have the same isue

**Comment by lordwelch** [comment]
The current alpha release does not have this issue.
