### ISSUE TITLE
Comic Vine Not Reachable

### ISSUE THREAD

**Issue by japeberg** [comictagger/comictagger#168]
Tagging aborts with message: 
> Could not connect to Comic Vine to search for series!

Already checked, the key is valid according to Comic Vine but not according to ComicTagger.

Logging reports this error:
> <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:852)>

OS: Ubuntu 18.04
Software-Version: 1.1.31-rc1

**Comment by lordwelch** [comment]
fixed in #189
