### ISSUE TITLE
Not really issues but small feature requests

### ISSUE THREAD

**Issue by DOS76** [comictagger/comictagger#169]
when you add things but try to move to the next item without saving the program prompts you with a yes or no option to either move to the next item without saving (yes) or doing nothing (no). Instead offering 3 options 1 save and move to the next item 2 don't save and move to the next item or 3 do nothing would make it more efficient when using. 2 when you search something and it returns 0 matches it still opens an empty form that the user has to then close. I mean even if the form was made to be in focus and you could just press enter and close it but how it is currently you have to navigate to it with your mouse. Either way this is a good program and this are just small quality of life improvements and not something essential to the program. Thanks for listening

**Comment by lordwelch** [comment]
I have tried to implement this as much as possible in #220. If you notice anything else feel free to open a new issue.
