### ISSUE TITLE
Adding custom tags to store volume and issue ID's

### ISSUE THREAD

**Issue by ErenPhayte** [comictagger/comictagger#170]
Hi,

Is there a way to store [Issue ID 660010] sitting in notes into two custom fields? I have comicrack, and used a plugin for the data however it's not as accurate as this tool. However, all my comics have two fields

comicvine_issue
comicvine_volume

and it would be great if there was a way to populate these two fields with the respective data, especially when doing refreshes on data.

**Comment by Drudoo** [comment]
The issue with ComicRack's custom values (like `comicvine_issue` and `comicvine_volume`) is that they are not stored in the `ComicInfo.xml` file in the cbz archive. The values are stored in the `ComicDb.xml` database that ComicRack uses. Each entry in ComicRack has a `<CustomValueStore>` where these values are stored. 

So even if comictagger could store them in the `ComicInfo.xml` file, ComicRack wouldn't read them.
