### ISSUE TITLE
Asterisk (*) in Series field causes crash during automated rename

### ISSUE THREAD

**Issue by katzmeowski** [comictagger/comictagger#171]
Platform: Windows 10 GUI
Release version: 1.2.3
Steps to reproduce issue:
- Include an asterisk character in Series field
    - See, for example, _ALF* Annual_ series [here](https://comicvine.gamespot.com/alf-annual/4050-4043/)
- Include `%series%` macro in renaming template (in Rename Settings)
    - Example template: `%year% %series% #%issue%`
- Execute automated rename of affected archive

When the renamer encounters the asterisk, the app hangs for a moment before crashing and closing. Asterisks in other metadata fields used in the renaming template likely cause the same issue, though I have not tested that. Likely related to previous issues with `"` #68 and `:` #18 and other forbidden characters being filtered out before saving to filename, including `\ / ? % * : | " < >`.

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.1](https://github.com/comictagger/comictagger/releases/tag/1.4.1)
