### ISSUE TITLE
GUI always opens

### ISSUE THREAD

**Issue by PiDockMedia** [comictagger/comictagger#173]
I am on Mac OS X 10.15.4 and I am trying to use the CLI to read CR tags and write them out to CBL tags but when I run the find/sed/xargs it just opens the GUI and adds them all to a list. How do I actually get it to run without the GUI? I have tried the normal Mac install and a homebrew install with the same result. This is the latest 1.3.0a\

**Comment by lordwelch** [comment]
A new alpha release has just been posted and the CLI interface works using the .app on the release page.
Note I only have access to an M1 Mac mini on macOS 12.0.1 to test
