### ISSUE TITLE
Month not always 2 digit

### ISSUE THREAD

**Issue by TheRonGDD** [comictagger/comictagger#175]
Rename set to %year%-%month% - %series% #%issue%
To set reader to show all series flat and by file name to read multiple series in chronological order.

Scrape seem to pull whatever is on comicvine which could be 2 digit or one for the month. 
Rename has no option that I see to set month digit.

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.1](https://github.com/comictagger/comictagger/releases/tag/1.4.1)

use `{month:02d}`
