### ISSUE TITLE
Help with Humble Bundle filenames

### ISSUE THREAD

**Issue by tlc** [comictagger/comictagger#176]
I buy a lot of large Humble Bundles (mostly) consisting of trade paperbacks..  They have crappy file naming that doesn't match what comictagger needs.

```
BlackScience_vol1.cbz
Invincible_vol1_1398382571.cbz
...
StrayBullets_vol1_1420484117.cbz
...
blackscience_vol2.cbz
...
straybullets_sunshineandroses_vol1.cbz
...
straybullets_vol2.cbz
...
```

I've been using the CT GUI and all told, it's a lot of work.  (This HB has 91 trade paperbacks.)  I can change the filenames, splitting the title words and changing "vol" to "v",  before using CT.  I can even add '#1'.  But it seems like for some trades vol2 has only issue \#1 and for others vol2 has only issue \#2.  (I imagine this is a comicvine issue, not CT.)

Or I can tweak these entries in the GUI before calling Search Online.  Either way it's a lot of hand work and even then Auto-identify rarely matches and Search Online takes a few clicks.  I have not really used the command line tagging -- I assume that's like auto-tagging and if I'm not getting good matches in the GUI, it might tag them wrong.

What can I do to improve my workflow?  How can I automate more so this takes less time?

**Comment by lordwelch** [comment]
Hello, I just made a pull request (#193) that would help with some of the issues.
I bought the recent Judge Dredd and Isekai bundles on Humble to test with and ComicTagger now successfully tags 71/113 comics which is pretty good.

The remaining fall into a few different categories of issues:

Mispelled on Humble:
* judgederedd_orgins_ -> Judge Dredd Origins

Mispelled on Comic Vine:
* dredd_finaljudgement -> Dredd: Final Judgment

Split when it didn't need to be:
* mazeworld -> Mazeworld

Full title not matched:
* absolom_vol1 -> Absalom: Ghosts Of London
* kingdom_vol1 -> [Kingdom #001 The Promised Land](https://comicvine.gamespot.com/kingdom-1-the-promised-land/4000-333638/)
* kingdom_vol2 -> [Kingdom #002 Call of the Wild](https://comicvine.gamespot.com/kingdom-2-call-of-the-wild/4000-333639/)
* kingdom_vol3 -> [Kingdom: Aux Drift](https://comicvine.gamespot.com/kingdom-aux-drift-1-tpb/4000-583940/)
* kingdom_vol4 -> [Kingdom: Alpha and Omega](https://comicvine.gamespot.com/kingdom-alpha-and-omega-1-volume-4/4000-738503/)

The first two are obviously issues with Humble and Comic Vine respectively the third one is unfortunately just something that will have to be dealt with manually, the last one is not so clear for example [Comic Vine](https://comicvine.gamespot.com/search/?i=volume&q=absalom) has all three separately listed _Absalom: Ghosts Of London_, _Absalom: Under A False Flag_ and _Absalom: Terminal Diagnosis_.
The [Grand Comics Database](https://www.comics.org/series/169004/details/) has a single series with the name Absalom and a title of _Ghosts of London_.
I haven't used the GCD much but I know that Comic Vine is not completely consistent on when they are a series or separate when it comes to trade paperbacks and the info found on the comic itself usually doesn't help with that decision, as seen with the Kingdom series.

**Comment by lordwelch** [comment]
Screenshots on how to enable word splitting in the latest alpha are located on the announcement for [1.4.4-alpha.4]

[1.4.4-alpha.4]: https://github.com/comictagger/comictagger/discussions/296
