### ISSUE TITLE
Make adding artist / writer possible in filenames when renaming

### ISSUE THREAD

**Issue by jfml** [comictagger/comictagger#177]
Hi, I'm loving comictagger so far but it kinda bugs me that it's not possible to rename files with (primary?) artist and writer names. I mostly have (european) graphic novels and while I know that comic tagger is very US centric it would be really cool to have 

%artist%  
%writer%

because this are quite important with graphic novels (and since I'm an illustrator as well it would be nice to be able to credit creators in filenames as well ^__^)

Would this be possible at some point?

Thanks a lot and keep up the good work!

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.1](https://github.com/comictagger/comictagger/releases/tag/1.4.1)

use `{artist}` or `{writer}`

**Comment by jfml** [comment]
Hi! Updated to 1.4.1 but unfortunately it doesn't seem to work for me +__+  Am I supposed to use {} instead of %%? Curly brackets seem to brake things for me:

![grafik](https://user-images.githubusercontent.com/4312909/163960042-787be18b-3489-4789-8a29-5426ca843c2c.png)

**Comment by lordwelch** [comment]
You must select the 'Enable the new renamer' checkbox
![image](https://user-images.githubusercontent.com/7547075/163963342-510e6c41-ad0a-43d2-9610-c227d42b609f.png)

**Comment by jfml** [comment]
Ahhh, that did the trick, sorry! So cool, thanks a lot!
