### ISSUE TITLE
7zip Support

### ISSUE THREAD

**Issue by Protektor-Desura** [comictagger/comictagger#179]
What is the possibility of seeing 7zip support since it has tight compression and is free unlike RAR? Even has python code you can already use:
https://pypi.org/project/py7zr/
https://github.com/miurahr/py7zr

**Comment by MichaelFitzurka** [comment]
I have a working 7zip in my branch ... that as of yesterday stopped working for other reasons.
I'm rebaselining to this branch as it now has active updates going on and I will separate and upload my changes to get 7zip working here.

**Comment by MichaelFitzurka** [comment]
Added pull request: https://github.com/comictagger/comictagger/pull/225

**Comment by MichaelFitzurka** [comment]
Pull request merged - issue closed.
