### ISSUE TITLE
colon (":") handling

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#18]
_From [TheDomin...@gmail.com](https://code.google.com/u/106062039756062406940/) on May 12, 2013 02:35:15_

What steps will reproduce the problem? 1. Opening comictagger
2. Tagging a comic that in it's name contains a colon and not being able to decide 
what to do with this kind of special characters. What is the expected output? What do you see instead? The input is "Series: Blah blah"
The output that I was expecting was "Series- Blah blah"
The output that I get is "Series - Blah blah" What version of the product are you using? On what operating system? As of now I'm using version 1.1.9-beta
OSX Lion Please provide any additional information below. I would like to see the ability to determine how to handle the colon or other special characters.
I liked the way the colon was handle in version 1.1.7 because that way I could determine if the series title had a colon or a hyphen easily. For now I think I'll go back to version 1.1.7

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=18_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 24, 2014 08:16:27_

Changed from "Defect" to "Enhancement"

**Labels:** -Type-Defect Type-Enhancement

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.1](https://github.com/comictagger/comictagger/releases/tag/1.4.1)

To get the requested format you will need to disable smart text cleanup
