### ISSUE TITLE
TypeError: object of type 'float' has no len()

### ISSUE THREAD

**Issue by Baton4986** [comictagger/comictagger#180]
If you try to rename a comic that has a float number in the issue field (e.g. 1.0) no window will open. This happens e.g. with files which were edited with calibre-plugin before. You get the following message on the console:
File "/home/ramon/.local/lib/python3.6/site-packages/comicapi/issuestring.py", line 44, in __init__
TypeError: object of type 'float' has no len()
I changed Line 44 in /home/ramon/.local/lib/python3.6/site-packages/comicapi/issuestring.py from:
        if len(text) == 0:
to
        if len(str(text)) == 0:

Everything is fine now :)

**Comment by lordwelch** [comment]
fixed in #214
