### ISSUE TITLE
Write metadata to multiple files at once

### ISSUE THREAD

**Issue by jfml** [comictagger/comictagger#181]
Not sure if this would be possible but if you have a series it would be super awesome if you could edit artist, writer, publisher etc. for all issues at once. Keep up the good work! ^__^

**Comment by jwmcdermaid** [comment]
I agree with this, it would be extremely useful, if possible of course.

On Jan 5, 2021, at 2:53 AM, jfml <notifications@github.com> wrote:

﻿

Not sure if this would be possible but if you have a series it would be super awesome if you could edit artist, writer, publisher etc. for all issues at once. Keep up the good work! ^__^

**Comment by lordwelch** [comment]
closing this as a duplicate of  #23
