### ISSUE TITLE
App crashes on rename with quotation marks

### ISSUE THREAD

**Issue by themeatsweats** [comictagger/comictagger#184]
Windows doesn't allow " characters in filenames, so when I try to rename a file with them in it's tag, the app explodes. Not really surprising or a big deal to fix/workaround, but took me a few minutes to figure out why it was exploding when bulk renaming today. Maybe CT should check and replace with single quotes, at least in the filenames?

**Comment by lordwelch** [comment]
Would you be able to test pull request #129 and test to see if it fixes your issue?

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.1](https://github.com/comictagger/comictagger/releases/tag/1.4.1)
