### ISSUE TITLE
Saving metadata overwrites ComicInfo.xml

### ISSUE THREAD

**Issue by codedread** [comictagger/comictagger#185]
I have many archives with small ComicInfo.xml files like this:

```
<ComicInfo>
  <SomeOtherElement xmlns="some-other-namespace" someValue="foo"></SomeOtherElement>
</ComicInfo>
```

However, when I update metadata using ComicTagger in ComicRack format, it overwrites the contents of the ComicInfo and deletes the <SomeOtherElement> tag.

ComicTagger should only add to the XML file, not remove unrecognized elements (especially those in other XML namespaces)

**Comment by lordwelch** [comment]
@codedread could you test the build from pullrequest #202 you can get it either from clicking on the green checkmark next to the commit or by going here https://github.com/comictagger/comictagger/actions/runs/1302416694

**Comment by codedread** [comment]
Sorry @lordwelch - I didn't act on this last year and now I'm unsure how to get access to a build that has this patch. Is it included in a recent release?

**Comment by lordwelch** [comment]
No problem I didn't realize that GitHub actions didn't keep artifacts so I'll just upload it as a comment later tonight

**Comment by lordwelch** [comment]
So it turns out that GitHub has a limit of 25 MB on attachments and comictagger sits around 40MB I uploaded it to mega.io
https://mega.nz/folder/m9wDUApI#xowVnn5Vh8n8SCrn-KMBvQ it is also available on the current run of the GitHub Action which will expire in 30 days

**Comment by codedread** [comment]
Hi there - I have verified that this build doesn't overwrite existing XML tags. One little nit I have is that it took

```xml
<ComicInfo>
  <SomeOtherElement xmlns="some-other-namespace" someValue="foo"></SomeOtherElement>
</ComicInfo>
```

and rewrote it as:

```xml
<ComicInfo xmlns:ns0="some-other-namespace">
  <ns0:SomeOtherElement someValue="foo" />
</ComicInfo>
```

Since this is essentially the same XML (if memory serves), I think that's ok. I assume this is just a Python XML library doing it's job. I like the self-closing tag better, and the namespace prefix declared at the top is fine.

**Comment by lordwelch** [comment]
Thanks for the input, the XML changes come from using the built-in etree library. I have another change I'm trying to put in before I merge this pull request, but I plan to merge it in the next month or two
