### ISSUE TITLE
dark mode for windows?

### ISSUE THREAD

**Issue by phanirithvij** [comictagger/comictagger#194]
Is it already implemented? I couldn't find it in the settings. Using v1.3.0-alpha.0

**Comment by lordwelch** [comment]
No there is not currently one implemented. A quick search shows that this [might not be to difficult](https://stackoverflow.com/questions/48256772/dark-theme-for-qt-widgets) to implement

**Comment by lordwelch** [comment]
There are no current plans to implement a dark mode, however you can add `-- -platform windows:darkmode=2` to the end of the arguments passed to comictagger
Below is an example of creating a link to enable _a_ darkmode on windows however it is not very good
![Capture](https://user-images.githubusercontent.com/7547075/145754033-458430ae-0e3d-42bb-9b8e-5d7d34415be6.PNG)
![darkmode](https://user-images.githubusercontent.com/7547075/145754600-dd511adc-fc55-419c-9c3e-6a291842bb71.PNG)

**Comment by lordwelch** [comment]
There is now a specific option `--darkmode` which will enable this and should be used in place of `-- -platform windows:darkmode=2` in the example above
There are no plans to create a manual darkmode but a PR would be accepted
