### ISSUE TITLE
pull request #189 seriesSearch undoes the fix isue #143

### ISSUE THREAD

**Issue by thFrgttn** [comictagger/comictagger#197]
#143 due to the number of volumes with matching names, recent x-man and spider-man series are not in the default number of return results from comicvine,
This was fixed by increasing the number of return results, but #189 is missing this fix.
Its a simple as adding 
        params = {
           ...
            'page': 1,
            'limit': 100
        }

**Comment by lordwelch** [comment]
@thFrgttn thanks for the notice I will put the fix back in shortly.

**Comment by thFrgttn** [comment]
np, I only noticed because I've been playing with sorting and filtering those results

**Comment by lordwelch** [comment]
Published a new pre-release.
