### ISSUE TITLE
Update to more current version of Natsort

### ISSUE THREAD

**Issue by bpepple** [comictagger/comictagger#203]
comictagger uses an _extremely_ old version of natsort, and if the user uses any other software that uses natsort it will cause conflicts. In addition, comictagger only seems to use it here, so it make sense to update to a more current version:

https://github.com/comictagger/comictagger/blob/93f5061c8f023ed838bc968f1c06f1ed4c3275fb/comicapi/comicarchive.py#L818

And to update it should only require modifying to something like this (depending if you wanted to drop the corresponding key function):

`files = natsorted(files, alg=ns.IGNORECASE)`

**Comment by lordwelch** [comment]
Thanks for the issue! I have a pull request open with the fix and plan to merge it soon

**Comment by lordwelch** [comment]
This has now been merged
