### ISSUE TITLE
Segmentation fault in 1.3.0 alpha on MacOS Big Sur (11.4)

### ISSUE THREAD

**Issue by carlosedp** [comictagger/comictagger#205]
Tried running latest 1.3.0 alpha on MacOS Big Sur (11.4) but I'm getting a segmentation fault (when trying to run from terminal). 

```
❯ ~/Downloads/ComicTagger.app/Contents/MacOS/comictagger
[1]    28723 segmentation fault  ~/Downloads/ComicTagger.app/Contents/MacOS/comictagger
```

Also tried 1.3.0a1 but same happens.

**Comment by lordwelch** [comment]
Hello @carlosedp I just pushed a new alpha release at https://github.com/comictagger/comictagger/releases/tag/1.3.0-alpha.4
I was able to test it on macOS 12.0.1 with a M1 Mac mini can you check if it works for you?

**Comment by carlosedp** [comment]
Yep, It worked! Thanks!
