### ISSUE TITLE
Can't run ui on linux

### ISSUE THREAD

**Issue by astrid-dev** [comictagger/comictagger#208]
when running from terminal in linux got a window with a throw exception

![Screenshot from 2021-12-17 22-13-57](https://user-images.githubusercontent.com/6403537/146628575-02fe039c-234f-4546-97f0-535ccde13490.png)

SO: Archlinux
Kernel: 5.15.6-arch2-1
comictagger version: 1.3.0a4
python version: 3.10.1
installed with: `pip install comictagger`
command to start: `comictagger`

**Comment by lordwelch** [comment]
Hello @rurickdev, this appears to be an incompatibility with newer versions of PyQt. PyQt should be limited to versions <= 5.15.3 through the requirements file and I know that there are no wheels for Python 3.10 and PyQt5 5.13.3 so it is probably an issue with Arch using the latest PyQt.
In any case the next alpha release will fix this issue.

**Comment by astrid-dev** [comment]
Awesome, I'll wait till that.
keep the good work!
