### ISSUE TITLE
1.3.0 alpha 4 - Not writing tags to .cbr files on MacOS

### ISSUE THREAD

**Issue by Sparks01** [comictagger/comictagger#210]
When trying to write tags to .cbr files the tags are not being written. File stays the same.

**Comment by lordwelch** [comment]
You have to download the rar program from https://www.rarlab.com/download.htm and add the path to the rar executable in the settings.

**Comment by Sparks01** [comment]
I have it pointed at "/usr/local/Caskroom/rar/6.0.2/rar/rar" and still nothing. I used homebrew to install rar on my mac.

**Comment by Sparks01** [comment]
Sorted. New Rar instal fixed it. Thx.
