### ISSUE TITLE
[Feature request] Bookmarking chapters in ComicRack format

### ISSUE THREAD

**Issue by varappdev** [comictagger/comictagger#212]
The ComicRack format is capable of adding chapters like
`<Page Image="0" Bookmark="Cover"/>`
And it will show up on any e-readers as chapters in the table of contents.
Can we please have the possibility of bookmarking without having to manually edit the XML file.

**Comment by lordwelch** [comment]
I didn't even know that Bookmarks were a part of the ComicRack spec but I just double checked on a copy from archive.org and turns out it does.

I don't know when I'll have time to implement this but I plan to.

**Comment by beville** [comment]
Just to throw in my two cents:  I feel like bookmarks are more ephemeral and personal, and should live outside of the embedded metadata within a comic file.  While bookmarks _are_ metadata, it's personal metadata, and maybe bookmarks (and other things like current page, finished status etc) are best managed by reader applications outside of the comic file.  Sounds like good fodder for conversation over at the [anansi-project](https://github.com/anansi-project/comicinfo)

**Comment by lordwelch** [comment]
This is true and ComicRack follows this idea in some instances but not others. For example the personal rating vs the community rating.
I am also thinking that I will complete the few elements that ComicTagger does not currently support from ComicRack, and then support a separate format for any changes, such as in this case I think the current usage is for labeling _chapters_ and should probably be renamed as such, whether in a similar format as ComicInfo.xml or another type.
I have made a PR at anansi-project/comicinfo#13 to get it added to the v2.0 spec for completeness.

**Comment by lordwelch** [comment]
@VictorGamerLOL what programs have you used that implement the bookmark feature?
We are discussing it in anansi-project/comicinfo#13 and were wondering how programs implemented it.

**Comment by varappdev** [comment]
@lordwelch I did not use any program for this. I just read about it in the kindle comic converter wiki, which said that you must use ComicRack metadata to change the default metadata, and the example they used there had bookmarks of chapters.
