### ISSUE TITLE
unable to identify A+X

### ISSUE THREAD

**Issue by nomsirk** [comictagger/comictagger#215]
Books titled A+X (https://comicvine.gamespot.com/ax/4050-53535/), I've tried multiple iterations of the title (A+X, A-X, A X, AX, etc) in the _Series_ box, I can't get comictagger to pull the correct data out of comicvine.

**Comment by lordwelch** [comment]
So the reason this doesn't work is that the series is normalized to alphanumeric text only which means that the only text in your examples that produces a different result is `AX` vs `A X` for the rest.

I'm not sure of the best way to fix this, right now I'm leaning towards having a "literal search" option which will just return the first 50~100 results without any further processing

**Comment by lordwelch** [comment]
The new Literal Search option is available in [1.4.4-alpha.8] and allows tagging the `A+X` series.
If you run across other issues feel free to re-open.

[1.4.4-alpha.8]: https://github.com/comictagger/comictagger/releases/1.4.4-alpha.8

**Comment by nodupe** [comment]
Hi, This works perfectly as intended. I was also having issues with A+X. I have two suggestions for your evaluation: 
1. Keep literal search ( and add it to Auto-tag options )
2. Allow escaping the characters on normal standard search - for instance: A\+X or "A+X".
Great software by the way! Cheers.
