### ISSUE TITLE
[Question] Is it possible to get Genres from the API

### ISSUE THREAD

**Issue by WorldTeacher** [comictagger/comictagger#217]
I have used comictagger to tag most of my collection and then imported everything to Komga, but noticed that the Genre/Themes which are provided on comicvine didn't get added to the comicinfo.xml.

Would it be possible to add this function, or is this a limitation of the api?

**Comment by lordwelch** [comment]
ComicVine does not provide information on the genre. So there is currently nothing we can do about it.

**Comment by WorldTeacher** [comment]
Okay, thanks for letting me know.
Then I'm going to have to add them all manually... this will take a while
