### ISSUE TITLE
CBR file, "Sorry is not a comic archive"

### ISSUE THREAD

**Issue by darylf** [comictagger/comictagger#218]
Hi, I'm a new comictagger user.

I am trying to use comictagger from the command line, but I can't get it to read a CBR file. It only works for CBZ files. I have found suggestions on the mylar repository pointing to an old version of unrar installed, however I have confirmed that mine is 5.61 and installed in /usr/bin/unrar (using Ubuntu). I've run a test command (`unzip -q -t "sample.cbr" > /dev/null 2>&1 `) on the file to confirm it isn't corrupt.

I'm not sure where to find logs to help others here troubleshoot my issue, but any feedback is welcomed.

**Comment by lordwelch** [comment]
Did you install the CBR requirements?
`pip install comictagger[CBR]`

**Comment by darylf** [comment]
Ah, it looks like it didn't run successfully when I first ran it. Turns out I had to escape the brackets.
` pip install comictagger\[CBR\]`

Thanks!

**Comment by lordwelch** [comment]
Yes, ZSH and other shells require straight braces to be escaped, bash does not.
I've run into it several times myself.
