### ISSUE TITLE
[Feature Request] Tags Comicinfo Metadata Field

### ISSUE THREAD

**Issue by SandyRodgers-2017** [comictagger/comictagger#219]
Hi Lordwelch,
I was wondering could you add the ability to set a Tags metadata field for ComicRack comicinfo files. Right now this isn't available. This isn't a default metadata field for comicinfo. However, it is a part of the anansi projects draft of the comicinfo 2.1 standard, if that matters. Right now it is supported by nhentai, kavita, and komga, but I would love to see it expand. I was able to kind of get it working under the command line using some modifications that broke CBL format, but a more official way would be greatly appreciated,
Sincerely,
SR2017

**Comment by lordwelch** [comment]
My only issue is that I want to make sure that ComicTagger shows a difference between the metadata the ComicRack supports and what the newer Anansi project supports as many readers only support the original set of metadata that ComicRack included. My current plan for this is to make it so that there is a plugin-type capability for metadata and then a new metadata type can be defined.

**Comment by SandyRodgers-2017** [comment]
Thank you for responding. Good to know that you are working on a solution.

**Comment by zachstultz** [comment]
Out of curiosity, any update on this?

**Comment by lordwelch** [comment]
When this PR is merged adding this will be possible #195
Before I finish that PR I am re-working the settings in #363

**Comment by zachstultz** [comment]
Any chance of this getting implemented now that both are merged? Or even just support for the tags field by itself via command line. Totally cool if not, I know the hassle of maintaining a project and the constant requests for various features. Just wanted to get an idea if it was planned at all, so I can plan the integration on my personal project accordingly.

**Comment by lordwelch** [comment]
I have some decent code for turning metadata styles into plugins, (I have to actually fix a hardware issue with the machine it's on before I can get to it again) but right now I'm trying to separate ComicAPI out of ComicTagger into it's own library with https://github.com/OzzieIsaacs/ComicAPI once that is done then I plan on working on metadata plugins again

**Comment by lordwelch** [comment]
This is now supported via https://github.com/comictagger/comicinfoxml the comicinfoxml plugin is included in all binary downloads starting with [1.6.0-alpha.9: Groonk](https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.9)

**Comment by SandyRodgers-2017** [comment]
Nice
