### ISSUE TITLE
"Clear form before importing comic vine data" not working

### ISSUE THREAD

**Issue by Bazzu85** [comictagger/comictagger#224]
Hi using last version from github

![image](https://user-images.githubusercontent.com/7345587/158776321-163e7a41-3049-4e8a-800b-faeb88ec8b71.png)

Let's take this example

![image](https://user-images.githubusercontent.com/7345587/158776414-432e2ba3-2a84-4edd-bbcf-d4104fa19c66.png)

enabling this

![image](https://user-images.githubusercontent.com/7345587/158776474-407b3873-66a5-4c5a-9de7-26d145d2b797.png)

the "aaa" in alt. series is not removed after auto tagging... am I missing something?

Search online and Auto-identify works as expected

**Comment by lordwelch** [comment]
This setting only works when the `Search Online` or `Auto-Identify` buttons. In other words it only takes effect when importing metadata interactively

**Comment by Bazzu85** [comment]
> This setting only works when the `Search Online` or `Auto-Identify` buttons. In other words it only takes effect when importing metadata interactively

Can I ask you the Reason?

**Comment by lordwelch** [comment]
No idea, I only started contributing to ComicTagger fairly recently

**Comment by Bazzu85** [comment]
> No idea, I only started contributing to ComicTagger fairly recently

Ok, can so we talk about if this is a intended or if is a bug?

**Comment by lordwelch** [comment]
Sorry, GitHub was not working well and apparently did not post my reply.

I think this was originally intended so that custom data would not be lost when doing mass updates to comic libraries, but there's no reason why another option can't be added.

**Comment by Bazzu85** [comment]
> Sorry, GitHub was not working well and apparently did not post my reply.
> 
> I think this was originally intended so that custom data would not be lost when doing mass updates to comic libraries, but there's no reason why another option can't be added.

Don't worry @lordwelch 

So can I suggest to add an option here

![image](https://user-images.githubusercontent.com/7345587/160210411-b7971b13-1aaa-4050-921e-43cd21e125c1.png)

to clear the forms?

**Comment by MichaelFitzurka** [comment]
Fixed in [1.3.2-alpha.0](https://github.com/comictagger/comictagger/releases/tag/1.3.2-alpha.0)

**Comment by Bazzu85** [comment]
> Fixed in [1.3.2-alpha.0](https://github.com/comictagger/comictagger/releases/tag/1.3.2-alpha.0)

Thx, I'll try ASAP..
