### ISSUE TITLE
Not all alternate cover images are found on ComicVine pages

### ISSUE THREAD

**Issue by MichaelFitzurka** [comictagger/comictagger#227]
Take Firefly issue #1.
There are actually 13 cover images displayed, but the application only finds 6 of them.
I have a small code fix that finds these other images in the data-src element vs the src element and will upload a fix soon.

**Comment by MichaelFitzurka** [comment]
I meant to include comic vine link: https://comicvine.gamespot.com/firefly-1/4000-692009/

**Comment by lordwelch** [comment]
Merged! Thanks for the contribution!
