### ISSUE TITLE
Some special characters cause a crash upons saving comicrack metadata

### ISSUE THREAD

**Issue by thampp** [comictagger/comictagger#229]
I am working with Comictagger 1.3.0 on MacOS.
I experience crashes when saving comicrack metadata. In my case that is to cbz file and with comicrack metadata but I have not tested if the same happens with other cbr and/or cbl.

With lot's of trial and error I have found that this is caused be the presence of certain special characters in a text field. So far I have identified two:
- … horizontal ellipsis (0x2026)
- ’ right single quotation mark (0x2019)

I suspect that this may apply to all Unicode chars above a certain number.
Since characters like this are returned by Comicvine APIs relatively frequently this is quite annoying.
It's most frequent for the "Notes" field but I can trigger the same crash by pasting such a char into other fields as well.

**Comment by thampp** [comment]
Quick update: The problem seems to indeed be with any Unicode char above 127.
At least any accented or umlauted character I tried causes this crash (e.g. àèïöę) also some Japanese I tried (e.g. (北斗の拳) cause the same
Makes it practically impossible to use this version of Comictagger with French or German or Japanese input....
Looks like a regression: I am pretty sure this used to work in the 1.2.x version stream.

**Comment by lordwelch** [comment]
I figured it out in #223 I just pushed a new alpha release that has the fix applied

**Comment by thampp** [comment]
Somehow I missed #223 as a duplicate. I guess it was closed already by the time I opened mine.
In an case: Thanks the response and for the quick turnaround  on this!!

**Comment by thampp** [comment]
And BTW: I can confirm that my issue is resolved with the latest alpha build
