### ISSUE TITLE
Comictagger 1.3.0 Crash

### ISSUE THREAD

**Issue by irwando** [comictagger/comictagger#236]
Mac Mini M1 running macOS 12.3 Monterey
Installed ComicTagger from brew via "brew install --cask comictagger"

Most Books work fine but I have a few issues that hard crash comictagger every time I try to save tags after auto-identify.  Identify works fine but save crashes.  Other books in the same series work fine.

Whats the best way to get the issue debugged?

**Comment by lordwelch** [comment]
This is resolved in the current alpha release which has a .app pre-built. You can see #223 for the explanation but I don't know who created the package for brew

**Comment by lordwelch** [comment]
fixed in homebrew/homebrew-cask#121175
