### ISSUE TITLE
Add ability to save multiple formats

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#24]
_From [JCZork...@gmail.com](https://code.google.com/u/115082408460417545268/) on June 06, 2013 16:09:43_

What steps will reproduce the problem? 1. run 'commictagger -s' without '-t' 
2. instructed to select a tag format

OR
1. run 'commictagger -s' with multiple '-t' options What is the expected output? What do you see instead? Expected all formats to save if none specified (or a '-t all' option).

If multiple formats are specified only the last is used. What version of the product are you using? On what operating system? 1.1.9-beta

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=24_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on July 08, 2013 17:49:58_

I will think about this one.  Probably the way to go would be a coma separated list of formats.  i.e.:

"-t cr,cbl"

**Status:** Accepted  
**Labels:** -Type-Defect Type-Enhancement

**Comment by jpenney** [comment]
Just came by to see if this was addressed yet. Still hoping for this feature
