### ISSUE TITLE
Anansi Project: Schema v1.0: ComicPageInfo.Key

### ISSUE THREAD

**Issue by MichaelFitzurka** [comictagger/comictagger#257]
We are almost fully v1.0 compliant with the Anansi v1.0 schema.
The only outlier is the ComicPageInfo.Key value.

``` xml
<xs:attribute default="" name="Key" type="xs:string" />
```

On the bright side, if the XML has an existing Key field, we won't overwrite it on a save.
But we also have no way to edit the value.

We could add the field on the Pages tab under the Bookmark field.
But no one seems to know what the value is actually for and I couldn't trigger a value in playing around with the original ComicRack application.

Thoughts?

**Comment by lordwelch** [comment]
I couldn't find any application that uses it. My guess is that it was a free property that ComicRack scripts could set for page metadata. I don't see a use in adding it as it add one more box that nobody knows what to put into it.

**Comment by MichaelFitzurka** [comment]
Thanks for the info - agreed, let's not add as an editable field - closing.
