### ISSUE TITLE
Anansi Project: Schema v2.0: CommunityRating

### ISSUE THREAD

**Issue by MichaelFitzurka** [comictagger/comictagger#258]
Likewise, we are almost fully compliant with the Anansi v2.0 schema.
The only outlier here is the CommunityRating value.

``` xml
<xs:element minOccurs="0" maxOccurs="1" name="CommunityRating" type="Rating" />

    <xs:simpleType name="Rating">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="5"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
```

Or, 0 to 5 with 2 decimal points.
The decimal points gets changed to only 1 in the v2.1 schema.

This would be easy enought to add to the Notes tab, after the User Rating.
The value is available on some ComicVine pages:
ex. https://comicvine.gamespot.com/wonder-woman-89-home/4000-55260/

``` html
<span class="[average-score]()">4.1 stars</span>
```

**Comment by lordwelch** [comment]
As to adding support for editing it should absolutely be added, however when it comes to ComicVine we should stick to the [API](https://comicvine.gamespot.com/api/documentation) and I do not see any options to retrieve any sort of community rating/review
