### ISSUE TITLE
Tagging fails to identify comics on Read-Only files

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#26]
_From [boo...@gmail.com](https://code.google.com/u/102131201638249756871/) on June 21, 2013 21:11:26_

Seems ComicTagger knows the files are read only as the save option is greyed out, but rather than tell me - all matching just fails. Error message would be awesome.

Thanks!!

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=26_

**Comment by davide-romanini** [comment]
_From [jwfl2...@gmail.com](https://code.google.com/u/117673507003588571146/) on July 04, 2013 13:07:18_

I'm getting all my files listed as read only on a mounted network share.  Not sure what the deal is.  I've tried running the app as an admin as well.  Win 7 x64

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on July 08, 2013 18:51:37_

boojew:

Just want to be clear:  Are you talking about the auto-tag process?  I see that when I try to auto-tag a single file it says:

"Successfully tagged archives: 0"

I think you're suggesting something like this:

"Read-only files:1
Successfully tagged archives: 0"

Is that correct?

**Labels:** -Type-Defect Type-Enhancement

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on July 08, 2013 18:53:59_

jwfl2005:  I will look into this, but need more info:  Are the files listed *incorrectly* as read-only?  If so, what kind of share is it, and what kind of host?  I will try to recreate this, but def need more info.

**Comment by davide-romanini** [comment]
_From [boo...@gmail.com](https://code.google.com/u/102131201638249756871/) on July 09, 2013 04:35:06_

I'm running Windows 8  and the CBRs are on a local drive. When they are in read only auto-tagging continually just tells me it cant find any data and the "save tags" button is grayed out.

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on July 23, 2013 10:18:04_

boojew, looks like the thread was slightly hijacked, and you I don't know what you meant by the previous answer in `#4`.  What are you thoughts on my initial response in `#2` above?

**Comment by lordwelch** [comment]
closing due to age.
