### ISSUE TITLE
Comictagger crashing

### ISSUE THREAD

**Issue by Bazzu85** [comictagger/comictagger#262]
Hi, 

I have to report a crash case:
Renaming a file with some special characters make the app crash.
Here's a screen of the metadata from CV
![image](https://user-images.githubusercontent.com/7345587/162611604-dd8ae0d1-79a4-4513-8959-b6013f0ac3fe.png)
When renaming using this pattern
`%series% (%volume%) #%issue% [%title%] [%storyarc%] [%month_name%, %year%] [%language_code%]`
the " in the title makes the app crash.
It's easily reproducible and fixable imho..

thx

**Comment by JohnKacz** [comment]
Looks like it's probably the difference between “ and ". I'm not familiar enough with the terminology but it has to do with character encoding or something. I would be that if you replace the “s with double quotes from the key right next to your enter/return key then it will work just fine.

source: I had a similar issue with some auto-identified comments.

**Comment by lordwelch** [comment]
This is because Bazzu85 is on windows, windows does not allow double quotes in filenames. I have some code that should fix it and plan to merge it in the next week or two

**Comment by Bazzu85** [comment]
> This is because Bazzu85 is on windows, windows does not allow double quotes in filenames. I have some code that should fix it and plan to merge it in the next week or two

Exactly...windows doesn't allow some character including the ones from the screen..
I think that a regex replace off this special char can be enough..
For the moment I manually remove it from the metadata..
When you make the improvement we have the test case..

**Comment by Bazzu85** [comment]
Additionally comicrack Library Organizer has this:

![image](https://user-images.githubusercontent.com/7345587/162640611-63b34f7c-659b-4a9c-bcee-0683fb7bc6ff.png)

to prevent problems

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.1](https://github.com/comictagger/comictagger/releases/tag/1.4.1)
