### ISSUE TITLE
Trying to save comicrack tags

### ISSUE THREAD

**Issue by arthuras313** [comictagger/comictagger#272]
I tried to add comicrack tags to my own cbz but all the time popped up an error as the print.

Can you help me fixing this or explain to me what I've done wrong?

Thanks

![image](https://user-images.githubusercontent.com/84281746/164024409-fc7f4bab-97d7-4e48-95cd-9a061537fe47.png)

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.2](https://github.com/comictagger/comictagger/releases/tag/1.4.2)

**Comment by arthuras313** [comment]
Confirmed as fixed.
