### ISSUE TITLE
Empty tags in XML when removing a pre-existing value.

### ISSUE THREAD

**Issue by MichaelFitzurka** [comictagger/comictagger#278]
If the ComicInfo XML has a value, and then the value is removed, it leaves an empty tag.

Pre-Existing tag:
```xml
<CommunityRating>0.1</CommunityRating>
```
After removing the value in the application, an empty tag is created:
```xml
<CommunityRating />
```
which should just be removed altogether.

**Comment by lordwelch** [comment]
Is there a particular reason why you need the tag to be absent?

**Comment by MichaelFitzurka** [comment]
Semantically there are similar, but in XML, the existence of a tag versus an omitted tag can have slightly different meanings - any empty tag would indicate that a value exists but of an unknown value - versus an omitted tag which would indicate that the value is known to not exist - subtle difference.

Also, it makes for smaller XML which is more efficient.

**Comment by lordwelch** [comment]
1. <details><summary>Semantically the difference between a tag existing versus being empty, is that if it is empty it has been explicitly set to be empty. It has nothing to do with whether or not the value is unknown.</summary>

   - As an example you can see that in the schema from ComicRack hosted at the [Anansi Project](https://github.com/anansi-project/comicinfo/blob/main/schema/v2.0/ComicInfo.xsd) that elements are allowed to be omitted and several have a default value of "Unknown".
   - In regards to applications, every application that I can find [Manga-Tagger](https://github.com/Inpacchi/Manga-Tagger/blob/d459df30dab06afc28b9c32d521aaa97dea388e9/MangaTaggerLib/MangaTaggerLib.py#L515), [Manga-Manager](https://github.com/ThePromidius/Manga-Manager/blob/e7e957cc7e537a353d87f585b8993b1c9a3775e3/MangaManager/MetadataManagerLib/ComicInfo.py#L2061), [ComicBox](https://github.com/ajslater/comicbox/blob/9cd8f608b92360908c657bb9046cf43ab4855291/comicbox/metadata/comicinfoxml.py#L119) used by [Codex](https://github.com/ajslater/codex), [komga](https://github.com/gotson/komga/blob/7c049adf8b30be34cf389a2787403dfeddd6ad27/komga/src/main/kotlin/org/gotson/komga/infrastructure/metadata/comicrack/ComicInfoProvider.kt#L131), [kavita](https://github.com/Kareadita/Kavita/blob/0eb3d74ff9648484f07d7057e8f71070ad1a0695/API/Services/Tasks/Scanner/ParseScannedFiles.cs#L106) and [kthoom](https://github.com/codedread/kthoom/blob/2fd52d90f78bf5722d9bade1bb775990f8540feb/code/metadata/book-metadata.js#L152) account for not only whether or not it exists but also if it is empty, the only exception being ComicRack.
   - ComicRack only fails if the element does not have the empty string set as the default in the schema and only if the full closing and ending tag is present. `<Year></Year>` will fail to load however `<Year/>` works perfectly fine.

</details>

2. It is more efficient however I don't think anybody is trying to get 100% efficiency. On a collection of 14,000 tagged comics the total size of all of the metadata is 58MB uncompressed and 20MB compressed, that same collection is 867GB uncompressed and 847GB compressed. The metadata takes up 0.006533% of the total storage space. My issue of Batman 001 is 20MB the ComicInfo.xml is 6.5KB it is 0.03162% of the total size there is almost no efficiency to be gained as the total storage difference would be less than 1KB per comic

3. I cannot find any instance where this has a negative effect so I will merge it
