### ISSUE TITLE
[new renamer] language tag gives "string items out of range"

### ISSUE THREAD

**Issue by Bazzu85** [comictagger/comictagger#281]
Hi, I'm on the last version

![image](https://user-images.githubusercontent.com/7345587/165765604-561ae32b-ba6f-4f97-a9a8-3330c0b627a2.png)

here's some tests.

1. Using the {language} tag like this:
`{series} ({volume}) #{issue} [{title}] [{story_arc}] [{month_name}, {year}] [{language}]`
gives this error:
![image](https://user-images.githubusercontent.com/7345587/165765780-eb5eec7f-a8f3-4d94-9ca1-c4664967d889.png)

2. Removing the `{language}` tag like this
`{series} ({volume}) #{issue} [{title}] [{story_arc}] [{month_name}, {year}] []`
doesn't give error.
![image](https://user-images.githubusercontent.com/7345587/165766381-8162e353-c8fe-43d5-bcf7-691941b9f367.png)

3. Removing only the square brackets like this `{series} ({volume}) #{issue} [{title}] [{story_arc}] [{month_name}, {year}] {language}` gives this strange result:
![image](https://user-images.githubusercontent.com/7345587/165766634-f6c3abef-d087-44ae-88ff-4985ebb2ed20.png)

The issue doesn't have a language but with previous renamer the field was bypassed if missing

**Comment by lordwelch** [comment]
That shouldn't have happened I'll take a look tonight

**Comment by lordwelch** [comment]
Quickest fix is to turn off the experimental text cleanup and you will get left with your second example when there is no language set.

I have fixes in progress for the next release

**Comment by Bazzu85** [comment]
Ok, I have to report BTW that the 2 renamer are not fully compatible each other. When switching the first time I had to change some token names. The same when switching back to original renamer

**Comment by lordwelch** [comment]
yes, it was more of a convenience function to make the basic templates easier to transition

**Comment by lordwelch** [comment]
If you are able to test pull request #285 it has my fixes, so hopefully no more errors will happen.
On the pull request you can open the checks and download the application.

**Comment by Bazzu85** [comment]
> If you are able to test pull request #285 it has my fixes, so hopefully no more errors will happen. On the pull request you can open the checks and download the application.

Ty.
Can I ask you how to test it without the standard packed .exe?

**Comment by lordwelch** [comment]
If you follow the steps in the [CONTRIBUTING.md](https://github.com/comictagger/comictagger/blob/develop/CONTRIBUTING.md#contributing-code) that would let you run comictagger from source.

However in this case a packed exe is built it is just a little annoying to get to:

Click on the `Show all checks` and then click `Details` (it doesn't matter which one)
<img width="912" alt="Screen Shot 2022-04-30 at 12 17 09 AM" src="https://user-images.githubusercontent.com/7547075/166096122-389ce9c9-a461-414f-80d4-811d5b723b82.png">

Then click on `Summary`
<img width="912" alt="Screen Shot 2022-04-30 at 12 19 31 AM" src="https://user-images.githubusercontent.com/7547075/166096124-154948f3-bdc4-4a93-b146-d3cf85704e1b.png">

The download is labeled ComicTagger-Windows at the bottom of the page
<img width="912" alt="Screen Shot 2022-04-30 at 12 20 01 AM" src="https://user-images.githubusercontent.com/7547075/166096126-12e17885-c931-44f3-8eaa-4b62d5bfe817.png">

**Comment by Bazzu85** [comment]
> If you follow the steps in the [CONTRIBUTING.md](https://github.com/comictagger/comictagger/blob/develop/CONTRIBUTING.md#contributing-code) that would let you run comictagger from source.
> 
> However in this case a packed exe is built it is just a little annoying to get to:
> 
> Click on the `Show all checks` and then click `Details` (it doesn't matter which one) <img alt="Screen Shot 2022-04-30 at 12 17 09 AM" width="912" src="https://user-images.githubusercontent.com/7547075/166096122-389ce9c9-a461-414f-80d4-811d5b723b82.png">
> 
> Then click on `Summary` <img alt="Screen Shot 2022-04-30 at 12 19 31 AM" width="912" src="https://user-images.githubusercontent.com/7547075/166096124-154948f3-bdc4-4a93-b146-d3cf85704e1b.png">
> 
> The download is labeled ComicTagger-Windows at the bottom of the page <img alt="Screen Shot 2022-04-30 at 12 20 01 AM" width="912" src="https://user-images.githubusercontent.com/7547075/166096126-12e17885-c931-44f3-8eaa-4b62d5bfe817.png">

Ty. I didn't know about all this steps.
I tested and the problem seems to be solved:
![image](https://user-images.githubusercontent.com/7345587/166108262-1f9072ce-dffb-4273-aa3e-83db30a29b4d.png)

![image](https://user-images.githubusercontent.com/7345587/166108268-dfd8094f-ffc2-458e-ab03-98d325e5f104.png)

![image](https://user-images.githubusercontent.com/7345587/166108275-2ee2a403-b87b-4c10-846d-49e5a2a3f9f6.png)

ty
