### ISSUE TITLE
Crash on Auto Identify loading in 1.4.3 and 1.4.4a

### ISSUE THREAD

**Issue by rvcjew** [comictagger/comictagger#291]
Hi I just started using this app and immediately this my issue on the windows builds when trying to Auto Identify.

Win 10 x64 21H2

![image](https://user-images.githubusercontent.com/39548830/168404340-362bd138-54c7-472a-ae81-923387b51f2e.png)

And my log is as such:
[ComicTagger.log](https://github.com/comictagger/comictagger/files/8691896/ComicTagger.log)

**Comment by lordwelch** [comment]
Hmm, it appears that one of the issues that it matched with doesn't have a number part for the issue, I'll see what I can do to fix it tonight

**Comment by rvcjew** [comment]
> Hmm, it appears that one of the issues that it matched with doesn't have a number part for the issue, I'll see what I can do to fix it tonight

Yeah it seems other series work okay and I found out I actually really only need the files renamed to something not crazy and in order to use the app I prefer with my SMB shares. The app doesn't support tags, ComicTagger does not rename the files to fit the tag layout right? I might swap to komga though and then would need them I guess. Thanks for the help.

**Comment by lordwelch** [comment]
ComicTagger has full support for renaming comics based on metadata, including moving into folders based on metadata
