### ISSUE TITLE
Installing 1.4.4alpha4

### ISSUE THREAD

**Issue by sunjam** [comictagger/comictagger#295]
Having difficulty in understanding how to install alpha4 after `git checkout -b`
```
INFO: pip is looking at multiple versions of comictagger[gui] to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'comictagger' requires a different Python: 3.8.10 not in '>=3.9'
```
Unsuccessfully `$ pip3 install .[GUI]` switching between 3.8, 3.9. 3.10 using `sudo update-alternatives --config python`

New to python so I realize it is a noob testing question.  Thanks!

**Comment by lordwelch** [comment]
you should be able to run `pip3.9 install --user --pre 'comictagger[GUI]'`
