### ISSUE TITLE
ComicInfo.xml indentation problem

### ISSUE THREAD

**Issue by Pro-Tweaker** [comictagger/comictagger#300]
Using version : 1.4.3 
Tested only ComicRack  xml format

I have tested with various files and it always fails to indent correctly.

Closing tag </Pages> and </ComicInfo> are not indented correctly.

Is:
![image](https://user-images.githubusercontent.com/67857759/169644841-29e7b698-f84e-46be-9e8c-629dc72985be.png)

Should be:
![image](https://user-images.githubusercontent.com/67857759/169644891-2d391ff0-f663-4f87-a864-b74079ed486b.png)

**Comment by Pro-Tweaker** [comment]
I have build from sources v1.4.4a7 and it does properly indent.

**Comment by lordwelch** [comment]
@Pro-Tweaker FYI you didn't have to build anything from source there are alpha releases available https://github.com/comictagger/comictagger/releases
