### ISSUE TITLE
CLI Return codes

### ISSUE THREAD

**Issue by killo3967** [comictagger/comictagger#307]
Is there an intention to implement return codes for the CLI ?

I use it is a powershell script and it is difficult to know if what I have commanded it to execute has done well by analyzing the log.

**Comment by lordwelch** [comment]
I don't know of any explicit conditions that it should return a non-zero exit code besides application failures.
For example if your tagging 10 comics and 9 are successful should it fail? Well what about 100 and only 1 fails? I can't think of a way to say anything other than 100% success or not 100% success, and with most of the comics that I've tagged it was almost never 100% success. Also there should have been a summary printed at the end of the operation unless you passed `--nosummary`

**Comment by killo3967** [comment]
Well, first of all, thank you for developing such useful software and making it available to us. 
That said, what you say is very true. It would be interesting to know if all the comics that I pass to them have been correctly scraped or not.
In another case, it would be good to know if the data could be saved to the xml file or if the comic could be renamed.
Currently I have done the same by analyzing the log file.

**Comment by lordwelch** [comment]
First of all I'm just the current maintainer there were a minimum of two other primary people that built this software before I found it, with plenty of others that contributed.

I'll see what I can come up with and post some examples here.

**Comment by lordwelch** [comment]
Right now my current thought are:
* Implement a basic all or nothing return code in the case that everything went perfectly
  * This probably won't be common for searching but for renaming it should be useful as it is rare to have partial failures when renaming
* Allow renaming to happen after metadata searching for comics that were tagged without issues
  * This will allow a separate directory to be specified for completed comics so that for comics without issues you won't have to manually move them around
* Possibly add an option to allow json output so that results can be processed by other scripts created by the user

**Comment by killo3967** [comment]
The json idea could be perfect.

Thanks

**Comment by lordwelch** [comment]
I'm going to keep this open until I actually implement this

**Comment by killo3967** [comment]
Meanwhile you implement this, Could you tell me the list of the "return string's".
I made a little code in powershell, but i know i haven't all the solutions.

function repuesta_comictagger {
    # Analizo el fichero de log dejado por comictagger, para esto no necesito parametros
    # Pero si devuelvo $true si lo ha encontrado o $false ni no lo ha encontrado 
    $respuesta = get-content -literalpath "$log_dir\comictagger.log"

    if (( $respuesta | select-string 'Save complete').count -gt 0) {
        # Si encuentra una linea con Save complete, es que ha encontrado el comic o se ha realizado la escritura del XML correctamente
        $return_code = 0
    } else { 
        if (( $respuesta | select-string 'Error').count -gt 0) {
            # Si encuentra una linea con Error es que ha fallado la busqueda del comic
            $return_code = 1
        } else {
            if (( $respuesta | select-string 'Archives with multiple high-confidence matches').count -gt 0) {
                # Si encuentra una linea con Archives with multiple high-confidence matches es que ha encontrado varias posibilidades
                $return_code = 2
            } else {
                # Hay que estudiar otro tipo de errores
                $return_code = 9999
            }
        }
    }
return $return_code
}

**Comment by lordwelch** [comment]
```
Successful matches:
------------------
No matches:
------------------
File Write Failures:
------------------
Network Data Fetch Failures:
------------------
Archives with multiple high-confidence matches:
------------------
Archives with low-confidence matches:
------------------
```
