### ISSUE TITLE
Not search a second series with the same name but diferent year

### ISSUE THREAD

**Issue by killo3967** [comictagger/comictagger#317]
Hi.
As you can see I have tried with the 'volume' and 'year' tags, neither of them giving results.
The correct comicvine link is:
https://comicvine.gamespot.com/conan-el-barbaro/4050-100167/

Can you tell me what I am doing wrong?

PS C:\scripts> & "C:\Program Files (x86)\ComicTagger\comictagger.exe" -n -v -s -o -t cr -m "series=Conan el Barbaro, issue = 20, **year**=1983" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz" 2>&1        
Going to search for:
        Series: Conan el Barbaro
        Issue:  20
        Year:   1983
Searching for Conan el Barbaro #20 ...
Searching in 2 series
Found 0 series that have an issue #20 from 1983
:-(no matches!

No matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz
2022-06-22T21:24:11 | comictaggerlib.cli | ERROR | Online search: No match found. Save aborted

PS C:\scripts> & "C:\Program Files (x86)\ComicTagger\comictagger.exe" -n -v -s -o -t cr -m "series=Conan el Barbaro, issue = 20, **volume**=1983" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz" 2>&1
Going to search for:
        Series: Conan el Barbaro
        Issue:  20
Searching for Conan el Barbaro #20 ...
Searching in 2 series
Found 1 series that have an issue #20
Examining covers for  ID: 98007 Conan el Bárbaro (1980) ...[ 36 ] --> 36
Compared to covers in 1 issue(s):[36]
Very weak scores for the cover. Analyzing alternate pages and covers...
Examining alternate covers for ID: 98007 Conan el Bárbaro (1980) ...[0 alt. covers][ 362435 ]--->24

No matching pages in the issue.
--------------------------------------------------------------------------
-----> Conan el Bárbaro (1980) #20 Los Espejos Asesinos (None/None) -- score: 36
--------------------------------------------------------------------------

Archives with low-confidence matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz -- Single low-confidence match:
    1. Conan el Bárbaro (1980) #20 [Editorial Novaro] (None/None) - Los Espejos Asesinos
2022-06-22T21:24:29 | comictaggerlib.cli | ERROR | Online search: Low confidence match. Save aborted

**Comment by lordwelch** [comment]
So the first issue is that [ComicVine] does not have a cover date for issue 20 and first command is telling you exactly why it fails.
The second issue appears to be that the cover you have is substantially different than the cover that is on ComicVine so ComicTagger cannot say with a high confidence that the match is correct.

You should either open up the GUI to find the issue and save the metadata or use the `-i` option on the command line and ComicTagger will prompt you for the correct result to use.

[ComicVine]: https://comicvine.gamespot.com/conan-el-barbaro-20-la-cosa-de-la-cripta-ha-vengan/4000-591692/

**Comment by killo3967** [comment]
Thanks for your quick response.

As you said i alds check the covers, and of course mine don't correspond with the series of 1980, because is another series.

My question i why with the second try, when i use the tag volume=1983 as metadata comictaggert no take acount it.
Going to search for:
Series: Conan el Barbaro
Issue: 20

I also check with "-i" option  and this is what i have
PS C:\scripts> & "C:\Program Files (x86)\ComicTagger\comictagger.exe" -n -i -v -s -o -t cr -m "series=Conan el Barbaro, issue = 20, year=1983" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz" 2>&1
Going to search for:
        Series: Conan el Barbaro
        Issue:  20
        Year:   1983
Searching for Conan el Barbaro #20 ...
Searching in 2 series
Found 0 series that have an issue #20 from 1983
:-(no matches!

No matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz
2022-06-22T23:00:35 | comictaggerlib.cli | ERROR | Online search: No match found. Save aborted

and the second option with tag volume instead of year

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -n -i -v -s -o -t cr -m "series=Conan el Barbaro, issue = 20, volume=1983" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz" 2>&1
Going to search for:
        Series: Conan el Barbaro
        Issue:  20
Searching for Conan el Barbaro #20 ...
Searching in 2 series
Found 1 series that have an issue #20
Examining covers for  ID: 98007 Conan el Bárbaro (1980) ...[ 36 ] --> 36
Compared to covers in 1 issue(s):[36]
Very weak scores for the cover. Analyzing alternate pages and covers...
Examining alternate covers for ID: 98007 Conan el Bárbaro (1980) ...[0 alt. covers][ 362435 ]--->24

No matching pages in the issue.
--------------------------------------------------------------------------
-----> Conan el Bárbaro (1980) #20 Los Espejos Asesinos (None/None) -- score: 36
--------------------------------------------------------------------------
2022-06-22T23:05:18 | comictaggerlib.cli | ERROR | Online search: Low confidence match. Save aborted

Archives with low-confidence matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz -- Single low-confidence match:
    1. Conan el Bárbaro (1980) #20 [Editorial Novaro] (None/None) - Los Espejos Asesinos
Choose a match #, or 's' to skip:

But this is not the series of 1983 tthat i said with "volume=1983"

I search (manualy) in comicvine for series=conan el barbaro, volume=1983 and issus=20
https://comicvine.gamespot.com/conan-el-barbaro-20-la-cosa-de-la-cripta-ha-vengan/4000-591692/

And here you have my cover -> https://postimg.cc/pypkfbxR

**Comment by lordwelch** [comment]
In your second command 1980 refers to the start date of the series and has no relation to the cover date of issue 20 which can be seen if you look at this link
https://comicvine.gamespot.com/conan-el-barbaro/4050-100167/

Currently ComicTagger only uses the Series, issue and year to search by. Setting the volume simply sets the volume tag to whatever value you supply and saves it to the comic metadata

You also do not need to set the series manually you can use the `-f` flag and it will parse it from the filename

**Comment by killo3967** [comment]
Sorry but i don't understand.
Did you mean to use this ?

PS C:\scripts> & "C:\Program Files (x86)\ComicTagger\comictagger.exe" -n -f -i -v -s -o -t cr -m "issue=20" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz" 2>&1
Not enough info for a search!

No matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el barbaro #020.cbz
2022-06-23T08:06:58 | comictaggerlib.cli | ERROR | Online search: No match found. Save aborted

Which options, do you think i must use to get a correct response ?

**Comment by lordwelch** [comment]
The only way that happens is if you already have metadata saved for that comic and that metadata does not have a series set.

Print tags showing that none are present
```console
PS H:\> .\comictagger.exe -p '.\Conan el barbaro #20.cbz'
ZIP archive    ( 24 pages)  tags:[ none ]
```

Show successful search with filename parsing
```console
PS H:\> .\comictagger.exe -n -f -i -v -s -o -t cr '.\Conan el barbaro #20.cbz'
Going to search for:
        Series: Conan el barbaro
        Issue:  20
Searching for Conan el barbaro #20 ...
Searching in 2 series
Found 1 series that have an issue #20
Examining covers for  ID: 98007 Conan el Bárbaro (1980) ...[ 37 ] --> 37
Compared to covers in 1 issue(s):[37]
Very weak scores for the cover. Analyzing alternate pages and covers...
Examining alternate covers for ID: 98007 Conan el Bárbaro (1980) ...[0 alt. covers][ 374040 ]--->37

No matching pages in the issue.
--------------------------------------------------------------------------
-----> Conan el Bárbaro (1980) #20 Los Espejos Asesinos (None/None) -- score: 37
--------------------------------------------------------------------------
2022-06-23T00:01:19 | comictaggerlib.cli | ERROR | Online search: Low confidence match. Save aborted

Archives with low-confidence matches:
------------------
.\Conan el barbaro #20.cbz -- Single low-confidence match:
    1. Conan el Bárbaro (1980) #20 [Editorial Novaro] (None/None) - Los Espejos Asesinos
Choose a match #, or 's' to skip: 1
dry-run option was set, so nothing was written, but here is the final set of tags:
series:     Conan el Bárbaro
issue:      20
title:      Los Espejos Asesinos
publisher:  Editorial Novaro
web_link:   https://comicvine.gamespot.com/conan-el-barbaro-20-los-espejos-asesinos/4000-581756/
characters: Conan
notes:      Tagged with ComicTagger 1.4.3 using info from Comic Vine on 2022-06-23 00:01:23.  [Issue ID 581756]
```

Save tags explicitly without a series
```console
PS H:\> .\comictagger.exe -s -t cr -m "issue=20,series=" '.\Conan el barbaro #20.cbz'
Save complete.

Successful matches:
------------------
.\Conan el barbaro #20.cbz
```
Print tags to show that only the issue is set
```console
PS H:\> .\comictagger.exe -p '.\Conan el barbaro #20.cbz'
ZIP archive    ( 24 pages)  tags:[ CR ]

--------- ComicRack tags ---------
issue: 20
```

Show search fail because series is specifically set to empty
```console
PS H:\> .\comictagger.exe -n -f -i -v -s -o -t cr '.\Conan el barbaro #20.cbz'
Not enough info for a search!
2022-06-23T00:02:04 | comictaggerlib.cli | ERROR | Online search: No match found. Save aborted

No matches:
------------------
.\Conan el barbaro #20.cbz
```

**Comment by killo3967** [comment]
Firts of all I thank you very much for putting up with this heavy user. 

Now, Let's see if I've got it right.

I have done the following:

FIRST - I have deleted the comicinfo.xml file from inside the comic and confirmed it with '-p' and there is nothing.

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -p -t cr -m "series=Conan el Bárbaro,issue=1,year=1983" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1

C:\Users\server>

SECOND - I have used the '-f' parameter to write the tags in the comic. That is, the comicinfo.xml is created and confirm it with '-p'

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -s -f -t cr -m "series=Conan el Bárbaro,issue=1,year=1983" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1
Save complete.

Successful matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -p -t cr -m "series=Conan el Bárbaro,issue=1,year=1983" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1

--------- ComicRack tags ---------
series: Conan el Bárbaro
issue:  1
year:   1983

THIRD - I search online. Now series is not empty.
C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -s -o -t cr "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1
Going to search for:
        Series: Conan el Bárbaro
        Issue:  1
        Year:   1983
Searching for Conan el Bárbaro #1 ...
Found 100 of 969 results
Searching in 2 series
Found 0 series that have an issue #1 from 1983
:-(no matches!
2022-06-23T20:49:07 | comictaggerlib.cli | ERROR | Online search: No match found. Save aborted

No matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz

And fail again beacuse of the year.

AND NOW THE SAME STEPS WITHOUT THE YEAR TAG

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -s -f -t cr -m "series=Conan el Bárbaro,issue=1" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1
Save complete.

Successful matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -p -t cr "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1

--------- ComicRack tags ---------
series: Conan el Bárbaro
issue:  1


C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -s -o -t cr "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1
Going to search for:
        Series: Conan el Bárbaro
        Issue:  1
Searching for Conan el Bárbaro #1 ...
Searching in 2 series
Found 1 series that have an issue #1
Examining covers for  ID: 98007 Conan el Bárbaro (1980) ...[ 20 ] --> 20
Compared to covers in 1 issue(s):[20]
Very weak scores for the cover. Analyzing alternate pages and covers...
Examining alternate covers for ID: 98007 Conan el Bárbaro (1980) ...[0 alt. covers][ 203121 ]--->20

No matching pages in the issue.
--------------------------------------------------------------------------
-----> Conan el Bárbaro (1980) #1 None (12/1980) -- score: 20
--------------------------------------------------------------------------
2022-06-23T20:52:32 | comictaggerlib.cli | ERROR | Online search: Low confidence match. Save aborted

Archives with low-confidence matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz -- Single low-confidence match:
    1. Conan el Bárbaro (1980) #1 [Editorial Novaro] (12/1980) - None


The results is:
Searching for Conan el Bárbaro #1 ...
Searching in 2 series
Found 1 series that have an issue #1
Examining covers for  ID: 98007 Conan el Bárbaro (1980) ...[ 20 ] --> 20
Compared to covers in 1 issue(s):[20]
Very weak scores for the cover. Analyzing alternate pages and covers...
Examining alternate covers for ID: 98007 Conan el Bárbaro (1980) ...[0 alt. covers][ 203121 ]--->20

Why only check the covers in the series with the year 1980 and not in teh secon serie?

**Comment by beville** [comment]
@killo3967 Check your configuration.  I'll bet that missing series is from Panini Comics, which reprints a lot of Marvel (and maybe DC?) books.  I'm not running the latest version of ComicTagger, but it's probably under a publisher blacklist or filter.  You can remove the Panini entry (which is there by default), if it exists, and try again.

**Comment by lordwelch** [comment]
No problem it's a complicated program at times.

You only need the `-m` option for information not in the filename so for example your first command can be reduced to
```
C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -p -t cr -m "year=1983" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #1.cbz" 2>&1
```

The final thing is that there is a list of publishers that are filtered out which defaults to `Panini Comics`, `Abril`, `Planeta DeAgostini`, `Editorial Televisa`, `Dino Comics`
which makes it so that the only results ComicTagger looks at are the one from [1983] and the one from [1974].

The one from 1974 has some bad data the issue numbers that it has are barely useful even on the website.
The first issue number on comic vine is listed as `v. 2 no. 1` when it should be `1` and ComicTagger looks to see if there is an issue number `1` and cannot find it

[1983]: https://comicvine.gamespot.com/conan-el-barbaro/4050-100167/
[1974]: https://comicvine.gamespot.com/conan-el-barbaro/4050-94768/

**Comment by lordwelch** [comment]
Also ComicTagger only checks covers that match the issue number because otherwise if you try to tag a popular comic you would quickly download thousands of covers.
For example these are the first two series that you find when you search batman with a combined total of 2003 issues
https://comicvine.gamespot.com/batman/4050-126840/
https://comicvine.gamespot.com/batman/4050-796/

**Comment by killo3967** [comment]
Thank you very much, but this no resolve my problem. I started to code my own solution.

**Comment by killo3967** [comment]
For me its ok to close this issue

**Comment by killo3967** [comment]
Finally it's works. The problem was the filter. "Panini Comics" was in the filter.

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -p -t cr  "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1


C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -s -f -t cr -m "series=Conan el Bárbaro,issue=1" "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1
Save complete.

Successful matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -p -t cr  "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1

--------- ComicRack tags ---------
series: Conan el Bárbaro
issue:  1


C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -s -o -t cr "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1
Going to search for:
        Series: Conan el Bárbaro
        Issue:  1
Searching for Conan el Bárbaro #1 ...
Searching in 5 series
Found 4 series that have an issue #1
Examining covers for  ID: 98007 Conan el Bárbaro (1980) ...[ 20 ] --> 20
Examining covers for  ID: 100167 Conan el Bárbaro (1983) ...[ 4 ] --> 4
Examining covers for  ID: 104403 Conan el Bárbaro (1998) ...[ 32 ] --> 32
Examining covers for  ID: 131940 Conan el Bárbaro (2019) ...[ 18 ] --> 18
Compared to covers in 4 issue(s):[4, 18, 20, 32]
--------------------------------------------------------------------------
-----> Conan el Bárbaro (1983) #1 El Dios de la Cripta (None/None) -- score: 4
--------------------------------------------------------------------------
Save complete.

Successful matches:
------------------
J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz

C:\Users\server>"C:\Program Files (x86)\ComicTagger\comictagger.exe" -v -r -t cr  "J:\COMICS\FANTASIA\CONAN\Conan Vol.1 Forum\Conan el Bárbaro #001.cbz" 2>&1
renamed 'Conan el Bárbaro #001.cbz' -> 'Conan el Bárbaro #001 - El Dios de la Cripta.cbz'

But.,,, of course always be a 'but', if i use year tag the online option don't find anything. 
But for the moment, for me is solved.

**Comment by lordwelch** [comment]
@killo3967 Is there anything else that you needed with this issue?

**Comment by killo3967** [comment]
Thanks very much
