### ISSUE TITLE
Renamer is too limited

### ISSUE THREAD

**Issue by gramster** [comictagger/comictagger#322]
I can't see how to do conditionals in the templates; I would like to use:

```
{series}{' v' if volume else ''}{volume} #{issue} ({year})
```

Otherwise everything that has no volume metadata ends up with a 'v' in the name which is wrong.

**Comment by lordwelch** [comment]
The template is made by subclassing the Python string formatter https://docs.python.org/3/library/string.html#format-string-syntax
There are no plans to create a more complex template.
This case should now be fixed in the latest [commit].
You can download a pre-built binary of the latest [commit here]

[commit here]: https://github.com/comictagger/comictagger/actions/runs/2563604368
[commit]: https://github.com/comictagger/comictagger/commit/cb5b321539974d6b36a83567aa0f3832d40c6a2b

**Comment by gramster** [comment]
Ah, sneaky. But thank you! BTW there is a different issue if the year is empty: 
<img width="425" alt="image" src="https://user-images.githubusercontent.com/2762632/180634278-68171e37-8d06-4f8b-935c-65a3726f03dc.png">

**Comment by gramster** [comment]
Something to consider maybe is to use eval and cons up an f-string so that conditionals could be used in the template. It would get a bit ugly but would mean all these issues could be dealt with through preferences. OTOH that may be asking for too much Python knowledge from the average user.

**Comment by lordwelch** [comment]
Using the latest alpha does not crash with a year missing
<img width="880" alt="Screen Shot 2022-07-23 at 10 54 03 PM" src="https://user-images.githubusercontent.com/7547075/180634425-180b8bd7-74fb-4f56-b556-7db7a56adba6.png">
<img width="837" alt="Screen Shot 2022-07-23 at 10 54 23 PM" src="https://user-images.githubusercontent.com/7547075/180634422-0cbab19e-b62b-4cd6-816f-585641454d82.png">

**Comment by lordwelch** [comment]
There are logs located in ~/.ComicTagger that you can attach which should show the full error

**Comment by gramster** [comment]
Cool. Another thing that could have been useful is more columns to the list of comics on the right. E.g. if the list could be sorted by year or by volume, it would have been easy to isolate the ones that are missing this data so they could either have it added or be handled separately. It may not matter much now given you have addressed the template limitations.

**Comment by lordwelch** [comment]
Eventually batch editing might be added #23 and the whole interface will need to be updated to work differently, which would need more advanced sorting and management of comics.
Right now I'm trying to stick to bug squashing and making it more stable, at which point I will make another full release and after I plan on working on #195 to give ComicTagger a plugin system

**Comment by rhaussmann** [comment]
I recently switched to Komga and unfortunately it uses the folder level as a series indicator. So with my "flat" directory of just files, it sees all those files as one series. I tried using the python3 formatting but the rename input won't let me create a directory structure based on the tags. It would be something like `{publisher}/{series}({volume})/{series}({volume})#{issue}`. Is there a way to get that structure in there in the current or develop version?

**Comment by gramster** [comment]
That's probably just a couple of lines fix, but I would open it as a
separate issue.

**Comment by lordwelch** [comment]
The latest release 1.5.1 has support for alternate and default values, which should cover most if not all edge cases.
File renaming is considered complete at this point. The only further changes accepted will be Conversions which are functions that take a single object as an input and output a string eg `str.lower()`, in most circumstances it will need to be a function from the standard library, and alternate ways of obtaining metadata specifically in the spirit of the credit fields eg `{writer}` refers to either the first credit that is a writer or the primary writer
