### ISSUE TITLE
ComicVine API Rate Limiting

### ISSUE THREAD

**Issue by WorldTeacher** [comictagger/comictagger#326]
Now that ComicVine  has implemented a rate limiting on their API
![image](https://user-images.githubusercontent.com/41587052/177320260-1a4aea9a-df04-468b-a7bd-7e4901afdcd6.png)
are there any plans on implementing a rate limiter to stay within the limits?
![image](https://user-images.githubusercontent.com/41587052/177320211-8abaaf36-d796-4302-9ba9-833e42f58683.png)

The Limit is reset every 60 minutes and like they write in the Guidelines, I think it could be possible to create lists with all the to be requested series based on the filename. Based on that I'd guess it would be possible to get the data for the issues and other data?

I don't know enough about the ComicVine API and have not really worked with APIs before, so I this might be wrong...

**Comment by lordwelch** [comment]
There is already caching in place in most places, almost the only case that isn't cached is retrieving a specific issue which if cached would only help tag the exact same comic, which in most cases should not be useful
