### ISSUE TITLE
Separate format specifier for cases where volume is empty

### ISSUE THREAD

**Issue by gramster** [comictagger/comictagger#336]
This relates to https://github.com/comictagger/comictagger/issues/322. I understand the formatter can't handle arbitrary expressions unlike f-strings (which is what I was hoping). So I am left with the problem when doing bulk renames of adding unwanted 'v's in the names of files where the volume is empty. An alternate solution would be to allow two templates, one for cases where there is a volume number and another for when there isn't.

**Comment by gramster** [comment]
Actually things seem to be working right now, with this template:

```
{series} v{volume} #{issue} ({year})
```

I don't get a v when the volume is empty. Which is great on the one hand but doesn't make sense.

**Comment by lordwelch** [comment]
I did explain in my reply https://github.com/comictagger/comictagger/issues/322#issuecomment-1166459994

**Comment by gramster** [comment]
Thanks, I missed the fact that you had done some special casing. I added a couple more comments there about all of this; it can get a bit messy. Like if the year is missing you get a pretty unhelpful error popup.

**Comment by lordwelch** [comment]
I'm going to close this issue and re-open #322
