### ISSUE TITLE
Error saving tags

### ISSUE THREAD

**Issue by gmhowell** [comictagger/comictagger#337]
Encountering an error when I attempt to save tags. Using v1.4.4.a10 on Windows 11. 
> 2022-07-25 04:55:15,667 | comicapi.comicarchive | ERROR | Error saving CBI! for R:\Comics\Batman & the Outsiders (2019)\Batman & the Outsiders 1 (2019).cbr: Object of type set is not JSON serializable

**Comment by lordwelch** [comment]
Fixed in latest release [1.4.4-beta.1](https://github.com/comictagger/comictagger/releases/tag/1.4.4-beta.1)
