### ISSUE TITLE
Weird error when identifying some titles

### ISSUE THREAD

**Issue by eduo** [comictagger/comictagger#339]
I've found this error at least in two titles. They keep unindentified after several days because the parser seems to choke in the results.

The error I get if I search the title and double click on it to select an issue is this: 

```
Oops.An unexpected error occured:
File "comictaggerlib/issueselectionwindow.py",line
35,in__It_
TypeError: '<' not supported between instances of
'NoneType' and 'float'
```

When auto-tag is used, the issue is not found.

I imagine this can be replicated by naming any cbz with the same titles:
We Only Find Them When They're Dead 011 (2022) (digital) (Son of Ultron-Empire).cbz
Neverender 001 (2022) (Digital) (Mephisto-Empire).cbz

Also, if I change the numbering, auto-identify works OK, but same error crops up if I try to navigate the issues.

**Comment by lordwelch** [comment]
Have you tried on the latest beta? [1.4.4-beta.1](https://github.com/comictagger/comictagger/releases/tag/1.4.4-beta.1)

**Comment by eduo** [comment]
Welp, the beta came out right as I logged the ticket. It seems indeed to have fixed the issue :D
