### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by carterartist** [comictagger/comictagger#340]
I've tried downloading previous versions, it won't open.

**Comment by lordwelch** [comment]
Can you elaborate? What os are you running? What did you try?

**Comment by carterartist** [comment]
> Can you elaborate? What os are you running? What did you try?

I was running it on MacOS 11, with the past 5 or so versions of the comictagger. Last night I updated to 12.4 Monterey and I've tried the past 5 or so comictaggers...

all to no avail. I noticed in activity monitor it pops up in there, but only for about 30 seconds. Then it shuts down.

**Comment by lordwelch** [comment]
First MacOS is annoying make sure that you get around the popup it creates [Opening 3rd Party Apps on MacOS]
Second try [opening it from the command line]
Third if everything has failed [provide any logs] that were created

[Opening 3rd Party Apps on MacOS]: https://github.com/comictagger/comictagger/wiki/Opening-3rd-Party-Apps-on-MacOS
[opening it from the command line]: https://github.com/comictagger/comictagger/wiki/Open-ComicTagger-from-the-CLI-on-MacOS
[provide any logs]: https://github.com/comictagger/comictagger/wiki/Locating-Log-files

**Comment by carterartist** [comment]
`2022-06-19T10:38:50 | comictagger | INFO | ComicTagger Version: 1.4.3 running on: Darwin PyInstaller: Yes
2022-06-19T10:38:50 | comictagger | DEBUG | Installed Packages
2022-06-19T10:38:50 | comictagger | DEBUG | pycountry	22.3.5
2022-06-19T10:38:50 | comictagger | DEBUG | setuptools	58.1.0
2022-06-19T10:38:50 | comictagger | DEBUG | wheel	0.37.1
2022-06-19T17:20:22 | comictagger | CRITICAL | Uncaught exception: OSError: [Errno 28] No space left on device
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "comictaggerlib/taggerwindow.py", line 1895, in closeEvent
  File "comictaggerlib/settings.py", line 483, in save
OSError: [Errno 28] No space left on device
`

**Comment by lordwelch** [comment]
Well there is your error you do not have any space left on your device, I'm not sure how that makes sense considering you downloaded the program but that's what's happening.

**Comment by carterartist** [comment]
I have 598 GB available on the 1 terabyte drive

**Comment by lordwelch** [comment]
Can you attach logs using the latest beta? https://github.com/comictagger/comictagger/releases/tag/1.4.4-beta.1

**Comment by carterartist** [comment]
Tried it.

changed nothing to logs.

Still won't open.

I'm not having a problem with any other software either.

**Comment by lordwelch** [comment]
Can you delete the entire .ComicTagger folder and then run `df -h` in the terminal and post the output

Also if you use brew, you can try installing it through brew.
`brew install --cask comictagger`

**Comment by carterartist** [comment]
`Last login: Wed Jul 27 07:05:35 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Seans-iMac:~ seancarter$ df -h
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk2s5s1  957Gi   14Gi  542Gi     3%  501138 4292998498    0%   /
devfs           201Ki  201Ki    0Bi   100%     696          0  100%   /dev
/dev/disk2s4    957Gi  3.0Gi  542Gi     1%       3 5683657800    0%   /System/Volumes/VM
/dev/disk2s2    957Gi  312Mi  542Gi     1%    1512 5683657800    0%   /System/Volumes/Preboot
/dev/disk2s6    957Gi  2.6Mi  542Gi     1%      20 5683657800    0%   /System/Volumes/Update
/dev/disk2s1    957Gi  392Gi  542Gi    42% 2487991 5683657800    0%   /System/Volumes/Data
map auto_home     0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
/dev/disk4s2    5.5Ti  5.2Ti  250Gi    96% 1162678 4293804601    0%   /Volumes/Library
/dev/disk5s2    1.8Ti  934Gi  928Gi    51% 7653601    7606143   50%   /Volumes/Bellys
/dev/disk3s1    1.8Ti  1.6Ti  254Gi    87% 1255809 4293711470    0%   /Volumes/Seagate 2TB
Seans-iMac:~ seancarter$ 
`

**Comment by carterartist** [comment]
After deleting that folder, it is now working.
