### ISSUE TITLE
When I try to rename I get: "Your rename template is invalid!"

### ISSUE THREAD

**Issue by carterartist** [comictagger/comictagger#342]
Your rename template is invalid!

'primary'

Please consult the template help in the settings and the documentation on the format at https://docs.python.org/3/library/string.html#format-string-syntax

--

I had to delete the .comictagger folder to finally get the app to work again, and the settings were corrupted (it seems). So trying to get them to rename the files as I've done in the past.

I have tried: {series} - {issue} -- {series} -  {title} -- ({year}-{month})

I also tried with %series%

It keeps telling me to go to https://docs.python.org/3/library/string.html#format-string-syntax but I am not seeing the solution.

**Comment by lordwelch** [comment]
@carterartist
I updated the error message so for future issues it will be more helpful.
The latest release has this issue fixed [1.4.4-beta.2](https://github.com/comictagger/comictagger/releases/tag/1.4.4-beta.2)
