### ISSUE TITLE
Comic Vine API Key invalid 

### ISSUE THREAD

**Issue by ExtraTorrential** [comictagger/comictagger#345]
When I use the API key generated by Comic Vine, Comic Tagger says it's invalid. Could I putting an incorrect URL? 

I made a new account and same issue.

**Comment by lordwelch** [comment]
Did you change the url or the api key?

**Comment by ExtraTorrential** [comment]
I copied the API key straight from the site. And the url I copied from the API page at the top of the browser.

**Comment by ExtraTorrential** [comment]
I'm very new to using comic tagger and doing anything involving scripts LOL.

**Comment by lordwelch** [comment]
So you don't need to set the URL, it's possible that's bugged, unset it and try it

**Comment by lordwelch** [comment]
This should be fixed in the latest beta [1.4.4-beta.3](https://github.com/comictagger/comictagger/releases/tag/1.4.4-beta.3)
