### ISSUE TITLE
QUrl(QUrl): argument 1 has unexpected type 'SplitResult' Error when identifying comic

### ISSUE THREAD

**Issue by HeuristicPerson** [comictagger/comictagger#350]
I'm trying comictagger in Linux Mint 21 and I just found this error when trying to identify a comic:

    Traceback (most recent call last):
     File "/home/jdoe/.local/lib/python3.10/site-packages/comictaggerlib/imagehasher.py", line 52, in average_hash
       image = self.image.resize((self.width, self.height), Image.Resampling.LANCZOS).convert("L")
     File "/usr/lib/python3/dist-packages/PIL/Image.py", line 65, in __getattr__
       raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
    AttributeError: module 'PIL.Image' has no attribute 'Resampling'
    Examining covers for  ID: 47764 Batman The Cult (1989) ... [  0  ]  --> 0 
    Compared to covers in 3 issue(s): [0, 0, 0]
    More than one likely candidate.
    --------------------------------------------------------------------------
    -----> Batman: The Cult (1988) #1 Ordeal (8/1988) -- score: 0
    -----> Batman: The Cult (1989) #1 TPB (12/1991) -- score: 0
    -----> Batman The Cult (1989) #1 La Prueba (5/1989) -- score: 0
    --------------------------------------------------------------------------
    2022-08-10T13:52:01 | comictagger | CRITICAL | Uncaught exception: TypeError: arguments did not match any overloaded call:
     QUrl(): too many arguments
     QUrl(str, mode: QUrl.ParsingMode = QUrl.TolerantMode): argument 1 has unexpected type 'SplitResult'
     QUrl(QUrl): argument 1 has unexpected type 'SplitResult'
    Traceback (most recent call last):
     File "/home/jdoe/.local/lib/python3.10/site-packages/comictaggerlib/matchselectionwindow.py", line 145, in current_item_changed
       self.altCoverWidget.set_issue_id(self.current_match()["issue_id"])
     File "/home/jdoe/.local/lib/python3.10/site-packages/comictaggerlib/coverimagewidget.py", line 183, in set_issue_id
       comic_vine.async_fetch_issue_cover_urls(self.issue_id)
     File "/home/jdoe/.local/lib/python3.10/site-packages/comictaggerlib/comicvinetalker.py", line 743, in async_fetch_issue_cover_urls
       self.nam.get(QtNetwork.QNetworkRequest(QtCore.QUrl(issue_url)))
    TypeError: arguments did not match any overloaded call:
     QUrl(): too many arguments
     QUrl(str, mode: QUrl.ParsingMode = QUrl.TolerantMode): argument 1 has unexpected type 'SplitResult'
     QUrl(QUrl): argument 1 has unexpected type 'SplitResult'

Few hours ago I installed in another machine with Linux Mint 20 (using pip as well) and I didn't have any issue.

Regards

**Comment by lordwelch** [comment]
Well it should only fail currently when a comic has alternate covers that it tries to download, I'll have another release published later today with this fixed.

**Comment by lordwelch** [comment]
Also the other error with Pillow is because you have an older version installed you can fix it by running
`pip install --user pillow>=9.1.0` this will also be fixed in the release later today

**Comment by HeuristicPerson** [comment]
Thanks, the update of Pillow did the trick!

Regards and many thanks.

**Comment by lordwelch** [comment]
Version [1.4.5](https://github.com/comictagger/comictagger/releases/tag/1.4.5) is released closing
