### ISSUE TITLE
Broken identifying/searching in 1.4.4, working in 1.4.4a8

### ISSUE THREAD

**Issue by Symbiatch** [comictagger/comictagger#353]
Previously I used 1.4.4a8 and it worked fine for me, but upgrading to 1.4.4 (and 1.4.5 also) now identifying/searching works incorrectly.

Example: Comic has "Ms. Marvel" as the name, in 1.4.4a8 it finds a couple of Ms. Marvels, including the correct one with 38 issues. 1.4.4 finds only one series with one issue, which is a wrong one.

Another: Spider-Man/Deadpool, 1.4.4a8 finds the correct series, 1.4.4/1.4.5 can't automatically find it, searching finds a lot of series and have to manually go to the one literally named Spider-Man/Deadpool which is the correct series.

Mr & Mrs X only finds things named X, nothing actually relevant also.

I wonder what changed between those versions that broke this? Most of things work fine, but I've noticed a few of cases where exact name is not found like this. 

I can check more specifically which version broke this if needed from the Releases. I did clear cache to see if it helps, no change.

**Comment by lordwelch** [comment]
1.4.4a8 was the last one that this worked in 1.4.4a9 introduced the change that broke it. If you are curious as to the code that changed check #321. 1.4.6 will be released shortly which fixes these issues
