### ISSUE TITLE
Add Volume # Zero Padding

### ISSUE THREAD

**Issue by WHiZSTA** [comictagger/comictagger#356]
In the same way as there is issue # zero padding, can we get one for volume # zero padding as well please or at least a check where it will always be 2 digits if there is data? Thanks!

**Comment by lordwelch** [comment]
Normally you can do this with `{volume:02}` but I broke it so you'll be able to do it in another release I make later today

**Comment by lordwelch** [comment]
Version [1.4.7](https://github.com/comictagger/comictagger/releases/1.4.7) has been released.
