### ISSUE TITLE
Renaming issue

### ISSUE THREAD

**Issue by WHiZSTA** [comictagger/comictagger#357]
If a comic has a series name with a ' - ' in it,  for example 'my comic - series 2' it will strip the - out upon rename

**Comment by lordwelch** [comment]
This doesn't sound like a renaming issue it sounds more like a fileparser issue.
When renaming ComicTagger only uses information in the metadata it does not care what the filename is. In other words it only uses the information in the form when you open it. For example in this comic the filename is `鋼の錬金術師 #001,.cbz`
 when renaming however it will end up as `Hagane no Renkinjutsushi #001.cbz` as `鋼の錬金術師` is not anywhere on the form. <img width="1102" alt="Screen Shot 2022-08-17 at 4 02 39 PM" src="https://user-images.githubusercontent.com/7547075/185258540-066507f5-66ae-4276-a91b-d8b2bd9596a6.png">

**Comment by WHiZSTA** [comment]
I'm sorry, upon further testing you are right. It keeps the ' - ' i was confusing it with ripping out the ':'. Is there a way to replace the ': ' in series names with ' - ' in filenames for rename?

**Comment by lordwelch** [comment]
It should happen automatically on Windows and you can enable it on macOS and Linux with the `Strict renaming` option in the rename settings.

**Comment by WHiZSTA** [comment]
![image](https://user-images.githubusercontent.com/18521070/185263559-b2150d4f-f112-42fd-aeef-628a59dc5435.png)
No, the app strips it rather than converting it prior to rename, look at what the result will be on the right.

**Comment by lordwelch** [comment]
So, it turns out I only do the replacement on the template text not the actual values, I'm working on a fix

**Comment by lordwelch** [comment]
Release [1.4.8](https://github.com/comictagger/comictagger/releases/tag/1.4.8) has this fixed
