### ISSUE TITLE
CLI rename no-op adds a "(1)" to filename

### ISSUE THREAD

**Issue by beville** [comictagger/comictagger#359]
If I have a tagged comic, and use the command-line to rename it, if there is no change to the file from the rename, it will add a "1" to the filename.

Example:

My rename template:
`rename_template = {series} #{issue} ({year})`

I've got a file with "Captain Marvel Adventures" #11, published in 1942, I've already run the rename on it, and it looks great.
As part of a batch script the rename is run on it again.  In the past this would be a no-op and the name wouldn't change.

Now:

```
$ ls 
'Captain Marvel Adventures #011 (1942).cbz'
$ comictagger  -r  -t cr "Captain Marvel Adventures #011 (1942).cbz" 
renamed 'Captain Marvel Adventures #011 (1942).cbz (1)' -> 'Captain Marvel Adventures #011 (1942).cbz'
$ ls
'Captain Marvel Adventures #011 (1942).cbz (1)'
```
(The rename message is also backwards.)

---------

By the way, nice work on ComicTagger, keep it up!

**Comment by lordwelch** [comment]
I thought I fixed this...

**Comment by lordwelch** [comment]
Release [1.4.8](https://github.com/comictagger/comictagger/releases/tag/1.4.8) has this fixed
