### ISSUE TITLE
Rename replaces "/" with nothing.

### ISSUE THREAD

**Issue by beville** [comictagger/comictagger#360]
I'm not sure if this was already there before, but I notice that with a title like "Batman/Superman", a rename operation will remove the "/" from the title for the filename (which is proper for strict renaming), but it replaces it with nothing, resulting in "BatmanSuperman" in the filename, which seems wrong.  Probably better to replace it with a space.

**Comment by lordwelch** [comment]
Yes, it was pointed out in #357 as well I just pushed a commit to fix it

**Comment by lordwelch** [comment]
Release [1.4.8](https://github.com/comictagger/comictagger/releases/tag/1.4.8) has this fixed
