### ISSUE TITLE
Suggestion: For Rename Smart Text Cleanup replace ":" with " -"

### ISSUE THREAD

**Issue by beville** [comictagger/comictagger#361]
This is not imperative, but it's a nice formatting thing.

If Strict Renaming is on, the colon character has to be removed from the filename, and that's what currently happens, so the title

"Superman: The Man of Steel" is changed to "Superman The Man of Steel"

but it would be slightly cooler to detect when a colon is at the end of a word, and replace it with \<space\>\<hyphen\> or " -". For example:

"Superman: The Man of Steel" is changed to "Superman - The Man of Steel"

which more looks nice and I this is valid on all filesystems.

**Comment by lordwelch** [comment]
This is what I do, I forgot to apply it to the actual values, so a series name, on windows the colon just disappears, but if if you put a colon manually in the template this suggestion is what gets applied, I plan on making a point release to fix it tonight

**Comment by lordwelch** [comment]
Release [1.4.8](https://github.com/comictagger/comictagger/releases/tag/1.4.8) has this fixed
