### ISSUE TITLE
Feature Request: parsing just name and issue number

### ISSUE THREAD

**Issue by musictrivianut** [comictagger/comictagger#364]
I really do not know *anything* about how this software works, only that it is wonderful and I really appreciate all the hard work.

That said, I do sometimes find files that do not conform to any sort of "standard" naming format, so they will have the wrong year (series start instead of  issue release year) or free text in the filename not enclosed in parentheses.  Both of those things throw off the search function.  Was wondering if it would be possible to add an option that would tell the search function to *only* search using the series name and issue number, i.e. throw out everything following those two items.  Yes, it could possibly make for a broader search, but it would also avoid more than a few "Not match found; save aborted" errors and allow comictagger to continue on its way nicely.

If not possible or too complicated, understand completely.  Just a thought.

Edit:  Had a thought.  I normally use the CLI version, but decided to see what the GUI parses when a "bad" filename is put in (no parentheses).  Turns out that it thought that the entire thing was the series name.  Didn't even figure out what the issue number was.  Don't know if that helps, but...

**Comment by lordwelch** [comment]
The only information that ComicTagger uses to search is year, series name, and issue number when in the GUI you can either remove the year or when using the Auto-Tag feature there is an option to ignore it <img width="665" alt="Screen Shot 2022-05-19 at 7 04 04 PM" src="https://user-images.githubusercontent.com/7547075/169434326-ce4888c1-2050-4c67-9eb9-84bc349e5fb1.png">

On the CLI you can specify metadata via the `-m` option for example `-m year=` will unset the year

**Comment by musictrivianut** [comment]
Thank you for that.  In that case, I think it is the part in my edit that is pertinent, then.  When text is not in parentheses, it throws off the parsing and comictagger thinks that all of the free text is the series name, sometimes including the issue number.

These two images should illustrate what I mean.  The only difference between the two files loaded into the GUI is the filename (I copied the file and then renamed the new one, taking out the parentheses, which is the way that I got it).  If it is just a single file or even a dozen, okay, I can deal with that, but it does get tedious.  The problem really gets annoying when there are lots of files of varying lengths to rename properly, which is *really* not fun.

So, maybe this isn't really a "feature request" as much as a bug, since CT isn't parsing the series name correctly when the filename is malformed?

And as I said before, if there is nothing to be done in the program, that is fine, I will continue as before.  But I really do appreciate you taking a look at this.

![tag good](https://user-images.githubusercontent.com/18358514/186776645-9bb13c88-1da0-4cc0-a6ef-ec7b760ebfdc.png)

![tag bad](https://user-images.githubusercontent.com/18358514/186776665-54d5961c-1f26-4070-952d-7119f56c0f2f.png)

**Comment by lordwelch** [comment]
So for this reason there are two filename parsers. If you go into settings under `Filename Parser` there is an option to enable the 'Complicated Parser'. It should parse out the filename as you want it to

**Comment by lordwelch** [comment]
Also for parsing any file if the number has a hashtag in front of it it will do several times better than if it does not

**Comment by musictrivianut** [comment]
That did it!!  Woohoo!  I had no idea that setting was there.  Thank you so much!!!
