### ISSUE TITLE
Cross-device link error on rename

### ISSUE THREAD

**Issue by jwynn6** [comictagger/comictagger#365]
Cleaning up a messy directory and the following error occurs when I rename the files.  This appears to be around the usage of os.rename. I'm moving files from a local directory to one on an nfs share mounted on my host.

> Oops. An unexpected error occured:
>  File "/usr/lib/python3.10/site-packages/comictaggerlib/renamewindow.py", line 186, in accept
>    os.rename(item["archive"].path, new_abs_path)

> OSError: [Errno 18] Invalid cross-device link: '/home/user/local/oldname.cbz' -> '/home/user/sharedir/newname.cbz'

**Comment by lordwelch** [comment]
You do not appear to be on the latest version. What version are you running?

**Comment by jwynn6** [comment]
I was not running the latest. Looks like the AUR is out of date at the moment. I manually upgraded and voila, things worked!
