### ISSUE TITLE
Feature request: disregard black border on digital comics

### ISSUE THREAD

**Issue by musictrivianut** [comictagger/comictagger#366]
Hello again, back with another...suggestion?  Request?

As always, no idea how hard this might be to do, but has anyone ever brought up the fact that comictagger and the image comparing has a difficult time with digital covers that include a black border?  I always get a  low-confidence match on those.  Yes, I am well aware that you can set it to go ahead and save when that happens, but wouldn't it be better to have a better match?  Is there any way to have the system ignore or crop the cover image to exclude the border and then match?

And if not, not a huge deal.  Still a fantastic piece of software.  Thanks!

**Comment by lordwelch** [comment]
Turns out this should be pretty simple, https://stackoverflow.com/questions/19271692/removing-borders-from-an-image-in-python, it might be a week or two till I get around to testing though, and it will almost definitely be a setting that is off by default.

**Comment by musictrivianut** [comment]
Sweet!!  And thank you!!

Suggestion, though?  Understand this is something that would be off by default, because you don't necessarily want *every* cover processed like this.  But, is there a way to go through a second processing, for those that don't match the first time?  They usually come back as a low-confidence match.  Could this be set up to run those through the crop and then matched again?  Probably a headache for programming, but would definitely make matching easier/better, IMO.

Whatever you end up doing, this is a great piece of software!  Appreciate the time you put in.

**Comment by lordwelch** [comment]
That's not a bad idea, can you open a separate issue for that?

**Comment by musictrivianut** [comment]
Done!  And hope that what I put in there is sufficient.

**Comment by lordwelch** [comment]
@musictrivianut I looked at this again and realized I there is already a list of images to use as the cover and I can just add this to the end. This will be in the next pre-release
