### ISSUE TITLE
CLI ERROR: 'blah'.cbr is not a comic archive! 

### ISSUE THREAD

**Issue by Xellinus** [comictagger/comictagger#371]
Everything works fine in the gui but the CLI won't work on my cbrs despite being a proper file.

022-09-11T08:49:38 | comictaggerlib.cli | ERROR | Sorry, but (*********).cbr is not a comic archive

**Comment by lordwelch** [comment]
please provide the full log located at either %appdata%\ComicTagger\logs on Windows or ~/.ComicTagger/logs on Linux and macOS

**Comment by Xellinus** [comment]
[ComicTagger.log](https://github.com/comictagger/comictagger/files/9543209/ComicTagger.log)

**Comment by lordwelch** [comment]
This looks like you installed via pip please reference the [pip installation instructions] and include the CBR optional dependency.
Or alternatively use the pre-compiled exe located on the releases page https://github.com/comictagger/comictagger/releases

[pip installation instructions]: https://github.com/comictagger/comictagger#pip-installation

**Comment by Xellinus** [comment]
Thanks!
