### ISSUE TITLE
Bug?  Stuck on "searching for alt. covers"

### ISSUE THREAD

**Issue by musictrivianut** [comictagger/comictagger#372]
Did a quick search of the issues, but did not see this in there.

When using the GUI (at least, may be CLI also, dunno) and it comes back with a low-confident match, it will show the "normal" cover on the right but the text underneath says "searching for alt. covers" and just....stays there?  It doesn't seem to actually be searching for alternates because, if it did, it probably would find a match.

Looks like the same is happening when using the Auto-Identify function.  Once you find the right series and issue, it will also showing "searching for alt. covers" but it never comes up with any (and there definitely are with the issue I just tried).

I know this worked previously because I have looked through alternate covers before.  Not sure if some change in the code is the cause or maybe it's a CV thing?

**Comment by lordwelch** [comment]
It should just be the GUI, this is because we use Qt's library for network requests when we run the GUI and I've had some trouble getting it to work consistently.

**Comment by ducky0518** [comment]
I'm also seeing this issue, which is limiting my ability to match issues without manually going to CV. Any options here?

**Comment by lordwelch** [comment]
@ducky0518 @musictrivianut there is still an issue when using the search button to browse the comic issues that it will not retrieve the alternate covers, in the mean time you will need to use the auto-identify or the auto-tag feature for it to retrieve the alternate covers, on the latest release [1.5.3].

[1.5.3]: https://github.com/comictagger/comictagger/releases/1.5.3

**Comment by lordwelch** [comment]
Please ignore 1.5.3 [1.5.4] is released now

[1.5.4]: https://github.com/comictagger/comictagger/releases/1.5.4

**Comment by ducky0518** [comment]
Even on v1.5.4 I'm not seeing the alternative covers with auto-identify. It still says "Searching for alt. covers" - and yes I have an issue where I've verified there are multiple covers on CV. Here's an example:
https://comicvine.gamespot.com/no-hero-2/4000-141243/

**Comment by ducky0518** [comment]
OK - I think I see how this works now. It's only if it doesn't think its a match will you see the arrows for the additional covers show up. Is that correct? When I moved the covers around in the file so the first one was different than the primary one on CV, then the multiple covers arrows showed up. Interesting. So does that mean it uses that image matching algorithm to decide whether or not to show the additional covers?

**Comment by lordwelch** [comment]
Yeah, it's really buggy right now. When #341 is merged this should all work consistently.

**Comment by ducky0518** [comment]
Yeah, It seems to be working like 5% of the time for me. Definitely it doesn't work far more than it does. As long as you're seeing this same behavior. We're good.

**Comment by mizaki** [comment]
This can be closed now?

**Comment by lordwelch** [comment]
Yes this was fixed by @mizaki in #341
