### ISSUE TITLE
CLI: Filename too long should fail gracefully and continue

### ISSUE THREAD

**Issue by jacobkossman** [comictagger/comictagger#374]
Running 1.4.3 so forgive me if this is fixed already I've installed using `pip3 install --user --pre 'comictagger[GUI]'` on Ubuntu

Running a rename operation with the new rename template `rename_template = {series} #{issue} {title} ({year})`

The error is as follows:
```
2022-09-19T21:12:26 | comictagger | ERROR | CLI mode failed
Traceback (most recent call last):
  File "/home/XXXX/.local/lib/python3.8/site-packages/comictaggerlib/main.py", line 147, in ctmain
    cli.cli_mode(opts, SETTINGS)
  File "/home/XXXX/.local/lib/python3.8/site-packages/comictaggerlib/cli.py", line 168, in cli_mode
    process_file_cli(f, opts, settings, match_results)
  File "/home/XXXX/.local/lib/python3.8/site-packages/comictaggerlib/cli.py", line 490, in process_file_cli
    os.rename(filename, new_abs_path)
OSError: [Errno 36] File name too long:
```

Obviously I could remove `{title}` from the template but I would like to keep it. Is it possible for comictagger to know the limit for most OSes and either truncate with ... or remove the title all together when it would be too long coupled with the series etc?

Thanks!

**Comment by lordwelch** [comment]
@jacobkossman the file limit should be 255 characters what comic are you trying to rename? There is almost no reasonable way for this to happen.

You can use the `-n` or `--dryrun` option to see what the filename is

**Comment by jacobkossman** [comment]
@lordwelch 

https://comicvine.gamespot.com/deadpool-27-the-wedding-of-deadpool-operation-ball/4000-450073/

this name is absurd 😂  either way it should be able to fail gracefully or remove the title if it would be too long

**Comment by lordwelch** [comment]
Deadpool would do this to me 😒, but yes, ComicTagger fails gracefully on the latest commit I haven't made a release with it yet though.
As a way to actually make it work you can specify a maximum number of characters when using python format strings like so `{title:.100}` this would limit the title to the first 100 characters

**Comment by jacobkossman** [comment]
thanks i'll check back if i get it working

since I attempted to install 1.5.0 (i realized how behind it was) using `pip3.9 install 'comictagger[CBR]'` and i must have screwed something up 🤦  this is why i should stick to docker lol. i'll make a new issue 😭

**Comment by jacobkossman** [comment]
confirming that this `{title:.100}` does work. however, i'm leaving this open when failing gracefully is "fixed" in a release 😄

**Comment by lordwelch** [comment]
Fixed in the latest release
