### ISSUE TITLE
CBR:  ComicRack tags work, CBL tags do not

### ISSUE THREAD

**Issue by kainearashi** [comictagger/comictagger#376]
[ComicTagger.log](https://github.com/comictagger/comictagger/files/9694334/ComicTagger.log)
I hope this is the right place.  Thanks for all your work on this software, it's really slick!

I get the error: The tag save operation seemed to fail! when I try to Save Tags, using ComicBookLover style on CBRs.  ComicRack tags work fine.

I am running 
ComicTagger v1.5.0 (from binary installer)
WinRAR 6.11 64-bit
Win 10 21H2 64-bit

I tried an earlier version of ComicTagger v1.4.8, various path/reinstall things with WinRAR (I didn't realize it was a problem with CBL at first, and people seemed to have issues with RAR installs.)

I'm ok using CR tags, but it took me a while to figure out that I could. CR tags save fine with CBR files, but not CBL.  But I thought I'd report it in case it's an issue.

If CBL is inherently incompatible with CBR, my apologies, I'm new to all of this.  Thanks very much!

Edit updated with log per request

**Comment by lordwelch** [comment]
They're supposed to work, I just don't test them much...

**Comment by lordwelch** [comment]
There is a log located at `%APPDATA%\ComicTagger\logs` can you attach it to this ticket?

**Comment by kainearashi** [comment]
[ComicTagger.log](https://github.com/comictagger/comictagger/files/9694040/ComicTagger.log)
Activities:
Search-then-Save Tags CBL
Auto-Tag CBL
Search-then-Save CR

**Comment by kainearashi** [comment]
(Thanks!  I don't mind using CR tags, it was just that CBL was the default when it loaded for the first time and it took a bit to realize that I needed to change it.)

**Comment by lordwelch** [comment]
Fixed in the latest release
