### ISSUE TITLE
Make Scan Info tag viewable in GUI tabs (I'm assuming under info or other)

### ISSUE THREAD

**Issue by ducky0518** [comictagger/comictagger#380]
Right now the only way to view the Scan info tag (actually called  <ScanInformation>) in the GUI is by going into the File menu and selecting "View Raw Tags" and then -> "View Raw ComicRack tags" This takes a lot of time if you want to quickly look through several items that you have in your File list. Can this be presented in the GUI similar to the other tags? Thanks!

**Comment by lordwelch** [comment]
Are you looking for this?
<img width="1102" alt="Screen Shot 2022-10-04 at 11 49 12 PM" src="https://user-images.githubusercontent.com/7547075/193998233-f641e000-e022-4b5e-9c44-1a732ce657b0.png">

**Comment by ducky0518** [comment]
Yep. Crazy that I missed that. Sorry and thanks for the quick response.
