### ISSUE TITLE
Error writing any .cbr files

### ISSUE THREAD

**Issue by ducky0518** [comictagger/comictagger#381]
I've got rar.exe from the Winrar directory set in the UI.

Whenever I try to auto tag any .cbr (rar) files, they seem to fail - here's what I see in the logs:

2022-10-09 23:57:26,355 | comicapi.comicarchive | ERROR | Error writing rar archive [exitcode: 9]: M:\Comics\Dark Shadows (2011)\Dark Shadows 001 (2011) (2 covers) (digital) (Minutemen-InnerDemons).cbr :: ComicInfo.xml
2022-10-09 23:57:29,800 | comictaggerlib.taggerwindow | INFO | Successfully tagged archives: 0
Archives that failed due to file writing errors: 1

Any ideas? I have read/write access to this directory. I'm using Winrar 6.11 (newest) 64-bit.
If I chose convert to zip then the tags successfully write. Thanks!

**Comment by lordwelch** [comment]
Well exit code 9 is is a file create error from rar, so it either doesn't have access to create a file or it's given the wrong path (when rar edits files it creates a new temporary file and rewrites the whole thing). Can you attach the log file from %APPDATA%\ComicTagger?

**Comment by ducky0518** [comment]
[ComicTagger.log](https://github.com/comictagger/comictagger/files/9769256/ComicTagger.log)

**Comment by lordwelch** [comment]
I cannot re-produce this issue, I suggest copying that cbr file to your desktop and trying again, to ensure there are no access/permission issues, if that still fails open it in winrar and try to save it again, using the `save archive copy as...` option in the file menu or by editing the comment, and trying again with the new file.

**Comment by ducky0518** [comment]
Feel free to close this issue. I'm tagging via CR and the CV Scraper now due to other automation that surround it. Thanks for the help.
