### ISSUE TITLE
Error about python-Levenshtein on Macintosh

### ISSUE THREAD

**Issue by ghjimmy** [comictagger/comictagger#382]
I downloaded the latest version of comictagger (1.5.1) from homebrew upgrading from version 1.3
After changing my rename template, I'm getting errors about installing python-Levenshtein.
I installed it via pip3 install levenshtein but am still getting the error/warning.
Is there something else I should be setting/running to remove the error?
I'm running Python 3.10 on Mac OS Ventura, patched to the latest version.

Thanks,

**Comment by lordwelch** [comment]
No, unless someone added a new package to homebrew it uses the pre-compiled .app that I publish which still runs on Python 3.9. That warning should not have any effect when running and will be removed in the next release.

**Comment by ghjimmy** [comment]
Thanks for that.  I though that it used internal only binaries, so I was a bit confused as I have a script that parses the output and had to tweak it to be more resilient - no bad thing - due to the warning.
