### ISSUE TITLE
Smart renaming seem to be broken

### ISSUE THREAD

**Issue by ghjimmy** [comictagger/comictagger#384]
This is another issue I've seen upgrading to 1.5.1  The smart renaming seems to be not working:

my settings file:
```ini
[rename]
rename_template = {series} #{issue} {title} ({year}-{month:02})
rename_issue_number_padding = 3
rename_use_smart_string_cleanup = True
```

```console
$ comictagger --version
thefuzz/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
ComicTagger 1.5.1:  Copyright (c) 2012-2022 ComicTagger Team
Distributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
$ comictagger -v --rename --type=cbl bb.cbz
thefuzz/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
renamed 'bb.cbz' -> 'Superman: Son of Kal-El #016 KAL-EL RETURNS, PART 2: REUNION (2022-12).cbz'
```

On my other machine:
settings:
```ini
[rename]
rename_template = %series% #%issue% %title% (%year%-%month%)
rename_issue_number_padding = 3
rename_use_smart_string_cleanup = True
```
```console
$ comictagger --version
ComicTagger 1.2.3:  Copyright (c) 2012-2014 Anthony Beville
Distributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
$ comictagger -v --rename --type=cbl bb.cbz
renamed 'bb.cbz' -> 'Superman - Son of Kal-El #016 KAL-EL RETURNS, PART 2 - REUNION (2022-12).cbz'
```

The difference is the colons in the filename are there under 1.5.1 and not there under 1.2.3

Is there an extra setting that needs to be turned on to revert to the old naming convention?

Thanks.

**Comment by lordwelch** [comment]
Yes, as macOS and Linux allow colons in filenames, ComicTagger now leaves them in by default if you are on macOS or Linux. You can set the `rename_strict` option to True in order to have colons replaced on Linux and macOS
```ini
[rename]
rename_strict = True
```

**Comment by ghjimmy** [comment]
Excellent.  Just tried it and it works as I wanted.  I was used to the renaming for 2 reasons:
1. When looking at the files in finder the "/" <-> ":" mapping just looks odd.
2. When using shared files in VMware fusing from my Mac OS to a Linux client, Fusion doesn't like files with ":" in their names for some reason so I like to avoid them.

Thanks again for the prompt reply.
