### ISSUE TITLE
Comic genre never populated

### ISSUE THREAD

**Issue by czearing** [comictagger/comictagger#395]
I can't find any information regarding this in the docs. Upon tagging a comic it never seems to populate the genre field. The genre tag is quite helpful for discovery in some of the platforms such as Komga. Is there a way to get this to work? Maybe concepts from the comic vine API could optionally be appended to genres?
Thanks!

**Comment by lordwelch** [comment]
Duplicate of #217 and #219. No, ComicVine does not have genre information available via the API.
The best I could do is add the concepts as tags, but currently ComicTagger does not have support for saving tags to the ComicRack/ComicInfo format. Komga in particular does not support the Comic Book Lover (CBL) format which ComicTagger does support adding tags to.

**Comment by czearing** [comment]
I appreciate the quick response and explanation! That makes sense. Will close since this is a duplicate.
