### ISSUE TITLE
Unsupported HTML shows as text in volume description

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#396]
I've found a volume description with a `figure` HTML tag. Volume ID: 18836 (https://comicvine.gamespot.com/naruto/4050-18836/)

Because only a limited number of tag are support (https://doc.qt.io/qtforpython-5/overviews/richtext-html-subset.html#supported-html-subset) the whole string is rendered as text. I presume it doesn't see it as HTML at all.

I wrote this function:
```
def clean_uncommon_html(string: str) -> str:
    if string is None:
        return ""

    soup = BeautifulSoup(string, "html.parser")
    figure = soup.figure
    if figure:
        figure.decompose()

    return str(soup)
```
I don't know if you'd want to do it another way? Also, where would be the best place to put something like it? In the API utils? Should the talker be expected to filter it out (as CV only problem)? Should the function remove any tags that aren't in a whitelist?

**Comment by lordwelch** [comment]
It should be a cv only problem but it might be better to just use a QWebEngineView, it would add a dependency on pyqtwebengine-qt5 but would have full html support
