### ISSUE TITLE
Publisher name gets cut-off when the series name is too long

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#402]
It's mainly the search window that this becomes annoying with but others should probably remember their size and position too.

**Comment by lordwelch** [comment]
All popup windows should be centered on the main window, including the search window

**Comment by mizaki** [comment]
That's fine initially but if I move it and resize it, I think it's fair to expect it to be remembered. If not through a restart of the program, at least within the session.

**Comment by lordwelch** [comment]
Right now that all of the windows are consistently centered on the main window is considered a feature. It would also make moving the main window unnecessarily complicated to do correctly because if someone does a search, possibly tags a comic, and then moves the main window to another monitor now it shows up where it used to be on the previous monitor, which is fair to say nobody wants.

**Comment by mizaki** [comment]
I would disagree and say that the user is god (even if it's a stupid one). If god wants their window on another screen, so be it. Even if they are not saved between launches, I think if a user moves and resizes a window, they expect it to be the same the next time they see. It looks like the big problem there is qdialog's are destroyed and so can't be re-used/updated so they'd keep their position and size.

Maybe an alternative is to better size (width wise) the search window to the information within? Making sure it's never bigger than the main window?

**Comment by lordwelch** [comment]
Show me how this is a bug and not a preference.
Until you can do that this is not changing.

**Comment by mizaki** [comment]
![Screenshot_2022-11-28_01-31-08](https://user-images.githubusercontent.com/1141189/204392022-d5c07517-6aa4-44d1-8788-02f9e572a410.png)
There is a long title in the above which causes the publisher to be hidden.

**Comment by lordwelch** [comment]
So the problem is that by default the publisher gets cut-off, check PR #405 It sizes the columns and rows to ensure that they can be read.
