### ISSUE TITLE
Issue numbers greater than 1000 not being parsed correctly?

### ISSUE THREAD

**Issue by musictrivianut** [comictagger/comictagger#414]
I can probably provide some examples, but it appears that for series with issue numbers greater than 1000 (specifically Action Comics and Detective Comics, not sure if there are others), the issue number is being parsed as part of the title.  Looking at the files in the gui, the issue number is not under "Issue", but rather in "Series" with the title.  Believe the cli is behaving the same, since it did not find and tag the latest ones (for me, at least) and I had to open them in the gui and hence, found what I did.

**Comment by lordwelch** [comment]
As a work around if you add a `#` in front of the number it will always parse correctly, you can also disable the complicated parser and it should parse the issue number correctly. I have also fixed this in fb4786159d4301b6423044a6345a7f7ad2b7854f.
