### ISSUE TITLE
key not valid for comic vine

### ISSUE THREAD

**Issue by ISeeTWizard** [comictagger/comictagger#434]
Hi
I have a problem that my api key isn't valid for comic tagger but for comic vine it is
I even recreated a new account to change the key and nothing changed, always key not valid and so no updates possible.
Anyone else having that issue recently?
When removing my personal API Key it works...

**Comment by lordwelch** [comment]
Using a personal API key works on the latest release [1.5.5]. I just tested to confirm

[1.5.5]: https://github.com/comictagger/comictagger/releases/tag/1.5.5
