### ISSUE TITLE
[Feature Request] Flatpak and/or AppImage

### ISSUE THREAD

**Issue by bmfrosty** [comictagger/comictagger#439]
I've been trying to get this to run on a steamdeck and am having a terrible time.  I worked through multiple build problems, but I'm stuck on unrar-cffi.

I'd love to see this available as a Flatpak and/or AppImage.

**Comment by lordwelch** [comment]
Flatpak would make me re-create all of the build steps and doesn't have any useful dependency management which adds a lot more work and I'm not going to maintain two completely separate build files. If someone else wants to that's fine.

AppImage basically just copies everything needed into an ISO file and makes it executable, which is almost exactly what PyInstaller does, so not much of a point in using it.

So I did find out what was causing the Linux PyInstaller to crash. Can you download the Linux build from here and try it? https://github.com/comictagger/comictagger/actions/runs/4239273956

**Comment by bmfrosty** [comment]
That works.  I was able to run it from that.

I don't care much what it is.  I'm personally going to be happy with a statically linked binary as long as I can get it to run.

**Comment by bmfrosty** [comment]
I locally built what I downloaded into an appimage.  Only required two files and a symbolic link.  I'll look at your build pipeline, but I suck at build pipelines.

**Comment by bmfrosty** [comment]
Created a pull request that does this.  Possibly clumbsily.

https://github.com/comictagger/comictagger/pull/440

**Comment by bmfrosty** [comment]
Does it run the appimage the same for the Mac Build?  I never got into the mac and windows builds because I'm not on any paid plan with github.   Crud.

**Comment by bmfrosty** [comment]
Pushed what should be the fix to the branch.

**Comment by bmfrosty** [comment]
I think it's just creating a single zip now for both.  I'll close the pull request when I have a bit of time to troubleshoot.  At least it's successfully building all three now.

**Comment by bmfrosty** [comment]
It's still bundling the appimage into the zip with the other zip.  I'm getting frustrated with the release process though.  PR is open again.  If you want to use it and just add a tweak or two or use the Makefile as an example on how to create an appimage, it's fine by me.

**Comment by lordwelch** [comment]
> It's still bundling the appimage into the zip with the other zip. I'm getting frustrated with the release process though.

That's just how GitHub Actions works, a name is created for an artifact in this case ComicTagger-Linux and files are added to that name in this case the zip and the appimage. Releases are different they let files be attached directly without any artifact names involved.

**Comment by lordwelch** [comment]
Fixed in #440
