### ISSUE TITLE
God is Dead - TypeError

### ISSUE THREAD

**Issue by gardn701** [comictagger/comictagger#443]
Came across this error today that crashes the app when you attempt to open the series from the Select Series window.  Not sure of the specifics of what is going wrong, but posting it here for y'all.

Using v1.4.3

<img width="631" alt="2023-03-03 (1)" src="https://user-images.githubusercontent.com/79603982/222810942-278eff29-b4f8-4c74-8e8e-b0c4e7088ff7.png">

**Comment by lordwelch** [comment]
I cannot re-produce this on [1.5.5]

[1.5.5]: https://github.com/comictagger/comictagger/releases/tag/1.5.5
