### ISSUE TITLE
Breaks CBZ/CBR file preview on Mac

### ISSUE THREAD

**Issue by mslmn** [comictagger/comictagger#444]
I've noticed that when I have the app installed I can no longer see the cover of a cbz/cbr file in the Finder Preview. Uninstalling the app fixes the problem.

**Comment by lordwelch** [comment]
Previews are not created for cbz/cbr files by default on Marcos so that means you have another program creating the preview for those files. You can probably get the previews back by setting it as the default program for cbz/cbr files.

**Comment by mslmn** [comment]
I'm using EdgeVIew for that but for some reason when comictagger is installed the previews stop working.

**Comment by lordwelch** [comment]
Well I can't troubleshoot EdgeView. That is a completely separate piece of software. You can try my suggestion of setting it as the default application for cbz/cbr files. But for anything else you will have to get support from them on why their feature doesn't work.
