### ISSUE TITLE
When running two instances at the same time on Windows 10 the log is locked causing an exception.

### ISSUE THREAD

**Issue by billroemhild** [comictagger/comictagger#445]
Platform: Windows 10
Version: 1.5.5

When running two instances at the same time the log is locked causing an exception.

Uncaught exception: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\bill\\AppData\\Roaming\\ComicTagger\\logs\\ComicTagger.log' -> 'C:\\Users\\bill\\AppData\\Roaming\\ComicTagger\\logs\\ComicTagger.log.1'
Traceback (most recent call last):
  File "comictagger.py", line 9, in <module>
  File "comictaggerlib\main.py", line 138, in ctmain
  File "comictaggerlib\main.py", line 115, in rotate
  File "logging\handlers.py", line 177, in doRollover
  File "logging\handlers.py", line 115, in rotate
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\bill\\AppData\\Roaming\\ComicTagger\\logs\\ComicTagger.log' -> 'C:\\Users\\bill\\AppData\\Roaming\\ComicTagger\\logs\\ComicTagger.log.1'
[192668] Failed to execute script 'comictagger' due to unhandled exception

**Comment by billroemhild** [comment]
Should probably mention this is running from the CLI.

**Comment by lordwelch** [comment]
If you want to run two instances you need to use two separate configuration directories. The log, cache and other things do not work when there are two instances running using the same configuration directories.
The GUI solves this by only ever running one instance and sending new file paths to the original. I currently do not have a nice message when running from the CLI.

Note that if you run a separate instance you will need to copy your configuration to the second location.
`comictagger.exe --config "C:\Users\ct\comictagger_config"`

**Comment by billroemhild** [comment]
Sweetness.  Thanks for getting back with me.  I'll try it out.
