### ISSUE TITLE
Autotag grab the wrong issue

### ISSUE THREAD

**Issue by Bazzu85** [comictagger/comictagger#448]
Hi guys,

this serie have 2 #0 numbers:
https://comicvine.gamespot.com/batwoman/4050-36950/

![image](https://user-images.githubusercontent.com/7345587/230033598-cfc7b599-7d44-41ed-bb0a-89cfd50cd0b6.png)

When using autotag on the november 2012 issue (with correct cover) the app give the issue with the other cover:

![image](https://user-images.githubusercontent.com/7345587/230033912-abe79334-cdc3-4315-98c3-e1fea2e13df7.png)

using Auto-identify give this:

![image](https://user-images.githubusercontent.com/7345587/230034069-95ff70c7-18fd-4de5-a1eb-43c11c95c30b.png)

and I can choose the correct one:

![image](https://user-images.githubusercontent.com/7345587/230034176-b9efb4f0-ab3a-40d1-8040-5dfde1870d1c.png)

Is this an auto-tag bug or what?
thx

**Comment by lordwelch** [comment]
I don't think ComicTagger handles the duplicate issue number gracefully.
@Bazzu85 can you attach the log file, it should be located at `C:\Users\<username>\AppData\Local\comictagger\Logs`

**Comment by Bazzu85** [comment]
> I don't think ComicTagger handles the duplicate issue number gracefully. @Bazzu85 can you attach the log file, it should be located at `C:\Users\<username>\AppData\Local\comictagger\Logs`

the logs are located in the roaming folder `%appdata%\ComicTagger\logs`

here's the log of autotag: 
[ComicTagger.log](https://github.com/comictagger/comictagger/files/11167849/ComicTagger.log)

**Comment by lordwelch** [comment]
So this issue happens because you have the year set and it does not match the year that ComicVine has set. This usually happens because of the difference between the cover date and the in-store date (Here's an explanation if you are unaware https://dc.fandom.com/f/p/2951064579997697606)
