### ISSUE TITLE
Unexpected Error: bad character range e-b at position 5?

### ISSUE THREAD

**Issue by DevXen** [comictagger/comictagger#449]
So everytime i try to add a folder to either version in windows 10: 
1.6.0-alpha.0: Cole Cash
1.5.5: Scanlan Shorthalt

I get the following error: 
![FK28Ew1YeU](https://user-images.githubusercontent.com/2284801/231619126-c56bd4d9-1fb2-4677-8bf6-77141005e22d.png)

I have tried:
To run them with administrator access.
Downloading the files again and unzipped them.
I even installed chocolatey and installed it from there. 
Tried several different folders.
Tried moving one of the folders up to the root of the drive to see if maybe it was a folder path length issue.

Nothing I've tried has worked. 

I have an older version, ComicTagger v1.1.15-beta that loads the folders just fine. but that version I noticed was actually installed to my program files (x86) folder. it's not a stand alone/portable .exe file like the latest 2 versions that i have tried have been. I'm not sure if that's related. i didn't try any older versions. 

the newer versions do work on single comic books. just seems to pull this error if i try to add any folder.

Anyhow I'm not sure how to fix it and looking online didn't pull anything up. so I thought i'd post here.

Thanks,
-Dev

**Comment by lordwelch** [comment]
This bug happens because you have this `[e-b]` in the name of the file you are opening. As a workaround you can put your comics in a folder without brackets and have ComicTagger open the folder instead of the individual comic. A fix will be in the next alpha.

**Comment by DevXen** [comment]
I read this . And we'd like no the folder and test folders don't have brackets the realized my main comics folder is: [Comics] but I do have a a lot of brackets in my folders to tidy them up.. Thanks for the fix in the next alpha release.
