### ISSUE TITLE
No matches when running from CLI, but everything works in the GUI

### ISSUE THREAD

**Issue by Nuddel69** [comictagger/comictagger#456]
Basically a reopening of [this](https://github.com/comictagger/comictagger/issues/9) issue. I've checked comicvine and the issue is present. Using the "Search Online" function in the GUI app works fine (all metadata is scraped and the tags are saved to the CBZ archive), but when I try to use the CLI I'm getting an error of no matches. I'm on macos, and comictagger is installed globally through pip3. 

This is the command I'm attempting to execute. I want to search comicvine for the issue, and assign all the metadata. 
`comictagger -s -t CR -f -o Witch\ Hat\ Atelier\ v01\ \(2019\)\ \(Digital\)\ \(goldenagato\).cbz`

This is what's returned:
`2023-04-24T16:03:45 | comictaggerlib.cli | ERROR | Online search: No match found. Save aborted`

**Comment by lordwelch** [comment]
Can you provide the full log. you can find it by opening console.app in utilities

**Comment by lordwelch** [comment]
fixed by 3a287504ae85bd4b4c2028a4202fa29b9507af0c
