### ISSUE TITLE
Unhandled exception error when running Comic Tagger

### ISSUE THREAD

**Issue by IDontKnow218** [comictagger/comictagger#460]
Just reinstalled Windows on my laptop. Comic Tagger used to work before I reinstalled. Every time I try to run it I get this. Any fix?

![image](https://user-images.githubusercontent.com/72819892/235722704-848ebbcf-ebd4-4f58-bd82-ce047b6b4a67.png)

**Comment by mizaki** [comment]
Looking at https://github.com/maxbachmann/RapidFuzz/releases/tag/v3.0.0:
```
remove rapidfuzz.string_metric module.
```
Which seems to fit the issue. How did you install and what version of CT?

If you use rapidfuzz [2.15.1](https://github.com/maxbachmann/RapidFuzz/releases/tag/v2.15.1) that should work for now until it can be looked at properly.

**Comment by lordwelch** [comment]
@IDontKnow218 please test with the exe from the latest release https://github.com/comictagger/comictagger/releases/tag/1.5.5
