### ISSUE TITLE
Oops. An unexpected error occurred when search online

### ISSUE THREAD

**Issue by Bartype** [comictagger/comictagger#462]
Comictagger run from Windows 11 always gives me an unexpected error when starting to search online (click on "Search Online", "Literal Search", "Auto-Identify" or "Auto-Tag"). Because i can't find a solution i open an issue here. See the picture for the error. After i click [OK] comictagger is closed. The version of comictagger doesn't seem to matter, i have this issue from 1.4.8 and up.

<a href="https://imgur.com/zLVqkBe"><img src="https://i.imgur.com/zLVqkBe.jpg" title="source: imgur.com" /></a>

**Comment by lordwelch** [comment]
Please go to settings and click clear cache

**Comment by Bartype** [comment]
Thanks, that does the trick!
