### ISSUE TITLE
[Feature Request] Add Text Input for Filtering Search Results in Select Series Window

### ISSUE THREAD

**Issue by apiweb** [comictagger/comictagger#476]
**Description:**
I would like to propose a new feature for ComicTagger that would enhance the user experience when searching for series in the Select Series window. The addition of a text input field would allow users to filter the search results more conveniently.

Currently, when using the Select Series window, the search results are displayed in a list format. However, when dealing with a large number of series, finding the desired series can become time-consuming and tedious. By incorporating a text input field, users could enter keywords or specific titles to filter the results, making the search process more efficient.

Here's how the proposed feature would work:

1. Open the Select Series window in ComicTagger.
2. Notice the new text input field at the top of the window, labeled "Filter Results."
3. As the user begins typing in the text input field, the list of series dynamically updates to show only the entries that match the entered text.
4. The filtering should be performed in real-time, meaning that with each keystroke, the search results are refined based on the current input.
5. The filtering should take into account series titles, publisher, year, or any other relevant information associated with the series.

This new feature would significantly improve the efficiency and user-friendliness of the Select Series window, especially when dealing with extensive libraries or collections. Users would be able to quickly narrow down the search results to find the desired series with ease.

<img width="1195" alt="Pasted Graphic 2" src="https://github.com/comictagger/comictagger/assets/5881027/ddf3391e-7b9d-41f6-9f9e-471e5cd866ba">

**Comment by lordwelch** [comment]
Turns out this is super easy to implement with Qt. Thanks for the suggestion!
