### ISSUE TITLE
[Feature Request] Add Option to Clean the List in a Single Action

### ISSUE THREAD

**Issue by apiweb** [comictagger/comictagger#477]
**Description:**
I would like to suggest a new feature for ComicTagger that would streamline the process of cleaning the list by adding an option to remove all items at once. Currently, to clear the list, users need to select all the items manually and then click on the "Remove Selected Items" button. Introducing a dedicated "Clean List" option would make this process more efficient and user-friendly.

**Comment by lordwelch** [comment]
There is a select-all option, you can also press Ctrl/Cmd+A to select all you can then press Ctrl/CMD+X to remove all selected comics. A dedicated button will not be added
