### ISSUE TITLE
[QUESTION] Code Usage in another Project and License

### ISSUE THREAD

**Issue by WorldTeacher** [comictagger/comictagger#479]
Hey there, 

I'm currently creating an application that tags Series based on ComicVine, Mangadex, AniList etc. and send that data to the respective Comic/Manga Server (currently only Komga, as that is what I use to host my Manga and Comic).
To do that, I am currently writing the auto series detection, but would like to offer a GUI as well (as some series might need manual editing / detection) and was wondering if I could use your .ui files, change the layout to my requirements and use them to create the GUI. 

I'm no expert regarding licenses, so I'm not sure on how to proceed. 
Currently, my Project is not released, but once it is in a usable state, I am planning to release it under the MIT License.
The only parts I'd use of ComicTagger would be some of the .ui files like taggerwindow.ui and change & remove some parts.

Would this be acceptable, or should I create the .ui files myself, and if I were allowed to use the files, how should / do I credit this?

Any answer is appreciated, thanks in advance.

Sincerely,
WorldTeacher

**Comment by lordwelch** [comment]
@WorldTeacher
Yes, I have no issue with it. Putting a note in your README or similar file that they are modified from ComicTagger under the Apache 2.0 License should be sufficient.

**Comment by WorldTeacher** [comment]
@lordwelch 

Thank you for the reply. I will do the following:
- add a notice to the README
- put the Apache License inside the ui folder
- add a disclaimer to all files taken from this repo
