### ISSUE TITLE
Pillow version conflict?

### ISSUE THREAD

**Issue by musictrivianut** [comictagger/comictagger#497]
In trying to keep my system up to date, I use pip-review to check for new versions of python software.  When it checks things, I get the following message:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
comictagger 1.6.0a5.dev38 requires pillow<10,>=9.1.0, but you have pillow 10.0.0 which is incompatible.

I have been getting a LOT of crashes/core dumps when using the comictagger gui for a few weeks now.

Is anyone else running into this?  If so, is a fix in the works or is there another solution that I just don't know about?  My python knowledge is minimal, so please be gentle :-)

Thank you!!

**Comment by lordwelch** [comment]
As it says you have pillow 10. pillow 10 dropped support for Qt5

**Comment by musictrivianut** [comment]
Aha, was not aware of the dropped support (see message about minimal knowledge).

Okay, off to see if I can install both versions or revert and hold. Or something.

Thanks!
