### ISSUE TITLE
Auto-Tag on the CLI doesn't write series name

### ISSUE THREAD

**Issue by eduo** [comictagger/comictagger#498]
Hello.

I updated after a few years and using the CLI I noticed an issue in the latest alpha that I don't see reported.

When I do a search the series name is not written to tags. In the GUI it is:

```
comictagger --comicvine-key XXX -w --ignore-leading-numbers-in-filename --save-on-low-confidence -v -s -t CR -1 -f -o Supreme\ #022\ -\ God\ War\,\ Part\ 2\ of\ 2\ \(1994\).cbz 
2023-08-14T22:09:51 | comictagger | INFO | ComicTagger Version: 1.6.0a4 running on: Darwin PyInstaller: Yes
Going to search for:
	Series: Supreme
	Issue:  22
	Count:  2
	Year:   1994
	Month:  12
Searching for Supreme #22 ...
2023-08-14T22:09:51 | comictalker.talkers.comicvine | INFO | Comic Vine searching: supreme
Searching in 1 series
Found 1 series that have an issue #22 from 1994
Examining covers for  ID: 4938 Supreme (1992) ...[ 30 ] --> 30
Compared to covers in 1 issue(s):[30]
Very weak scores for the cover. Analyzing alternate pages and covers...
Examining alternate covers for ID: 4938 Supreme (1992) ...[0 alt. covers][ 304 ]--->4

Success in secondary/alternate cover matching!
[Second round cover matching: best score = {best_score}]
--------------------------------------------------------------------------
-----> Supreme (1992) #22 God War, Part 2 of 2 (12/1994) -- score: 4
--------------------------------------------------------------------------
Save complete.
2023-08-14T22:09:52 | comictaggerlib.cli | INFO | Save complete.

Successful matches:
------------------
./Supreme #022 - God War, Part 2 of 2 (1994).cbz
 
```

This is the result:

<img width="1363" alt="image" src="https://github.com/comictagger/comictagger/assets/154630/f2119e99-3181-42e9-b3be-b62faae9a224">

If I do the same search via the GUI (removing tags first, otherwise it fails because if the series name is blank it doesn't fall back to the filename, which might be considered a bug too) if tags properly.

Nonetheless, I think in reality it's never writing the title from the search, just leaving the field empty because if I tick the "Overwrite" checkbox in the GUI, it will blank the Title field like the CLI. The "Overwrite" flag in the CLI makes no difference though. Same thing happens if I check the box to "Clear Form before Import comicvine data". 

In this Alpha, I just don't seem to be getting titles and publishers stored consistently.

I have gone back to version 1.5.5 and this is working correctly. I can try and trace in which Alpha this broke, if no better alternative.

**Comment by lordwelch** [comment]
If you pass `--no-clear-metadata` it will save the series, mostly by accident though. There was a caching issue which has since been fixed that wiped the series name when saving. The next alpha release will be fixed
