### ISSUE TITLE
Series Start Date is not retrieved on auto-tag but it is on auto-identify

### ISSUE THREAD

**Issue by eduo** [comictagger/comictagger#499]
What the title says. 

For a specific title if I do auto-tag the issue may be found but the series start is not filled out (I have it mapped to show in the volume, as no field seems to be present for it).

Possible related (reported in issue #498 ) where auto-tagging series in the CLI blanks the name field.

This is for ** v1.6.0a4**

**Comment by eduo** [comment]
I have also noticed I'm not always getting a publisher. I'm starting to believe the issue must be with my config. I haven't found a pattern, since for the same issue a new search will not overwrite it either.

**Comment by lordwelch** [comment]
This is the same issue as #498 1.6.0a2 1.6.0a3 and 1.6.0a4 all have this issue I suggest waiting until 1.6.0a5 or going back to 1.5.5 as the last main release
