### ISSUE TITLE
Enhancement - Save on close

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#50]
_From [xylamic](https://code.google.com/u/xylamic/) on May 04, 2014 15:00:35_

What version of ComicTagger are you using? 1.1.14-beta On what operating system (Mac, Linux, Windows)? What version? Ubuntu Linux GUI or command line? GUI What steps will reproduce the problem? 1. Open ComicTagger
2. Edit comic information
3. Close ComicTagger
4. You are told you will lose your changes What is the expected output? What do you see instead? I'd like the option to save on close all changes that have been made. Please provide any additional information below.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=50_

**Comment by lordwelch** [comment]
This is now implemented.
