### ISSUE TITLE
Support for Grand Comics Database (GCD / Comics.org) Talker

### ISSUE THREAD

**Issue by DieselTech** [comictagger/comictagger#506]
I know this is a big ask but with wanting to move ComicTagger to support more datasets than just CV, I think having a local DB option would be very beneficial going forward. That way the program wouldn't even rely on having an internet connection and people will be able to freely tag their files no matter the state of commercial services or internet status. 

The database dump can be acquired from: https://www.comics.org/download/

Their license model is CC BY 3.0

https://docs.comics.org/wiki/GCD_Board_Votes_-_2009#Data_License_and_proper_credit_in_derived_works

**Comment by mizaki** [comment]
Already ahead of you https://github.com/GrandComicsDatabase/gcd-django/discussions/608
Using a sqlite version would only require people to download the file and point to it. I don't see many people wanting to import to a MySQL/Maria DB and query that. Of course, the queries would be the same so it wouldn't be too difficult to make one from the sqlite version if there is enough interest.

I have a version that is pre-alpha that I will try to put up soon if people want to test it.

**Comment by beville** [comment]
That sounds pretty cool. How well does that 4.1 GB SQLite file compress? 

Once the new talker plug-in is broadly available, I wonder if the demand for people wanting to download the entire database will be more than the folks at GCD might expect.

I don’t really know much about file hosting services, but I also wonder if they’d be OK with periodic dumps going onto a mirror or a torrent possibly.  Maybe it won’t be an issue at all, regardless.

**Comment by DieselTech** [comment]
> That sounds pretty cool. How well does that 4.1 GB SQLite file compress? 

I was able to get it to 1GB using standard zip compression. Using something more advanced will likely get it smaller. I can test different options later tonight.

**Comment by lordwelch** [comment]
Brotli has some of the best compression I've seen and all major browsers support transparent decompression of it so I can stick it on a webserver and host it, I recently got a fiber connection at home so I should be able to allocate a gig upload to it. Making a torrent with it as a webseed should make it available even if my network goes down

**Comment by beville** [comment]
Just curious: Does the GCD DB dump include the cover image blobs (even as tiny thumbnails) that could be used for auto-tagging?

**Comment by lordwelch** [comment]
No, they do not. https://docs.comics.org/wiki/General_FAQ#I_would_like_to_use_data_and/or_cover_scans_from_the_GCD._Who_owns_the_copyright_to_these_items?

**Comment by mizaki** [comment]
No. There is a whole thing looking back in [gcd-tech](https://groups.google.com/g/gcd-tech/c/zsc6II5w-ms/m/ymCr3LiRAQAJ) which makes sense in terms of distribution but doesn't make a lot of sense to me from a copyright perspective to not even include the URLs to the images in the dump but there it is. I have a workaround in place which should be allowed by them but I'll run it past them to be sure.

Metron now has a p_hash of the covers so asking if they could do the same would get around the issue. (I've not gotten around to it yet.)

I'll try and put the pre-alpha version up before the weekend.

**Comment by beville** [comment]
Thanks.  It will be interesting to see what their response to that idea is.  Maybe outside of their core mission, but who knows?

**Comment by mizaki** [comment]
If it's a few CPU cycles on adding an image hash versus people scraping the image... Whether it would actually remove much scraping, probably not.

**Comment by mizaki** [comment]
As promised! Still a few things to do and what data to use/not use. I created the queries from looking through the tables so if you can make them better (had to create an index for the issue lists). Create any issues/requests on the repo https://github.com/mizaki/comictagger-gcd-talker

**Comment by lordwelch** [comment]
As of [1.6.0-alpha.12] the GCD sqlite export is now supported in comictagger

[1.6.0-alpha.12]: https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.12
