### ISSUE TITLE
Issue cover image in the GUI issue list becomes incorrect after tagging issue

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#507]
With latest git (using CV and Metron) it appears that after pulling the full information to tag an issue, when going back to the issue list the image is incorrect.

Steps to replicate:
- Clear DB
- Select the first issue of a series to tag a file (Doesn't have to be first but makes it easier)
- Re-enter the issue list for the same series and the cover images are now incorrect

It appears the covers are being rotated. Issue 1 cover becomes 2, 2 becomes 3, etc. and the last one becomes 1.

https://github.com/comictagger/comictagger/assets/1141189/ae7f9b58-88b5-4a8e-b78a-ea66bf6edb1d

It doesn't matter if they are cached first or not.

**Comment by lordwelch** [comment]
The series window has the same issue, I'll have a fix soon
