### ISSUE TITLE
Feature Request:  Select Online Source from CLI or main GUI

### ISSUE THREAD

**Issue by beville** [comictagger/comictagger#508]
I was just playing with the new Metron plugin and while trying to find tags for particular book in both CV and Metron, it was a bit clunky to have to go to the settings dialog to change between sources.  Maybe offering a drop down selector on the main window would make that use-case easier?

Also, adding a simple cli option along the lines of "--search-source" would be cool.  (And maybe "--list-search-sources" too)

**Comment by lordwelch** [comment]
That's a good idea I haven't used any other sources much myself yet, so the feedback is appreciated!
There is a `--source` option so you can select it on the CLI, but I'll add an option to list sources as well

**Comment by beville** [comment]
Ah, oops! I don't know how I missed the "--source" item.  I looked, but but I guess not hard enough. Sorry :-)
