### ISSUE TITLE
Issue and series window do not update with new information

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#512]
When a full series or issue call is made via `current_item_changed`, only a limited number of fields are updated.

Series updates image and desc.
Issues updates issue number, image and desc.

Also, issue only displays month. Year is over written by month looking at it.

**Comment by lordwelch** [comment]
The table itself is never updated, those rows are only created when the window is created. The full data is updated internally you just won't see it until you re-open the window.
The fields that you do see update are updated on every change even without the network call.

I'll push out a fix for the date issue in a bit.

**Comment by mizaki** [comment]
Related, it causes a delay when loading the extra data so switching the cursor to "busy" should be done as well.

I'll try and do a PR for both.
