### ISSUE TITLE
Talkers should not require a key and/or URL to generate the GUI settings

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#515]
In commit 05e6eaf88e12c0500b4ecb6ea946daf08979ed89 it assumes all talkers should have a key and URL field. This is not true for a few talkers with regards to the key (MangaDex, MangaUpdates, etc.) and while the URL field may be preferred, if using a library or a file, the URL is not required.

**Comment by lordwelch** [comment]
All talkers have those fields created for them. If they ever don't exist that is a bug here https://github.com/comictagger/comictagger/blob/3ade47a7e095b1ebb1630a633b62a99706a7f310/comictaggerlib/ctsettings/plugin.py#L39-L61

There are two issues generating the settings that will be fixed shortly
