### ISSUE TITLE
AppImage Crashing with Error Window During Online Search

### ISSUE THREAD

**Issue by FrenchToucan** [comictagger/comictagger#516]
After clicking "Search Online", somtimes I get a crash with the following error window:

Oops. An unexpected error occurred:
AttributeError: 'SeriesSelectionWindow' object has no attribute 'progdialog'

File "comictaggerlib/seriesselectionwindow.py", line 399, in search_complete

This happens when using the app imagine. Tested with 1.6.0-alpha4 and alpha5.

Update: Just happened with the executable for Linux too. Error in the terminal was:
  File "comictaggerlib/seriesselectionwindow.py", line 399, in search_complete
AttributeError: 'SeriesSelectionWindow' object has no attribute 'progdialog'
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate

**Comment by lordwelch** [comment]
It looks like PyInstaller isn't collecting the openssl libraries correctly, your best bet on linux is to install it via pip, or if you are on Archlinux use the AUR. I recommend using pipx so that it doesn't interfere with anything else.
Fedora: sudo dnf install pipx
Ubuntu/Debian: sudo apt-get install pipx

pipx install "comictagger[all]==1.6.0a5"

**Comment by FrenchToucan** [comment]
> It looks like PyInstaller isn't collecting the openssl libraries correctly, your best bet on linux is to install it via pip, or if you are on Archlinux use the AUR. I recommend using pipx so that it doesn't interfere with anything else. Fedora: sudo dnf install pipx Ubuntu/Debian: sudo apt-get install pipx
> 
> pipx install "comictagger[all]==1.6.0a5"

Build from AUR causes build errors on a couple of dependendencies.

pipx install "comictagger[all]==1.6.0a5" seemed to work but I got the same crash as in the original post.

**Comment by FrenchToucan** [comment]
Getting the same crash with it installed through the pipx method.

AUR has build errors for a couple dependencies so I couldn't get it installed that way.

**Comment by lordwelch** [comment]
Looks like it's an Arch Linux issue. https://github.com/nodegit/nodegit/issues/1967#issuecomment-1429957927 seems that they removed the function from the latest openssl build they are using

**Comment by FrenchToucan** [comment]
Doh! All right, thanks for getting to the bottom of that.
