### ISSUE TITLE
"ComicTagger" is damaged and can't be opened. 

### ISSUE THREAD

**Issue by howdy-im-david** [comictagger/comictagger#520]
Latest posted release, Alpha 5, does not open on macOS Sonoma 14.0. Issue does not occur on Alpha 4. 

[ComicTagger-1.6.0a5-osx-11.7.8-x86_64.app.zip](https://github.com/comictagger/comictagger/releases/download/1.6.0-alpha.5/ComicTagger-1.6.0a5-osx-11.7.8-x86_64.app.zip)
<img width="261" alt="Screenshot 2023-09-06 at 2 02 32 PM" src="https://github.com/comictagger/comictagger/assets/104217810/73cd9080-3c53-4655-9d48-15afa2408972">

**Comment by lordwelch** [comment]
Please see https://github.com/comictagger/comictagger/wiki/Opening-3rd-Party-Apps-on-MacOS

**Comment by howdy-im-david** [comment]
Thanks for the link, but unfortunately that isn't the issue. I know how to open 3rd party apps and did so with the previous build. That error message also looks different: 
<img width="258" alt="Screenshot 2023-09-06 at 2 22 09 PM" src="https://github.com/comictagger/comictagger/assets/104217810/430589ca-fee9-41bc-a952-55fd5db0780d">

The Alpha 5 build is corrupted for whatever reason. Please see the screenshot in my original post.

**Comment by lordwelch** [comment]
No apple is just being an asshole.
macOS is sometimes extremely picky about downloaded programs and doesn't allow you to open them directly anymore.
go to the .app downloaded copy (cmd+c) open up terminal and type this in
```bash
xattr -d com.apple.quarantine <paste here>
```
example:
```bash
xattr -d com.apple.quarantine /Applications/ComicTagger.app
```

**Comment by howdy-im-david** [comment]
*facepalm* I haven't had to do that command in enough years that I completely forgot it existed. Thank you for the additional notes. It does appear to open correctly now.

**Comment by lordwelch** [comment]
Apple has made some questionable decisions. Windows at least tells you that it's blocked instead of saying it's corrupt (assuming you even turn on that option on Windows)
