### ISSUE TITLE
Auto-tag OVERWRITE

### ISSUE THREAD

**Issue by protofolius** [comictagger/comictagger#524]
Using version 1.6.0a5 , auto tag function overwrites fields even when overwrite option is unticked in the following cases:

- the system finds a successful match on comicvine , it overwrites existing metadata (I spotted this cause it changed capital/small letters in the title and in some instances even series name . I had capital letters and comicvine used small letters , the metatag changed into small letters)
- the system THINKS it has found a match . yet the match is wrong . It still changes/overwrites the correct title,pblisher ..  to something completely different
- no CR metadata exists yet , only form data from the filename parser . it overwrites the already existing form data .
- it proposes a match , asks to manually accept it . when you accept it overwrites the already existing metadata

**Comment by lordwelch** [comment]
The overwrite option specifically refers to saving tags. If there are already CR tags saved in the comic CT will not save CR tags over them by default it does not refer to individual fields in the metadata

**Comment by lordwelch** [comment]
There are multiple options such as '--overwrite' and '--clear-metadata' which make this unnecessarily complicated. I plan to address this before the next full release, probably won't be addressed in the next alpha.

**Comment by lordwelch** [comment]
Now there are only two options and they should have a sufficiently clear help message.
```plain
  --overwrite, --no-overwrite
                        Apply metadata to already tagged archives, otherwise skips archives with existing metadata (relevant for -s or -c).
  --clear-metadata, --no-clear-metadata
                        Clears all existing metadata during import, default is to merge metadata.
                        May be used in conjunction with -o, -f and -m.
```

different options for merging metadata is being added in #598 by @mizaki

**Comment by lordwelch** [comment]
Related to #658

The current options are now:
```plain
  --clear-tags, --no-clear-tags
                        Clears all existing tags during import, default is to merge tags.
                        May be used in conjunction with -o, -f and -m.
                        default: False

  --skip-existing-tags, --no-skip-existing-tags
                        Skip archives that already have tags specified with -t,
                        otherwise merges new tags with existing tags (relevant for -s or -c).
                        default: True

  --tag-merge {overlay,add_missing}
                        How to merge fields when reading enabled tags (CR, CBL, etc.) See -t, --tags-read default: overlay
  --tag-merge-lists, --no-tag-merge-lists
                        Merge lists when reading enabled tags (genres, characters, etc.) default: True
  --metadata-merge {overlay,add_missing}
                        How to merge fields when downloading new metadata (CV, Metron, GCD, etc.) default: overlay
  --metadata-merge-lists, --no-metadata-merge-lists
                        Merge lists when downloading new metadata (genres, characters, etc.) default: True
```
