### ISSUE TITLE
Doesn't write valid ComicInfo.xml

### ISSUE THREAD

**Issue by bpepple** [comictagger/comictagger#525]
I was testing out the Metron plugin for ComicTagger this afternoon, and noticed CT doesn't write valid ComicInfo v1 or v2. Not sure if you were aware or not, so figured I'd open a bug on it.

```
bpepple@frodo ~/Git/metron-tagger (main) $ metron-tagger --validate ~/Storage/Downloads/today/dc/Silver\ Surfer\ Rebirth\ -\ Legacy\ v1\ \#001\ \(2023\).cbz 

Validating ComicInfo:
---------------------
'Silver Surfer Rebirth - Legacy v1 #001 (2023).cbz' is not valid
```

I tested this with the latest dev branch (as of submitting this bug) commit https://github.com/comictagger/comictagger/commit/f72c0c82243e9e4edd43ddc19068b63a09963397

The ComicInfo (changed the extension so the file could be attached):
[ComicInfo.txt](https://github.com/comictagger/comictagger/files/12563378/ComicInfo.txt)

**Comment by lordwelch** [comment]
Can you explain? I don't see anything that is obviously wrong. I don't really care for trusting the output of an arbitrary tool with no explanation or reason as to why it's invalid

**Comment by lordwelch** [comment]
The schema's are incorrect. See https://github.com/anansi-project/comicinfo/issues/10

**Comment by bpepple** [comment]
Well, that's debatable since it sorta defeats the purpose of schema if it can't be used to **actually** validate an xml, but that's really beside the point,  you will need to handle mapping the **AgeRating** metadata from Metron to make it compatible with the Anansi projects, since the two projects use different enumerations.  Something like this when mapping the metadata should fix that:

```
        def map_ratings(rating: str) -> str:
            age_rating = rating.lower()
            if age_rating in {"everyone", "cca"}:
                return "Everyone"
            if age_rating in {"teen", "teen plus"}:
                return "Teen"
            return "Mature 17+" if age_rating == "mature" else "Unknown"
```

**Comment by lordwelch** [comment]
Age rating is a free text field. https://web.archive.org/web/20161229183519/http://comicrack.cyolito.com:80/forum/7-general/709-using-comicinfo-xml-in-other-viewers#852

**Comment by lordwelch** [comment]
I don't believe ComicRack ever produced files that would actually pass validation

**Comment by bpepple** [comment]
I guess my thinking is if I'm writing out the ComicInfo, I want to make sure it's actually valid and can be used by any consumer that wants to (which I thought was the general mission statement for the Anansi Project).

Now, not all projects care if it's valid or not, but I'm aware of at least one project that does validate before reading the file (which makes sense since they worked on the Linux Desktop & fdo).

Anyway, just thought I'd bring this to your attention.

**Comment by lordwelch** [comment]
What project is that? I haven't noticed any projects that actually validated it before

**Comment by bpepple** [comment]
It hasn't been released yet (I think the code is sitting on the Fedora infra), a bunch of Fedora/GNOME folks have been working on it in their free time.
