### ISSUE TITLE
Complicated Parser : Karl May

### ISSUE THREAD

**Issue by protofolius** [comictagger/comictagger#542]
For some reason the complicated parser trips on all comics from Karl May .

filename  `Karl May #001 Old Shatterhand.cbr`
It parses as
Series `Karl`
Title `May Old Shatterhand`
Issue `1`

While it should be
Series `Karl May`
Title `Old Shatterhand`

**Comment by lordwelch** [comment]
That's because May is also the name of a month, but that shouldn't be happening
