### ISSUE TITLE
--complicated-parser (both CLI and GUI) issue field containing letters and digits

### ISSUE THREAD

**Issue by protofolius** [comictagger/comictagger#543]
### Discussed in https://github.com/comictagger/comictagger/discussions/511

<div type='discussions-op-text'>

<sup>Originally posted by **protofolius** September  4, 2023</sup>

My filestructure is as follows : {series} #{issue} {title} ({year})

Using the simple parser , the {series} , {issue} and {year} perfectly get inputted into the proper fields (both GUI and CLI) .
But I need to use the complicated parser in order to get the very important {title} part too .

The complicated parser seems to handle an {issue} part with only numbers just fine .
However I have used letters in my filenames for "special" editions .
A few {issue} examples -->

#P01 pocket editions
#F01 family book editions
#S01 special editions
#X01 X-rated editions

with obviously the last 2 digits incrementing the more issues the series has .

**The complicated parser** is unable to handle these imports properly .
It imports everything in the Series field , detaches the # from the issue part and attaches it to the first series part . Like this -->   
{series}# {issue} {title} .  The ({year}) field gets imported correctly .
So the Series field gets completely unusable data inside , and {issue} {title} field stay empty . year field gets populated .

As an example 
`Seriesname #S01 This is the title (1950).cbr`

Gets imported by the complicated parser as

Series field `Seriesname# S01 This is the title`
Title field stays empty
Year field `1950`

</div>

**Comment by lordwelch** [comment]
fixed in #518
