### ISSUE TITLE
Dialogue boxes crave attention

### ISSUE THREAD

**Issue by ScuttleSE** [comictagger/comictagger#546]
The "Adding files" progress bar forces itself front and center no matter what I do with it. If I am importing a few thousand files, it is really annoying  being forced to have that windows on top of everything and in the middle of the screen

**Comment by lordwelch** [comment]
Can you try out #552 and let me know if there is anything else that you think should be changed?
https://github.com/comictagger/comictagger/wiki/downloading-packages-from-pull-requests
