### ISSUE TITLE
CBZ with Archive comment inside makes comictagger crash when adding the file

### ISSUE THREAD

**Issue by protofolius** [comictagger/comictagger#548]
Whenever a CBZ file has an archive comment inside , dragging the CBZ inside comictagger immediately gives a pop up error and makes the program crash .

Only from the moment the archive comment is being removed from the CBZ prior to loading it into comictagger , the CBZ can be loaded .

See screenshot for the error .

![CBZ Comment](https://github.com/comictagger/comictagger/assets/30254488/0c215c8d-4cd0-42ee-b51e-e68eb8cd6498)

**Comment by lordwelch** [comment]
Can you give this PR a try? https://github.com/comictagger/comictagger/pull/550
https://github.com/comictagger/comictagger/wiki/downloading-packages-from-pull-requests

**Comment by protofolius** [comment]
That PR version seems to fix it indeed .

**Comment by protofolius** [comment]
fixed
