### ISSUE TITLE
Understanding releases

### ISSUE THREAD

**Issue by nodupe** [comictagger/comictagger#557]
Hi,
First of all thank you for this software! It is a godsend!

I am building comictagger on NixOs, and started the process for having it available on nixpkgs unstable - at least for linux.

Notice that my points are mostly cosmetics.

I've managed to build comictagger on tag 1.5.5, but when I run the app, it gives me this message:

"New version (1.5.5: Scanlan Shorthalt) available!
(You are currently running 0.1.dev1)"

I've used the commit hash on git, but the message stills hold. Not sure if this is the expected behaviour - since I am using the develop branch.

When I build the latest pre release, I do not receive the pop up, but the about shows the same version, and still show the year 2022:
"ComicTagger v0.1.dev1
©2014-2022 ComicTagger Devs"

By the way, I've noticed that the master branch is not receiving updates since 2019. Is there a reason why the new releases are not merged on master?

Note that I am not a developer, so I would not know where to touch to have those "fixes" done.

**Comment by lordwelch** [comment]
Use the binary release ComicTagger is released on PyPi https://pypi.org/project/comictagger/ https://nixos.wiki/wiki/Packaging/Python#install_binary_release

**Comment by nodupe** [comment]
I've manage to do it without the use of binary release - compiling from source, but I see your point.
I'll try your suggestion and check if a PR with binary will be accepted on upstream nixpkgs.
Thanks
