### ISSUE TITLE
Can't save tags, i get an error:

### ISSUE THREAD

**Issue by d0ntlkdwn** [comictagger/comictagger#562]
after i auto-identify when i try to save tags i get an error:

(2023-10-31 01:32:07,089 | comicapi.comicarchive | ERROR | c:\users\oomfield\appdata\local\programs\python\python39\lib\site-packages\comicapi\archivers\zip.py:39: Error saving CBI! for C:\Berserk v41 (2022) (Digital) (LuCaZ).cbz: [Errno 13] Permission denied: 'C:\\Berserk v41 (2022) (Digital) (LuCaZ).cbz)
![Screenshot 2023-10-31 011852](https://github.com/comictagger/comictagger/assets/149418755/236badf5-aa71-4c1b-9920-5cfe5a1b24c9)
![Screenshot 2023-10-31 013421](https://github.com/comictagger/comictagger/assets/149418755/65b463d7-5388-4526-83b7-8109169725aa)

if there is anyway to fix it let me know

**Comment by lordwelch** [comment]
Don't put your comics in the root put them in your documents or downloads

**Comment by d0ntlkdwn** [comment]
Thanks for the help, Though i get the same problem even when i change it to downloads/documents

![Screenshot 2023-10-31 123746](https://github.com/comictagger/comictagger/assets/149418755/72ac5831-db90-464c-b8f0-7639b5d8542b)

if anyone can help will be appreciated cause ive been trying to fix it for a whole week

**Comment by d0ntlkdwn** [comment]
Ive fixed it finally by: downloading comicrack,
then converted all the (comics/mangas .cbz) files to .cbz through the comicrack program, which when converted it puts an .xml file in the comic .cbz file which then allows you to change the metadata through any application like MangaTagger Kcc etc...
after that i could change the metadata in any of the comic that ive converted through comicrack.
