### ISSUE TITLE
Update existing comicinfo.xml

### ISSUE THREAD

**Issue by EckisWelt** [comictagger/comictagger#565]
Maybe a dumb question, but I wasn't sure. With the parameter -p I can print out existing tags. With -f I can parse the file name to lookup comic informations and with -m I'm able to direct comictagger to look for something specific.

I have a lot of comics where the data is incomplete. I would like to update this on comicvine and get an updated comicinfo.xml into my comics. How can I accomplish this without parsing again the file name or extracting with -p the content and use the --id flag to request it specifically for that file?

Maybe a parameter -u --update would be a great enhancement.

**Comment by lordwelch** [comment]
So unless ComicTagger can't parse the filename or you need a specific functionality you can just run this command
```sh
comictagger --save --type CR --parse-filename --no-overwrite --online --recurse .
```
This uses the "save" command with ComicRack tags, parse the filename, skip comics that already have a comicinfo.xml, retrieve metadata online and to recursively search all files in the current directory

The `-p` or `--print` flag is just to view the information in the file, if it is a part of your process for tagging comics it should be the last part to verify that they got tagged how you want them to.
The `-f` or `--parse-filename` flag should pretty much always be used, unless you know that it causes issues with a particular set of comics, any data stored as tags takes priority over data parsed from the filename.
The `-m` or `--metadata` overrides any other information obtained before doing an online search.

The `--id` flag is the last resort if ComicTagger can't find the issue, you can use it to tag a specific comic, but 80% of the time comictagger should just be able to search using the filename and find it.
`comictagger -s -t cr --id 1234 comic.cbz`

See the wiki for more info https://github.com/comictagger/comictagger/wiki
