### ISSUE TITLE
AVIF Support

### ISSUE THREAD

**Issue by 5h4k3** [comictagger/comictagger#569]
Hello!

I used to be an happy ComicTagger user, back in the days when my comic library was filled with JPG/PNG CBZ files…

But I've started converting all of them in AVIF a few month ago and now, I can't use ComicTagger anymore… Sadness…

I still can of course, use ComicRack and its incredible scrappers (and i do), but as the software is no longer "officially" maintained, I think it's a matter of time before I start having compatibility issues...

I was wondering if it would be possible to add, even partially, support for AVIF format?

By partial, I mean, if it is not capable of rendering the graphic part of AVIF files (like parse and preview), I can live with that.

I just want to be able to handle XML related stuff, namely working on the comicinfo…

Anyways, thanks for your time and your consideration! 
Have a nice day!

**Comment by lordwelch** [comment]
What is AVIF? I've never heard of it

**Comment by mizaki** [comment]
> What is AVIF? I've never heard of it

It's what Google is pushing instead of JPEG XL. https://tonisagrista.com/blog/2023/jpegxl-vs-avif/

**Comment by mizaki** [comment]
https://github.com/python-pillow/Pillow/pull/5201

**Comment by lordwelch** [comment]
I've added the plugin from that PR as an optional dependency in d37c7a680df45a7dcd2a57db72594010d0a99719. The next alpha will have it

**Comment by 5h4k3** [comment]
Awesome ! thank you !
