### ISSUE TITLE
Wild Card for batch editing in CLI is not working for Windows

### ISSUE THREAD

**Issue by Deathbot64** [comictagger/comictagger#571]
When I try to use *.cbz or *.cbr it will not find any files but I can make edits using the full file name. But I want to batch edit, is there a problem with how I am using it or a problem with the problem.

comictagger -s -t cr -m "series=Chronicles of the Avatar" *.cbz will not work

comictagger -s -t cr -m "series=Chronicles of the Avatar" "Dawn of Yangchen, The - F.C Yee.cbz" works

**Comment by lordwelch** [comment]
File globbing is provided by the shell on macOS and Linux. Because Windows sucks there is a `-g` option to enable glob expansion. You can also enable recursion with `-R` and just give it the name of the folder
