### ISSUE TITLE
Rename seems broken in 1.5.5

### ISSUE THREAD

**Issue by gramster** [comictagger/comictagger#574]
If I try rename, the previewed new name just shows the template.

**Comment by lordwelch** [comment]
It sounds like you are using an invalid template. The old template syntax was removed in [1.4.4](https://github.com/comictagger/comictagger/releases/tag/1.4.4) the wiki has documentation for both the old and new syntax https://github.com/comictagger/comictagger/wiki/UserGuide#rename

Also if you go to the rename tab in settings you can see a live preview of the rename template

I've verified that renaming files works on 1.5.5
