### ISSUE TITLE
macOS Hombrew -> rar -> wrong Syntax 

### ISSUE THREAD

**Issue by tocotronaut** [comictagger/comictagger#584]
![Bildschirmfoto 2023-12-28 um 14 31 51](https://github.com/comictagger/comictagger/assets/67421967/c2fc5233-5344-4a50-8115-d1cfb8e9a42e)

**Comment by tocotronaut** [comment]
Hello. 

The Program says "we need rar" and its easy to install via homebrew...
Then it says to install rar: _**brew install caskroom/cask/rar**_ 
This gives an Error and says you need to use: **brew install homebrew/cask/rar** 

> Error: caskroom/cask was moved. Tap homebrew/cask instead.
> 
> ➜  ~ brew install homebrew/cask/rar 
> ==> Downloading https://www.rarlab.com/rar/rarmacos-x64-624.tar.gz
> ######################################################################### 100.0%
> ==> Installing Cask rar
> ==> Moving Generic Artifact 'default.sfx' to '/usr/local/lib/default.sfx'
> ==> Moving Generic Artifact 'rarfiles.lst' to '/usr/local/etc/rarfiles.lst'
> ==> Linking Binary 'rar' to '/usr/local/bin/rar'
> ==> Linking Binary 'unrar' to '/usr/local/bin/unrar'
> 🍺  rar was successfully installed!
> ➜  ~ 

So the Correct Syntax is: brew install homebrew/cask/rar

**Comment by tocotronaut** [comment]
i installed comictagger on another machine.

**brew install rar** is enough to install rar on macOS :)

but you still have to Add: /usr/local/bin/rar as Path in ComicTagger Preferences...

btw: in actual Alpha comictagger does'nt allow to set the path directly. You have to open it in Finder - and there the /usr folder does'nt show up... so its not easy to get rar working without an good amount of knowledge in macOS sytem internals...

Maybe you can set `/usr/local/bin/rar` as default path...

**Comment by BenRoe** [comment]
@tocotronaut that helps, but unfortunately the directory are not saved. I use the latest release (1.6.0-alpha.10).
