### ISSUE TITLE
[1.6.0a10]Tag Save Operation Seemed to Fail

### ISSUE THREAD

**Issue by AlanDunaway** [comictagger/comictagger#586]
Getting the message "Tag Save Operation Seemed to Fail" whenever I try to save comic info to individual issues.

App version: 1.6.0a10
Windows 10
WinRAR is installed, and ComicTagger knows where it is.

**Comment by lordwelch** [comment]
I need the log in order to figure out what is wrong. You can press Ctrl+Shift+L to bring up the log for the current session and it has a link to the folder for the 9 previous sessions (on windows 11 the link doesn't open anything because Microsoft sucks, but you can right click and copy it).
