### ISSUE TITLE
Removing credits from CLI

### ISSUE THREAD

**Issue by atimeforwolves** [comictagger/comictagger#587]
When using ComicTagger with Comic Vine as metadata source, I am getting duplicates in credits with one having a number in []. This ends up bogging down my view through Kavita as when viewing an entire volume it populates all unique entries in the credits. As such, I'd rather just remove the credit entries entirely. Is there a way to do this from the cli? I'm not having any luck with anything I try after -m

Ex:
Writer: John Broome
Writer: John Broome [48152]

edit: regarding Comic Info XML (cix)

**Comment by lordwelch** [comment]
`-m credits=` should work

**Comment by atimeforwolves** [comment]
> `-m credits=` should work

Thank you! I had tried this earlier but maybe I had used credit instead of credits and didn't realize.

**Comment by atimeforwolves** [comment]
It looks like even though it did not error out, the credits are still there after checking: 
![image](https://github.com/comictagger/comictagger/assets/105068114/6e1eb176-badd-4f87-929a-a4a9ac341427)

For clarity, I have been using this batch script, which has been working for all other metatags:
for /r %%A IN (\*.cb*) do ( "full\path\to\comictagger.exe" -s -t cix -m "credits=" "%%~A") pause

**Comment by atimeforwolves** [comment]
It looks like this is how it's being assigned, but I'm not sure on the syntax:
```
    def overlay_credits(self, new_credits: list[Credit]) -> None:
        for c in new_credits:
            primary = bool("primary" in c and c["primary"])

            # Remove credit role if person is blank
            if c["person"] == "":
                for r in reversed(self.credits):
                    if r["role"].casefold() == c["role"].casefold():
                        self.credits.remove(r)
            # otherwise, add it!
            else:
                self.add_credit(c["person"], c["role"], primary)
```
Doesn't seem like it's able to handle removing credit metadata?
