### ISSUE TITLE
Winget support

### ISSUE THREAD

**Issue by nado** [comictagger/comictagger#589]
Hi,

Seeing that choco install are supported, would you consider submitting a request for supporting winget?

Microsoft doc: https://learn.microsoft.com/en-us/windows/package-manager/package/

Thanks for your work

**Comment by lordwelch** [comment]
I couldn't figure out their system. They've made it far too complicated, anyone that wants too can feel free to submit it themselves if they figure it out

**Comment by Sn1cket** [comment]
Hi,

I would like to see ComicTagger in the winget registries. So I created the necessary manifest files and a demo pull request to my own winget-pkgs fork.
https://github.com/Sn1cket/winget-pkgs/pull/1

@lordwelch You could look at the files and check if some infos provided in the manifest files should be changed.
If everything is fine I would create a PR to the real winget-pkgs repository and also add the latest 1.6.x-beta release.

I'm looking into updating the package in winget-pkgs automatically with Github Actions but I'm not quite there yet.

**Comment by lordwelch** [comment]
@Sn1cket it's fine with me

**Comment by Sn1cket** [comment]
The ComicTagger versions v1.5.5 and 1.6.0-beta.2 are now available on winget.
It can be installed with `winget install ComicTagger.ComicTagger`
