### ISSUE TITLE
During autotagging text is logged at cursor position, not end of screen

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#59]
_From [tr...@houliston.me](https://code.google.com/u/114935886033864143634/) on November 05, 2014 15:14:51_

What version of ComicTagger are you using? 1.1.15-beta On what operating system (Mac, Linux, Windows)? What version? Mac GUI or command line? GUI What steps will reproduce the problem? 1. Auto tag some comics
2. Click somewhere on the screen
3. Text will begin to print at the cursor location What is the expected output? What do you see instead? The text should continue to print at the end of the log rather then at the cursor.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=59_

**Comment by lordwelch** [comment]
fixed in #214
