### ISSUE TITLE
TypeError when loading multiple comics

### ISSUE THREAD

**Issue by stevethebuff** [comictagger/comictagger#593]
Novice user here ...I just installed ComicTagger (1.6.0-alpha.10) on my MacBook and successfully added the .cbr tagging function using Homebrew. So far so good.

It's working great when I use Open and do a single comic book file, but when I Open Folder to do multiple comics I get this error message:

<img width="431" alt="Screenshot 2024-01-18 at 7 32 01 pm" src="https://github.com/comictagger/comictagger/assets/157696881/05878b1d-7ce8-4ea2-8a17-c34350b37234">

I found the fileselectionlist file but can't see what needs changing.

New to  Python so hoping it's something simple I've missed ...

**Comment by stevethebuff** [comment]
Installed the new update, and it is now working perfectly.  Many thanks!

**Comment by lordwelch** [comment]
But I didn't actually push the fix yet.............. Were you installing via pip?

**Comment by stevethebuff** [comment]
I did install via pip originally, but when I opened the application a couple of days ago I got a prompt to install an update.  I did and it's working ... ain't gonna quibble with that!

**Comment by lordwelch** [comment]
if you used brew, they default to python3.11 which is not tested and probably caused the issue.
