### ISSUE TITLE
Credits getting lost

### ISSUE THREAD

**Issue by crass00** [comictagger/comictagger#602]
Hi,

When I get tag info from comicvine (I don't think this is a comicvine specific thing).  If a particular credit  has 1 person but with multiple roles (ie Writer and Artist) On save that info is lost rather than converted to seperate entries.  I think in such cases entries it should be split up so no info is lost when saved. 

Here is an example comic  https://comicvine.gamespot.com/sergio-aragones-the-groo-jamboree-1-tpb/4000-400256/ but its happens a lot for manga where the artist and writer are very often the same person

Cheers
Alex

**Comment by lordwelch** [comment]
Well I apparently broke this in 2c3a2566cce1a871cbc3c2058a0d34ea9490dc16 which was in [1.6.0-alpha.5] so [1.6.0-alpha.4] and earlier don't have this issue


[1.6.0-alpha.5]: https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.5
[1.6.0-alpha.4]: https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.4
