### ISSUE TITLE
[Feature Request] Preferences: Delay in tagging

### ISSUE THREAD

**Issue by TheBags** [comictagger/comictagger#613]
Hi,
since there is an API limit of 200 calls per hour on Comic Vine, **_it might be useful to have a preference to set a delay when multiple Auto-Tagging is performed._**

![SCR-20240226-nsqx](https://github.com/comictagger/comictagger/assets/2011000/dacede3b-0b3a-4781-ad72-4f394edfae49)

18s is calculated as:
Number of available calls in one hour: 200
Number of seconds in one hour: 3600
Delay = Number of seconds in one hour / Number of available calls in one hour = 3600 / 200 = 18

When the preference is set, every API call will be dalayed by 18s.

Tnx,
Giovanni

**Comment by lordwelch** [comment]
You don't want it to be an 18s delay between each call that is way to long also the [API] states:
> We officially support 200 requests per resource

There are 42 separate resources in the API https://comicvine.gamespot.com/api/documentation.
If you can do 8400 requests in an hour and not reach their limit.

Per [the developers]:
> Space out your requests so AT LEAST one second passes between each and you can make requests all day.

Currently the limit in ComicTagger is to allow 10 requests during any 10s window this allows small bursts of requests and keeps mostly within their limits. In 90% of cases ComicTagger can't actually go faster than 1 request a second per-resource anyway.

[the developers]: https://comicvine.gamespot.com/forums/api-developers-2334/api-rate-limiting-1746419/
[API]: https://comicvine.gamespot.com/api/

**Comment by TheBags** [comment]
Hi @lordwelch ,
I opened the ticket because i've had problems...
https://comicvine.gamespot.com/api/#:~:text=Rate%20limiting&text=We%20officially%20support%20200%20requests,for%20all%20of%20our%20users.

Seems that the 200 calls is for the API in general.

Giovanni
