### ISSUE TITLE
Comictagger doesn't write resource lists correctly for `comicinfo.xml`

### ISSUE THREAD

**Issue by bpepple** [comictagger/comictagger#617]
Noticed that Comictagger doesn't write resource lists (characters, teams, creators, etc) correctly if the string value from the data source (ComicVine or Metron) contains a comma.

If a comma is going to be used as a delimiter (which I don't think is a great idea for any type of name, a semi-colon seems like a more sane option) it needs to double quote the value when joining the values to a comma delimited string.

For example, if you were to tag for the comic `52 #12 (2006)` currently the teams list is as follows:
```
<Teams>Teen Titans,Infinity, Inc.</Teams>
```
where is should be:
```
<Teams>Teen Titans,"Infinity, Inc."</Teams>
```
Not really familiar with how you're handing metadata these day, but something like this should work:
```
lst = ["Outsiders", "Infinity, Inc."]
", ".join((f'"{item}"' if "," in item else item) for item in lst)
'Outsiders, "Infinity, Inc."'
```

**Comment by lordwelch** [comment]
ComicRack only supports commas the last time I checked

**Comment by bpepple** [comment]
> ComicRack only supports commas the last time I checked

I do question the wisdom of allowing a program that died 10 years ago to hamstring efforts to implement improvements, but if that is the case, it's been common practice for ages in comma delimited strings that contain commas (like "Infinity, Inc.") to be double quote enclosed.

**Comment by lordwelch** [comment]
That's what [anansi-project/comicinfo](https://github.com/anansi-project/comicinfo) is for. I would suggest opening a ticket there. The implementation of anansi-project/comicinfo for ComicTagger is located https://github.com/comictagger/comicinfoxml. The ComicInfo.xml implementation in this repository is intended to be only compatible with ComicRack as there is still a community that uses it. ComicTagger internally uses lists/sets to represent them so there would be no problem creating a metadata plugin to do with it as you please (documentation to be written in the future but https://github.com/comictagger/comicinfoxml is implemented as a pip-installable plugin so it would be a good starting place)

Also ComicTagger supports CoMet and CBI/CBL metadata and for those items that they intended to be multi-valued they do not use CSV formatted data.
