### ISSUE TITLE
Can't save or edit info

### ISSUE THREAD

**Issue by k3ltfalcon** [comictagger/comictagger#619]
I use the latest version of Comictagger (1.6.0-alpha.12: Lucius Morgan) in Windows 10. This software works well at first. But later, I can't save or edit anything. Please help me.
![1](https://github.com/comictagger/comictagger/assets/162257733/c901c7f5-b8e1-45c7-81a7-18422af57ad8)

**Comment by lordwelch** [comment]
Something seems to be failing when checking what fields it's has available to edit. You should be able to get it working by selecting the ModifyStyles dropdown on the top left and selecting any of the others and then deselecting it.
