### ISSUE TITLE
[Bug] File Name Parsing Doesn't work how it used to CLI

### ISSUE THREAD

**Issue by SandyRodgers-2017** [comictagger/comictagger#630]
When using the CLI file name parsing doesn't seem work on the version built from the latest source.  It can't seem to fill the series from the file name and instead seems to keep it empty even though I specified file name parsing. The program also doesn't overwrite previous series metadata like it used to. However, its able to parse the filename  and file in series name in the gui just fine.  I don't think that this  is intended behavior. This doesn't work for either cix or cr.  Could it be fixed? I usually glob my files but I also tried doing each file one by one in the terminal neither worked.

**Comment by lordwelch** [comment]
I can't re-produce this on the latest git commit, 1.5.5 or 1.3.0. Can you provide the log? It would be located at.
%LOCALAPPDATA%\ComicTagger\logs on windows
~/Library/Logs/ComicTagger/ on macOS
~/.cache/ComicTagger/log on Linux

**Comment by SandyRodgers-2017** [comment]
Ok Here you go. Sorry for taking so long. Had other more urgent stuff to do. Hope this will help fix the issue and thank you. My version of comic tagger is built from source due to my system incompatibility with newest pre-built binaries. Slightly NSFW.
[ComicTagger.log](https://github.com/comictagger/comictagger/files/15058129/ComicTagger.log)

[ComicTagger.1.log](https://github.com/comictagger/comictagger/files/15058130/ComicTagger.1.log)

Here is my one liner for example:

`comictagger  -s -t cix --parse-filename --filename-parser complicated -m "maturity_rating=Adults Only 18+,genres=straight^,hentai^,doujinshi,title=" -v *cbz`

I tried a number of different permutations of the above some containing the full file name or the full file path nothing seemed to work in cli. However in gui it did. I also tried changing the filename parser to a number of different types. Still nothing changed. 


Just in case it isn't clear. Expected behavior is for filled metadata  fields such as Series to instead be changed to Parsed filname output.

**Comment by lordwelch** [comment]
I see everything as working as I would expect
```console
$ /Applications/ComicTagger.app/Contents/MacOS/comictagger -d -t cix '[XTER] My Oyakodon [English][AD].cbz'
/Users/timmy/[XTER] My Oyakodon [English][AD].cbz: Removed Comic Info XML tags.
$ /Applications/ComicTagger.app/Contents/MacOS/comictagger -s -t cix --parse-filename --complicated-parser -m "maturity_rating=Adults Only 18+,genres=straight^,hentai^,doujinshi,title=" -v *cbz
2024-04-23T23:31:33 | comictagger | INFO | ComicTagger Version: 1.6.0a12 running on: Darwin PyInstaller: Yes
2024-04-23T23:31:34 | comictaggerlib.cli | INFO | Save complete.
2024-04-23T23:31:34 | comictaggerlib.cli | INFO | 
2024-04-23T23:31:34 | comictaggerlib.cli | INFO | Successful matches:
2024-04-23T23:31:34 | comictaggerlib.cli | INFO | ------------------
2024-04-23T23:31:34 | comictaggerlib.cli | INFO | ./[XTER] My Oyakodon [English][AD].cbz: None
$ rar p '[XTER] My Oyakodon [English][AD].cbz' ComicInfo.xml
<?xml version='1.0' encoding='utf-8'?>
<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Series>My Oyakodon</Series>
  <Genre>straight,hentai,doujinshi</Genre>
  <AgeRating>Adults Only 18+</AgeRating>
  <ScanInformation>[XTER] [English][AD]</ScanInformation>
  <Pages>
    <Page Image="0" Type="FrontCover" />
    <Page Image="1" />
    <Page Image="2" />
    <Page Image="3" />
    <Page Image="4" />
    <Page Image="5" />
    <Page Image="6" />
    <Page Image="7" />
    <Page Image="8" />
    <Page Image="9" />
    <Page Image="10" />
    <Page Image="11" />
    <Page Image="12" />
    <Page Image="13" />
    <Page Image="14" />
    <Page Image="15" />
    <Page Image="16" />
    <Page Image="17" />
    <Page Image="18" />
    <Page Image="19" />
    <Page Image="20" />
    <Page Image="21" />
    <Page Image="22" />
    <Page Image="23" />
  </Pages>
$ /Applications/ComicTagger.app/Contents/MacOS/comictagger -p *cbz
RAR archive ( 24 pages)  tags:[ ComicBookInfo Comic Rack Comic Info XML ]

--------- ComicBookInfo tags ---------
series:          Cory Doctorow's Futuristic Tales of the Here and Now
issue:           1
issue_count:     6
title:           Anda's Game
publisher:       IDW Publishing
year:            2007
month:           10
volume:          1
genres:          Sci-Fi
language:        en
critical_rating: 3
description:     For 12-year-old Anda, getting paid real money to kill the characters of players who were cheating in her favorite online computer game was a win-win situation. Until she found out who was paying her, and what those characters meant to the livelihood of children around the world.
credit:          Writer: Dara Naraghi
credit:          Penciller: Esteve Polls
credit:          Inker: Esteve Polls
credit:          Letterer: Neil Uyetake
credit:          Cover: Sam Kieth
credit:          Editor: Ted Adams

--------- Comic Rack tags ---------
series:          My Oyakodon
genres:          hentai, doujinshi, straight
maturity_rating: Adults Only 18+
scan_info:       [XTER] [English][AD]

--------- Comic Info XML tags ---------
series:          My Oyakodon
genres:          hentai, doujinshi, straight
maturity_rating: Adults Only 18+
scan_info:       [XTER] [English][AD]
```

**Comment by SandyRodgers-2017** [comment]
Thanks for the comment, but it doesn't seem,too. I'm seemingly on a newer version then the one you mentioned. It doesn't fill in series with new information like it used to. It used to overwrite old information if I wanted it to, it still does this in the gui, but not the cli.
 I tried what the command you showed and if I delete the cix info. it does parse the information, and put in the correct location, but it no longer overwrites already filled info with parsed information. This is what I would like it to do and what it used to do in the cli .
Is there some way to make more detailed logs? I'm not sure what to show you, maybe my logs were showing a the different version of comictagger that I also have installed. So I uploaded this and made sure that my other comictagger version wasn't used at all.  If this doesn't work I will make a screen recording of what i'm seeing and experiencing, and what the behavior used to be.  Thank you for you time.
Here is what my terminal shows when I run the above command.
2024-04-28T03:13:45 | comictagger | INFO | ComicTagger Version: 1.6.0a13.dev38 running on: Linux PyInstaller: No
2024-04-28T03:13:45 | comicapi.archivers.rar | ERROR | rar unavailable
2024-04-28T03:13:45 | comictaggerlib.cli | INFO | Save complete.
2024-04-28T03:13:45 | comictaggerlib.cli | INFO | 
2024-04-28T03:13:45 | comictaggerlib.cli | INFO | Successful matches:
2024-04-28T03:13:45 | comictaggerlib.cli | INFO | ------------------
2024-04-28T03:13:45 | comictaggerlib.cli | INFO | ./[XTER] My Oyakodon [English][AD].cbz: None

[ComicTagger.1.log](https://github.com/comictagger/comictagger/files/15141177/ComicTagger.1.log)
[ComicTagger.log](https://github.com/comictagger/comictagger/files/15141178/ComicTagger.log)

**Comment by lordwelch** [comment]
It has never overwritten existing information with parsed filename information on the CLI. I even checked version '1.1.1-beta' released back in 2013. In the GUI there is a command to parse the filename info but that only works if you manually execute that command. If you use auto-tag in the GUI it will ignore the filename if any tags already exist.

**Comment by SandyRodgers-2017** [comment]
It used to on version 1.3.0a5.dev0. It seems like that may not have been intended behavior then.  Here is a video. NSFW:Suggested Nudity

https://gofile.io/d/dRiEWG

Here is the command I used:
`comictagger-new  -s -t cr -f -m "maturityRating=Adults Only 18+,genre=straight^,hentai^,doujinshi,title=" -v *cbz`

comictagger-new is just the name of this version that I have to keep different version from interacting with each other too much.

**Comment by lordwelch** [comment]
Apparently I forgot how to read code because I changed it in c95e700025143fb6ff736f4b6933e8f64f26f7dd version 1.3.2-alpha.0
Before that the filename would overwrite existing metadata

**Comment by SandyRodgers-2017** [comment]
So could it be implemented back or a flag added that does the same thing or would that mess up something? Its very useful for me, but I'm only one person.

**Comment by lordwelch** [comment]
Are you getting these comics with a ComicInfo.xml already in them? and do you actually intend to keep any of that data?

**Comment by SandyRodgers-2017** [comment]
Yes. I use another program that downloads the files and compiles them into a cbz with a ComicInfo.xml. I would like to keep most of the data. What I usually want changed is the series name and issue number,  and as you can see above add a few genres, a maturity rating to the file along with clearing any title that the file may have. When file name parsing , series name and issue number used to be what the program used to change by itself, and unless otherwise specified it left everything else alone. This is the behavior I would like brought back if possible. 
Thank you for taking to respond, 
SR

**Comment by protofolius** [comment]
Try using a compiled version from Github and see if there is any difference .
The latest alpha 12 for example . (https://github.com/comictagger/comictagger/releases)

**Comment by SandyRodgers-2017** [comment]
Thanks lordwelch will compile this new version
