### ISSUE TITLE
[Feature Request] Add original filename string to Rename

### ISSUE THREAD

**Issue by deadman36g** [comictagger/comictagger#631]
Hello,

I would like to request that the original filename string be added as a rename string

An example I am looking for is as follows

my filename is DC Horror Presents - The Conjuring - The Lover 01 (of 05) (2021) (digital) (Son of Ultron-Empire).cbr

my current rename template is {publisher}/{series} ({year})/

I would like to keep my files with their original filenames, but I do want ComicTagger to create the {publisher}/{series} ({year})/ directories.

**Comment by lordwelch** [comment]
I'll add an option to move without renaming

**Comment by deadman36g** [comment]
> I'll add an option to move without renaming

Thank you, I eagerly await the next alpha.

**Comment by lordwelch** [comment]
Fixed in 8b4bf8d51f1486bd0663229d61842b210b7aed13 next release will have this fix
