### ISSUE TITLE
1.6.0-alpha.12 on Mac M2 macOS 14.4.1 (Sonoma) comictagger startup error

### ISSUE THREAD

**Issue by rmohns** [comictagger/comictagger#634]
Release 1.6.0-alpha.12 binary download puts up this error at startup:

```
Unhandled exception in app:
Traceback (most recent call last):
  File "comictaggerlib/gui.py", line 136, in open_tagger_window
  File "comictaggerlib/taggerwindow.py", line 221, in __init__
TypeError: 'int' object is not iterable
```

Screenshot:
<img width="532" alt="Screenshot 2024-04-21 at 10 37 00 PM" src="https://github.com/comictagger/comictagger/assets/2131133/d76bdd08-dc82-46b5-8be8-d309e2f76a0e">

If I can provide any more information, please let me know how I can best help.

**Comment by lordwelch** [comment]
You will need to clear out your settings in `~/Library/Application Support/ComicTaggec`

**Comment by rmohns** [comment]
Thank you! This resolved it.
