### ISSUE TITLE
[Bug] 1.6a12 (as well as latest commit) unable to Ctrl-A within issues list

### ISSUE THREAD

**Issue by Cducharme84** [comictagger/comictagger#635]
Behavior observed: When pressing the control and A keys to select all issues on the right-hand pane nothing happens visibly in regards to file selection. 

Expected behavior: previously this would result in all files/issues open being highlighted for bulk editing/removal from list. 

OS: Manjaro - 6.8 kernel
DE: KDE Plasma 6 (latest release in repo) / Cinnamon
Display server: Wayland (KDE) / x11 (Cinnamon)

1 other reported user using Windows 11 also cannot do this function, so it appears to not be environmental.

Versions affected: Looks like all after at least a12. I've used the commit most recently applied in the repo as well. 

Hoped for resolution: return to behavior of allowing ctrl-a to select all files, similar to the standard in most OS/DE combos.

**Comment by Cducharme84** [comment]
Right-click and "select all" does not appear to function either.

**Comment by lordwelch** [comment]
This is fixed in 996397b9d51872ea2a3bae9ef890495775a196f8 and will be in the next alpha

**Comment by Cducharme84** [comment]
Awesome, thanks! I usually grab the latest commits if there are any before using CT so I’m running with the fix.
