### ISSUE TITLE
Can't open alpha 12 on windows

### ISSUE THREAD

**Issue by Roshri** [comictagger/comictagger#636]
Downloading the exe and trying to open it brings an exception
![image](https://github.com/comictagger/comictagger/assets/29184137/ce0ff829-e6ad-499a-bc41-a0d82ee800a4)

can't run the program from latest commit either, also brings an exception

`in <module>
    import settngs
ModuleNotFoundError: No module named 'settngs'`

**Comment by lordwelch** [comment]
Remove the settings.json file in %LOCALAPPDATA%/ComicTagger
