### ISSUE TITLE
Complicated Parser - ½ symbol causes freeze and infinite memory leak

### ISSUE THREAD

**Issue by barrelltitor** [comictagger/comictagger#639]
OS: Windows 10
Comic Tagger Version: alpha 12 - Windows exe version
Reproduction steps:

* Start comictagger
* Enable Complicated parser and c2c&fcbd removal
* Add the ½ symbol anywhere in a comic's name, e.g `Potato Man #½ - Spud's Origins (2093) [Marvel]`
* Drop the comic into comictagger
* It now froze and starts gobbling up your memory

Disabling the complicated parser fixes this. I haven't tried disabling c2c or fcbd removal but I don't see how that would affect it.

Searched for 1/2, ½ and half, didn't find any existing issues

**Comment by Cducharme84** [comment]
I've done some testing after discussion on Discord involving this issue, I found if comictagger is called with complicated parser set in the settings already there's no issue tagging these ½ issues in GUI. If you switch from original or (in latest commits) comicfn2dict to complicated and select the file or use the ctrl-f hotkey to reparse the file memory starts ballooning until the available is met.

I've tested in alpha 12 and the latest commit as of this morning in Manjaro and was able to reproduce in both with these conditions.
