### ISSUE TITLE
LLM integration [Feature Request]

### ISSUE THREAD

**Issue by projectje** [comictagger/comictagger#643]
*feature request*

With various LLM API's the ability to upload a cover to "AI" and get a json would be handy e.g. just by uploading a
cover to open api and the request to generate a json for it goes pretty automagical.

![image](https://github.com/comictagger/comictagger/assets/6946109/04dce253-49b7-45bb-b2bd-6c33d01a46d9)

![image](https://github.com/comictagger/comictagger/assets/6946109/47d7f4f0-7b19-4a78-8862-d335d8c51e30)

**Comment by lordwelch** [comment]
LLMs hallucinate. Carl Gafford apparently didn't start coloring until 1970s https://dc.fandom.com/wiki/Carl_Gafford and GCD doesn't have him credited on anything before 1973 https://www.comics.org/checklist/1878/

The JSON is entirely arbitrary and doesn't make sense and the xml that it generated is not compatible in most ways with comicrack the application that originally made the ComicInfo.xml files

LLMs are a cool technology to play around with but I will not be adding any use of it to ComicTagger
