### ISSUE TITLE
remove_html_tables setting not followed with Auto-Tag (GUI - 1.6.0-alpha.12)

### ISSUE THREAD

**Issue by EnSt0rm** [comictagger/comictagger#644]
Using version [1.6.0-alpha.12](https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.12), with the GUI.

Using ComicVine as the source, I've found that when I'm doing an individual search, either manually, or with Auto-Identify, the remove_html_tables settings is working as intended, and the Comments field doesn't include lists of alternate covers etc.

However, when I use auto-tag, the same items are getting the table added, even while remove_html_tables is set to true.

**Comment by EnSt0rm** [comment]
Update - I've checked, and using CLI, remove_html_tables setting is working as intended, except where the '-i' interactive flag is used.

**Comment by mizaki** [comment]
Having a look, I believe the current `develop` solves these issues (along with #651). If you can give me an example title I can further check.

Also, "Comments field doesn't include lists of alternate covers" I presume these were in the comments as `<a>` tags.

**Comment by lordwelch** [comment]
This was fixed in [1.6.0-alpha.13]

[1.6.0-alpha.13]: https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.13
