### ISSUE TITLE
JPEG-XL support

### ISSUE THREAD

**Issue by mobedoor** [comictagger/comictagger#649]
I would like to request support for JPEG-XL, same as for AVIF in #569.

**Comment by lordwelch** [comment]
Pillow does not support JPEG-XL they have an open issue for it here python-pillow/Pillow#4247
None of the plugins listed in the issue for JPEG-XL seem to work, they all need to be compiled whenever I try to install them and so will not be added. The AVIF plugin works on all the platforms without issue and without any extra changes needed by ComicTagger. If you install using pip you can try using one of the plugins but I don't expect it to work well without further configuration.

**Comment by lordwelch** [comment]
@mobedoor well it seems that the plugins work now so the next alpha should have JPEG-XL support

**Comment by mobedoor** [comment]
Thanks for working on it lordwelch.
