### ISSUE TITLE
Rar Tools setting -  remove comic rack tag from cbz

### ISSUE THREAD

**Issue by protofolius** [comictagger/comictagger#650]
-comictagger version 1.6.0a12
-In settings - RAR tools , I select the Winrar installation .exe (C:\Program Files\WinRAR\Rar.exe) .
-My installed WinRAR version is 7.01 64bit (registered version) .

When I close and re-open comictagger and check the setting - RAR tools again , the path is empty .

The reason why I mention this is because when I use the "Remove comicrack tag" function on a .cbz file that has a comic rack tag , the comictagger program crashes . I think both might be related .

Error when trying to remove a comicrack tag from a .cbz :

_```
Oops . An unexpected error occured:
Keyerror: 'c'

File "comictaggerlib\taggerwindow.py", line
1504, in remove_tags
File "comicapi\comicarchive.py", line 234, in
has_metadata_
```_

**Comment by lordwelch** [comment]
It automatically checks several locations for rar, I should add a label saying if it found it or not

**Comment by lordwelch** [comment]
If you could attach the full log it would be best

**Comment by Drumada** [comment]
I just installed Comictagger fresh (1.6.0a12) and am also having the issue where RAR Tools doesnt seem to stick in settings. With a fresh install of WinRAR 7.01 (Unlicensed) installed to a non-standard location (different drive letter). I have not encountered a comicrack tag to perform this with, but if we want to diagnose whether or not these two are related or not I am happy to provide necessary logs as well.
