### ISSUE TITLE
Complicated parsers trips and adds a dot

### ISSUE THREAD

**Issue by protofolius** [comictagger/comictagger#652]
in 2 cases that i found , the complicated parser unnecessarily adds a point at the end .

2 examples where it does this :
Book #001 Day Z.cbz --> results in a title of Day Z.
Book #001 Stop it!.cbz --> results in a title of Stop it!.
Book #001 'If Your Eye Is a Burden...' --> results in a title of If Your Eye Is a Burden'.

note the points in the end

**Comment by protofolius** [comment]
Same seems to be the case with a title of Conceptions I from a filename of Conceptions #001 Conceptions I.cbz
The complicated parser parses the title as Conceptions I.

not the point/dot in the end .

**Comment by lordwelch** [comment]
I have a fix for this planning on pushing it tonight

**Comment by protofolius** [comment]
Super , Cool . Looking forward to the fix .

Also found another instance where it does this
With filename Crossover #006 Gen 13 + Generation X.cbz --> The title becomes Generation X.

When the new release is out I will test it :)

Thank you !
