### ISSUE TITLE
Windows installer not working on Windows 10 Pro

### ISSUE THREAD

**Issue by lvcabral** [comictagger/comictagger#664]
I have a Windows 10 Pro machine, brand newly installed, with latest version of Pyhon 3.12, when I try to run the latest package installer v1.5.5 I get this error:

<img width="927" alt="image" src="https://github.com/comictagger/comictagger/assets/16841645/78c6aa7d-233c-4263-8def-b73c7f49f8ed">

**Comment by lvcabral** [comment]
I solved the issue by installing the latest MSVC libraries, this should be in the documentation, not all Windows machines has the MSVC installed, in particular brand new installations with no developers tool.

https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by lordwelch** [comment]
I didn't even notice that it was needed
