### ISSUE TITLE
[GCD/Gui only] When searching pressing enter on results brings comic id 1

### ISSUE THREAD

**Issue by Cducharme84** [comictagger/comictagger#669]
Prior to recent alphas when pulling up a search in the GUI of the the GCD database, if the correct series comes up without further selection it would grab the issue details that matched the issue number (so Age of the Wolf from rebellion would bring up no other options in the search result for example)  and populate the form with those details. Now it grabs the details but of  the comic with issue id #1. See attached screens at imgur for example.

[Screens](https://imgur.com/a/edxnOpo)

**Comment by Cducharme84** [comment]
This does only happen in GUI with GCD talker all others appear unaffected.

**Comment by lordwelch** [comment]
Some parentheses were forgotten https://github.com/comictagger/gcd_talker/blob/45c83f3cda056781578cc6e656685ac57ce166ad/gcd_talker/gcd.py#L837

**Comment by mizaki** [comment]
Fixed with https://github.com/comictagger/gcd_talker/pull/24

I need to make a couple of other changes and then I'll do a new release in the next few days.

**Comment by mizaki** [comment]
https://github.com/comictagger/gcd_talker/releases/tag/0.1.2 but the pre-compiled alpha CT won't have it until the next alpha release.

**Comment by lordwelch** [comment]
This should be included in https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.22
