### ISSUE TITLE
comictagger not starting

### ISSUE THREAD

**Issue by musictrivianut** [comictagger/comictagger#670]
Just in the last few days, comictagger has stopped working, both CLI and GUI.

```
$ comictagger --version
ComicTagger 1.6.0a21.dev23:  Copyright (c) 2012-2022 ComicTagger Team
Distributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
```
```
$ comictagger
Traceback (most recent call last):
  File "/home/wayne/.local/bin/comictagger", line 8, in <module>
    sys.exit(main())
  File "/home/wayne/.local/lib/python3.10/site-packages/comictaggerlib/main.py", line 326, in main
    App().run()
  File "/home/wayne/.local/lib/python3.10/site-packages/comictaggerlib/main.py", line 123, in run
    self.main()
  File "/home/wayne/.local/lib/python3.10/site-packages/comictaggerlib/main.py", line 273, in main
    for pkg in sorted(importlib_metadata.distributions(), key=lambda x: x.name):
TypeError: '<' not supported between instances of 'NoneType' and 'str'

```
Same error whether I put in an argument or just the simple command. GUI never starts.

I know nothing about python other than installing packages, so tracking down why it is doing this is way beyond me.

Did reinstall, but no joy.  Any guidance appreciated and please let me know if there is any other information needed to dig into this.

Thank you!

**Comment by lordwelch** [comment]
You pip installed a package that doesn't have a name I recommend using pipx so other packages don't interfere

**Comment by musictrivianut** [comment]
Thank you!! I did not know about pipx. I had previously tried virtual environments, but the instructions I found were not as easy to use or understand as that seems to be.

Really appreciate the advice and your continued support for comictagger!
