### ISSUE TITLE
complicated parser and ' or + character

### ISSUE THREAD

**Issue by protofolius** [comictagger/comictagger#672]
filename
Airfiles #04 The 'Big Show' 2.cbz

turns title into
The' Big Show' 2

filename
Army #11 Operation 'Z'.cbz

turns title into
Operation' Z'

filename 
De Dwaas Van De Koning #009 Het Testament Van d'Artagnan.cbz

turns title into
Het Testament Van d' Artagnan
notice the added space after the '

I am using the complicated parser through command line , but the same behaviour is seen in the GUI .
Using version 1.6.0a21.dev0

The same happens with + signs .

filename
De Man of Steel #01 The Invasion + Power of The Monster.cbz

turns title into
The Invasion+ Power of The Monster

When a title start with a ' character , it drops it completely .
For example
Atari Force #09 'Als Uw Oog U Tot Last Is...'.cbz
turns title into
Als Uw Oog U Tot Last Is'
drops the first ' completely (and it also drops the ... for some reason)

**Comment by lordwelch** [comment]
that's because quotes shouldn't be in filenames 😝. I'll see if I can get to this next week

**Comment by protofolius** [comment]
If you need a Comic series to test with , this would be a good example for the ' sign :

https://www.stripinfo.be/reeks/index/1847_De_psy
