### ISSUE TITLE
not pulling/showing issue cover

### ISSUE THREAD

**Issue by musictrivianut** [comictagger/comictagger#675]
Not sure if this is just a "me" problem or if others have encountered it.

Comictagger seems to have trouble pulling and showing issue covers when trying to match things, at least on occasion. With both Auto-Identify and Auto-Tag, when the cover should be shown, it's just a blank and CT says it is searching for alternate covers.  Have tried clearing the cache multiple times, but does not seem to help at all.  Not really a big deal, but quite a few things end up as low-confidence  matches because of this and have to be manually matched.

I am using version v1.5.5 on Linux Mint.

Thanks!

**Comment by lordwelch** [comment]
Can you try on the latest alpha?

**Comment by musictrivianut** [comment]
I originally installed CT with pipx, not git, and my git-fu is not strong at all.  Not a big deal.  I can wait until next release.

**Comment by lordwelch** [comment]
`pipx install comictagger --pip-args='--pre' --force` or `pipx install comictagger==1.6.0a22  --force`

**Comment by musictrivianut** [comment]
Thank you for that.  I may learn the ins-and-outs of pip and git someday.

And yes, that seemed to do the trick.  Even differentiated between a regular issue 1 and TPB with the same cover.  Excellent!!

**Comment by lordwelch** [comment]
I added that in [1.6.0-alpha.13](https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.13) though I apparently forgot to put it into the release notes
