### ISSUE TITLE
[Enhancement] Removal of ComicBookLover format

### ISSUE THREAD

**Issue by DieselTech** [comictagger/comictagger#676]
I think the time has finally come to remove ComicBookLover format. It never really took off when it was created and has only served as a point of frustration when pointing new people at ComicTagger to tag their files, only to have them use said dead format that nearly nothing at all reads and causes these support sessions to be longer than they need to be.

**Comment by lordwelch** [comment]
Fair, in the next alpha I'll move it out to a separate repo that isn't included by default for the odd person that wants it

**Comment by lordwelch** [comment]
Removed in 006f3cbd1f9689d7c97345f4917145d311988fe0
