### ISSUE TITLE
Renaming stops when it encounters a " character. Mostly found in title tag

### ISSUE THREAD

**Issue by davide-romanini** [comictagger/comictagger#68]
_From [grip...@gmail.com](https://code.google.com/u/103748524502431867003/) on January 22, 2015 20:47:42_

What version of ComicTagger are you using? V1.1.15 beta On what operating system (Mac, Linux, Windows)? What version? Windows 8.1 x64 GUI or command line? GUI What steps will reproduce the problem? 1. Drag and drop a comic into the comic list pane (right side)
2. Select all comics, Ctrl-N to rename
3. Change rename settings to include title &#37;series&#37; #&#37;issue&#37; (&#37;volume&#37;) - &#37;title&#37;
4. Returns with the projected renamed files (looks good here)
5. Hit ok to run. What is the expected output? What do you see instead? App stops processing on any titles that have quoted text. No error, it just stops running with the progress bar. I then cancel and select only the titles with "'s in them. 

Example Inhumans volume 2 # 12 and 13. They both have a title of Plan "A" and Plan "B" respectively. Please provide any additional information below.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=68_

**Comment by davide-romanini** [comment]
_From [grip...@gmail.com](https://code.google.com/u/103748524502431867003/) on January 22, 2015 11:52:53_

Additional Info. This is because you cannot put a " in the name of a file in windows. Suggestion would be for re-namer to remove special characters that are not allowed in windows since it doesn't make sense to rename something to an invalid name.

**Attachment:** [error.png](http://code.google.com/p/comictagger/issues/detail?id=68#hc1)

**Comment by lordwelch** [comment]
This should be fixed in the latest release [1.4.1](https://github.com/comictagger/comictagger/releases/tag/1.4.1)
