### ISSUE TITLE
Need "start_year" of a series

### ISSUE THREAD

**Issue by killo3967** [comictagger/comictagger#680]
I have this rename template:

\{series} ({year})({publisher})\{series} #{issue} - {title}

The problem is when a series has diferent years of creation comictagger create diferent directories. 
I there an option to only use the first year, or the year of the number 1 issue?

**Comment by lordwelch** [comment]
There is an option to use the series start year as the volume, but currently there is not a dedicated field for the series year

**Comment by killo3967** [comment]
I know, but not all comics have the {volume} data. 
Could be posible to implement in the future "calculated fields"?
In this case the {year} of the first {issue}, by example.

**Comment by lordwelch** [comment]
The Comic rack format doesn't have a way to save this information in any other way. If this isn't how they are currently tagged you will need to re-tag your library

**Comment by killo3967** [comment]
i don't ask you about this theme if i don't see it before. In comicRack program, there is a plugin to scrape ComicVine and when i scrape with this plugin i could view the "volume" data. This is the log:
======> scraping next comic book: 'Book of Butcher.cbz'
trying to match this book automatically...
...too many matches, only getting the first 50
...found a suitable match:  Book of Butcher (155732)
searching for the right issue in 'Book of Butcher (155732)'
finding all issues for 'Book of Butcher (155732)'...
   ...found 1 issues at comicvine.gamespot.com
   ...identified issue number 
querying comicvine for issue details...
setting values for this comic book ('*' = changed):
-->  Series         : Book of Butcher
--> *Issue Number   : 1
-->  Title          : 
-->  Crossovers     : 
--> *Summary        : Leading into the fifth anniversary of Something Is Killing The Childre ...
--> *Release Date   : 2023-12-27
--> *Publish Date   : 2023-12-27
**--> *Volume         : 2023**
-->  Imprint        : 
--> *Publisher      : Boom! Studios
--> *Characters     : Cecilia Slaughter, Louis Boucher, Maxine Slaughter
--> *Teams          : The Order of St. George
--> *Locations      : New Orleans
--> *Writers        : James Tynion IV, Tate Brombal
--> *Pencillers     : Antonio Fuso, Chris Shehan, Letizia Cadonici, Werther Dell'Edera
--> *Inkers         : Antonio Fuso, Chris Shehan, Letizia Cadonici, Werther Dell'Edera
--> *Colorists      : June Chung, Miquel Muerto, Tamra Bonvillain
--> *Letterers      : AndWorld Design
--> *CoverArtists   : Dan Mora, Dani, Jae Lee, June Chung, Tamra Bonvillain, Werther Dell'Ed ...
--> *Editors        : Eric Harburn, Maya Bollinger, Ramiro Portnoy
--> *Webpage        : https://comicvine.gamespot.com/book-of-butcher-1/4000-1038464/
-->  Rating         : --- skipped ---
--> *Tags           : CVDB1038464
--> *Notes          : Scraped metadata from ComicVine [CVDB1038464].
--> *Issue Key      : 1038464
--> *Series Key     : 155732
-->  Cover Art URL  : https://comicvine.gamespot.com/a/uploads/scale_small/11161/111615891/9214360-cover.jpg

As you could see, it's extract the volume data. 
Could be a calculated data? 
Because i try with other series with 100 books and all the books has the same "volume" data. 
In this case you could put the first year of the series as the volume data.

**Comment by lordwelch** [comment]
No. ComicTagger only works on a single comic at a time it cannot use information from other comics to calculate a field.
The best you can get with ComicTagger is to enable the "Use series start as volume" checkbox and re-tag your comics (screenshot is from the latest alpha release)
<img width="862" alt="Screenshot 2024-09-11 at 10 14 05 AM" src="https://github.com/user-attachments/assets/e17cb882-68c5-4e64-afe3-81b536d18533">

**Comment by killo3967** [comment]
Thank you very much, this what i am looking for. It's work perfectly for me. Sorry if I insist too much, but i prefer your software to the comicrack plugin.
