### ISSUE TITLE
Can't open after beta update

### ISSUE THREAD

**Issue by rad96** [comictagger/comictagger#687]
Can't open comictagger after beta update, probably need to handle it gracefully
![изображение](https://github.com/user-attachments/assets/a48d38f0-1586-4c03-b0ef-8ff5dc7ea70b)

Workaround:
1. Kill processes of Comictagger (if any)
2. Open `C:\Users\YourUsername\AppData\Local\ComicTagger\ComicTagger\settings.json`
3. Remove mentioning of cbi in `read_tags` and `write_tags`

**Comment by nbycoder** [comment]
Same here!

**Comment by lordwelch** [comment]
Fixed in [1.6.0-beta.2](https://github.com/comictagger/comictagger/releases/tag/1.6.0-beta.2)
