### ISSUE TITLE
Comicvine API Key no longer valid

### ISSUE THREAD

**Issue by maximo1984** [comictagger/comictagger#689]
I am unable to tag anything. Trying to diagnose the problem, my API key is no longer valid after testing it in Comictagger. I can no longer find the API key generation on the comicvine site either.

This link no longer works
https://comicvine.gamespot.com/api/

and I cannot find any link on the site to generate one. I cannot find any announcements about this either. 

Does anyone know anything or also have their keys not working?

**Comment by nodupe** [comment]
API is down since at least Saturday morning.

**Comment by maximo1984** [comment]
Do they announce that anywhere ? So I can just check there next time. Thanks for the reply

**Comment by eduo** [comment]
When this works, the API in Comictagger will work: https://comicvine.gamespot.com/api/

**Comment by mizaki** [comment]
The alternative is to use the beta release and use another source via the plugins. https://github.com/comictagger/comictagger/releases
