### ISSUE TITLE
Page order changes reset on save

### ISSUE THREAD

**Issue by mizaki** [comictagger/comictagger#695]
In `comicarchive.py` the method `apply_archive_info_to_metadata` runs `md.apply_default_page_list(self.get_page_name_list())` which will overwrite the page order from the page list window in the passed in `GenericMetadata` with `self.page_list` which appears to be set on init and is never updated afterwards.

**Comment by lordwelch** [comment]
Display order and archive order are two separate things. That list is supposed to be in archive order which should "never" change, in any case it updates the page objects in place so it shouldn't lose any information unless something was already messed up

**Comment by lordwelch** [comment]
I also can't reproduce this issue. Since `apply_archive_info_to_metadata` runs on every tag save this should show up as page order not being preserved when saving tags but currently page order is saved and loaded successfully when using ComicTagger.

**Comment by mizaki** [comment]
I'll give a little more for archive purposes:

You can see it if you move a page and then in `comicarchive.py` `apply_archive_info_to_metadata` and check `md.pages` order before `md.apply_default_page_list(self.get_page_name_list())` and after.

It appears as if it's setup solely around ComicRack due to `# cr doesn't record the filename it just assumes it's always ordered the same` in `L:368 comicrack.py`.

It just seems odd that the `md.pages` in is the page order and then is reset to the file name order (and then has to be reordered back I would presume for anything other than ComicRack).

Is `md.apply_default_page_list(self.get_page_name_list())` meant to be ran each time (it needs to be at the moment) or is the simple answer of:
```python
if len(md.pages) == 0:
    md.apply_default_page_list(self.get_page_name_list())
``` 
Would solve the issue (barring any unforeseen problems). Expecting `md.pages` to be in the "correct" page order and not file order seems sane.

Either way the answer is `sorted(md.pages, key=lambda x: x.display_index)` or `sorted(md.pages, key=lambda x: x.archive_index)` depending.

**Comment by lordwelch** [comment]
That's what the `display_index` attribute is for, see https://github.com/comictagger/comictagger/blob/6d20fe348f12a4b5c47385cb6e12e3f1bdc55c61/comictaggerlib/pagelisteditor.py#L363 for how to get the display order. I believe everywhere else in ComicTagger it preserves the order and sorts accordingly when needed
