### ISSUE TITLE
"Export as ZIP archive" fails to identify CBR file (OSX) but CT will write tags to CBR file

### ISSUE THREAD

**Issue by rhaussmann** [comictagger/comictagger#696]
When I select an RAR (CBR) file in the file list, choose "Export as Zip archive", and leave the default setting, I get a pop-up window: "No readable comic archives were found." I click OK in the pop-up. The pop-up window doesn't close, but another pop-up is generated with a cancel button and a bar indicator bouncing back and forth.
Sometimes, I get a pop-up with the message 'Successfully created 0 Zip archive(s)'.

I tried to Auto-Tag a CBR file. ComicTagger successfully tagged the unconverted CBR file (!) and generated a ComicInfo.xml file.  I was able to tag the entire directory with both filetypes without an issue.

The command: **file "book_file_name.cbr"** returns **book_file_name.cbr: RAR archive data, v4, os: Win32** just to confirm that this isn't a filename mix-up.

I'm running: 
OS: macOS Sequoia 15.0 
Python: 3.12.6
ComicTagger: v1.6.0b3.dev0
RAR: 7.01
My rar location is set to **/usr/local/bin/rar** (RAR was installed using brew.)

If possible, I'd like to be able convert the CBR files to CBZ to maintain filetype uniformity in my collection.

Has anyone else seen this?

**Comment by lordwelch** [comment]
Somehow I really broke the GUI code for that a while ago. In the mean time you can use the CLI `comictagger -e /path/to/comics/*.cbr`
If you run the CLI on cbz files it has a separate bug where it duplicates files that are already a zip

**Comment by lordwelch** [comment]
CLI doesn't have a bug I just happened to test it on a misnamed CBR

**Comment by lordwelch** [comment]
Fixed in a8f269a. It will be in the next beta
