### ISSUE TITLE
Microsoft Defender warnings when appending metadata

### ISSUE THREAD

**Issue by sqcrtx** [comictagger/comictagger#697]
I get _Trojan:Script/Wacatac.B!ml_ and _Trojan:Script/Sabsik.FL.A!ml_ when batch applying metadata / auto-tagging files. Defender flags _.rar_ files created in temporary files folder (_~\AppData\Local\Temp\\*.rar_) as malicious. Meanwhile scanning the original comic files  (_.cbr, .cbz_) with Defender reveals no threats. 

Is this behavior something that is known?

The comictagger version: 1.6.0a21

**Comment by lordwelch** [comment]
It looks like it's flagging any RAR files in temp directories as malicious. There's nothing I can do about that

**Comment by lordwelch** [comment]
You should be able to change the temp directory by setting the TMPDIR environment variable but no guarantee that Microsoft defender won't still flag it
