### ISSUE TITLE
How do I suppress the settings warning while using the CLI

### ISSUE THREAD

**Issue by kev0153** [comictagger/comictagger#700]
Is there a way to suppress this warning when using the command line interface? I'm already running 1.5.5 - Thank You

!!!Warning!!!
The next release will save settings in a different format
NO SETTINGS WILL BE TRANSFERED to the new version.

**Comment by lordwelch** [comment]
That's because the settings change in the version after 1.5.5.
The release notes explain how the warning works https://github.com/comictagger/comictagger/releases/tag/1.5.5

**Comment by kev0153** [comment]
Thanks so you acknowledge the pop up 4 times and that clears with the GUI.
I’m still not understanding how to clear it using the CLI

Thanks

**Comment by lordwelch** [comment]
It uses the same check to show on the cli

**Comment by kev0153** [comment]
Oh I see.  I guess I'm out of luck since I'm running this on a headless server.  Thanks

**Comment by lordwelch** [comment]
There's an option, somewhere in the settings file, it should be in ~/ComicTagger that you can edit manually

**Comment by kev0153** [comment]
Thanks found it

dont_notify_about_this_version = 1

**Comment by kev0153** [comment]
Ok, no I really have it

settings_warning = 4

I installed the gui on my windows version and found the config file
