### ISSUE TITLE
[Feature Request Return] Populate Series Volume (Start Year)

### ISSUE THREAD

**Issue by rhaussmann** [comictagger/comictagger#706]
I am requesting a feature to capture a series Volume (series start year) field that has moved from the issue resource to the volume resource. My collection's file naming format uses the Volume field to differentiate series with the same name with different runs.

I'm proposing a second call to the volume resource to capture the series start_year and deck values.

This is an example using an issue from volume 3 of Secret Origins.

**Issue Look Up:**
https://comicvine.gamespot.com/api/issue/4000-483313/?api_key=MY_KEY&format=json
$.results.volume.api_detail_url
	[
	  "https://comicvine.gamespot.com/api/volume/4050-73215/"
	]

**Volume Look Up:**
https://comicvine.gamespot.com/api/volume/4050-73215/?api_key=MY_KEY&format=json
$.results.start_year
	[
	  "2014"
	]
$.results.deck
	[
	  "Volume 3."
	]

The request may not be realistic as this would add another API call to the process.

**Comment by rhaussmann** [comment]
I forgot there was a "Use the series start year as the volume number" setting somewhere. I found it in the code but not in the GUI. I'll keep poking at it.

**Comment by lordwelch** [comment]
1.5.5:
<img width="1090" alt="Screenshot 2024-12-01 at 7 04 03 PM" src="https://github.com/user-attachments/assets/86d06718-09d8-4252-9e1c-ba1cf578092b">
1.6.0-beta.2:
<img width="1207" alt="Screenshot 2024-12-01 at 7 04 21 PM" src="https://github.com/user-attachments/assets/e8708734-9f5e-47e2-8b18-2a4064be1870">

**Comment by rhaussmann** [comment]
Thanks. I must have looked at that page 100s of times....
