### ISSUE TITLE
Request: Add ability to determine trade volume by parsing ComicVine data.

### ISSUE THREAD

**Issue by CptanPanic** [comictagger/comictagger#90]
What comic vine calls a volume isn't what I think of a volume.  For example if you get all the volumes of comic "Descender" you get 5 volumes.  The regular monthly comic, the 3 TPBs and the reprint of the first issue.  What I would like is if I had issue 8 of Descender it would know that it is part of TPB volume 2.  There is no straight forward way to do this with comic vine, but you can do this by going through all the above volumes and reading what issues the TPB collects.  What do you think?

**Comment by lordwelch** [comment]
This is unfortunately not feasible to implement with ComicVine nor with the metadata fields available by I believe any format.
The [GCD](https://www.comics.org) has database dumps of mysql tables so it might be able to be used for this. However adding support for the GCD is not currently being looked at as downloading and setting up a mysql database to then be used for individual requests to retrieve metadata is currently not feasible.
