### ISSUE TITLE
Recognize leading number as alternate count

### ISSUE THREAD

**Issue by eduo** [comictagger/comictagger#91]
Sometimes crossed-over comics are named in a checklist or chronological format so they can be read sequentially.

Example (obviously made-up):
```
01 - The Tick #10.cbz
02 - Mystery Men #08.cbz
03 - Concrete #01.cbz
```
Another example are gimmicky countdown schemes.

When loading these into CT they'll usually be parsed properly and the right titles and issue numbers recognized (not sure if by Comictagger or by Comicvine). So they end up auto-tagged properly. When autorenaming, though, this counter would be lost.

Could a prefix either be understood as alternate count or, alternatively, be maintained as an existing prefix?

**Comment by lordwelch** [comment]
This is now supported when the 'Complicated' parser is used
