### ISSUE TITLE
Better error message for empty rar_exe_path

### ISSUE THREAD

**Issue by tlc** [comictagger/comictagger#92]
I inserted pdb calls to step down to the cause of this dialog

> The tag save operation seemed to fail!

It was the fact that `self.rar_exe_path` was not set.  It would
be nicer if we were told what this problem was.

> External RAR writer required.  Configure in Settings.

or 

> Please configure "RAR program" in the General Settings.

**Comment by lordwelch** [comment]
This is resolved in a3e1153.
There is now a popup if a CBR/RAR archive is opened and the rar application is not available
