### ISSUE TITLE
Improve matching with poorly indexed images

### ISSUE THREAD

**Issue by tlc** [comictagger/comictagger#95]
I seem to run into comics containing poorly named files.  The cover is either the last page (due to people who can't alphabetize?) or 2nd because someone stuck another image in front.

On the left side of the GUI is an image viewer.  I use it to find the cover for manual matching.  It'd be a nice enhancement if the selected image was used as the cover for "Search Online".

**OR** comictagger could have the ability to rename that image file within the cbz so it would be first.  The image viewew could have a right-click menu with "Make First" and "Delete" for the extraneous images.

**Comment by lordwelch** [comment]
The current ComicTagger takes the first page or the first page that has the `Page Type` set to `Front Cover`
